### ISSUE TITLE
Terraform vCD provider support for current vCloud API versions

### ISSUE THREAD

**Issue by pasikarkkainen** [terraform-providers/terraform-provider-vcd#101]
Currently terraform-provider-vcd seems to be using vCloud API version 5.5 (as defined in govcloudair / go-vcloud-director library api_vcd.go).

vCloud Director 9.5 completely removed support for old vCloud API versions, so 5.5 is not supported anymore. Support for vCloud API version 5.5 was already deprecated in previous vCloud Director 9.1 release.

What's the plan to get Terraform vcd provider working against vCloud Director 9.5, and later (than 5.5) API versions ?

**Comment by lvirbalas** [comment]
Hi @pasikarkkainen 

Incidentally, we had been working on this and have just merged the API upgrade to vmware-takes-ownership branch last night :) It was handled by this PR:
Upgrade API version from 5.5 to 27.0 #118

Please give it a try! I will close this issue now. If you find an issue, don't hesitate to reopen with a comment and we'll take a look.
