### ISSUE TITLE
Default 30m timeout is too short for running acceptance tests

### ISSUE THREAD

**Issue by lvirbalas** [terraform-providers/terraform-provider-vcd#111]
Default 30 min timeout in `GNUmakefile` for `testacc` should be extended to 45 min to have more reliable test runs in slow environments.

### Affected Resource(s)

This affect acceptance tests.

### Configuration Files

Note: running the `make testacc` with additional parameter for network tests to not timeout:
```
VCD_MAX_RETRY_TIMEOUT=300
```

### Output

Below is execution time of a all the tests on a not fast vCD environment. I extended the timeout for the tests to pass, and you can see it took 33 mins:

```
PASS
ok  	github.com/terraform-providers/terraform-provider-vcd/vcd	1987.812s

Process finished with exit code 0
```

### Expected Behavior

Tests should pass without the need to change `GNUmakefile`.

### Actual Behavior

I had to extend the timeout from 30m to 45m inside the `GNUmakefile`:
```
testacc: fmtcheck
	if [ ! -f vcd/vcd_test_config.json ] ; then \
		echo "ERROR: test configuration file vcd/vcd_test_config.json is missing"; \
		exit 1; \
	fi
	cd vcd ; TF_ACC=1 go test -v . -timeout 45m
```

### Steps to Reproduce

1. Prepare a valid `vcd_test_config.json` in vcd/
2. `export VCD_MAX_RETRY_TIMEOUT=300`
3. `make testacc`

**Comment by dataclouder** [comment]
Increased the timeout from 30 to 45 minutes.

**Comment by lvirbalas** [comment]
Thanks :)
