### ISSUE TITLE
Impossible to assign IP Mode "Static-IP Pool" to a NIC

### ISSUE THREAD

**Issue by WildWon** [terraform-providers/terraform-provider-vcd#116]
Hi there,

When deploying a vm from template it seems to be impossible to assign IP mode "Static-IP Pool" to a NIC. In the configuration file it is either possible to specify an IP address, i.e. ip = "10.10.10.10", which results in IP mode "Static-Manual", or you don't provide a value for ip = "" which will result in IP mode "DHCP". Alternatively you can drop the line ip = "" which will also result in IP mode "DHCP".

### Terraform Version
Terraform v0.11.10
+ provider.vcd (unversioned) built from (git commit 704012e) of the "vmware-takes-ownership" branch

### Affected Resource(s)
resource "vcd_vapp_vm"

### Terraform Configuration Files
```hcl
resource "vcd_network" "net00" {
        name = "${var.vcdnet_name}"
        edge_gateway = "${var.vcdnet_edge_gateway}"
        gateway = "${var.vcdnet_gateway}"

        static_ip_pool {
                start_address = "${var.vcdnet_static_ip_pool_start}"
                end_address = "${var.vcdnet_static_ip_pool_end}"
        }
}

resource "vcd_vapp_vm" "my_vm01" {
	vapp_name = "${var.vappname}"
	name = "${var.vmnamewin}"
	catalog_name = "${var.catalognamewin}"
	template_name = "${var.templatenamewin}"
	memory = 4096
	cpus = 2
	ip = ""
	power_on = false
	network_name = "${vcd_network.net00.name}"
}
```

### Debug Output
n/a

### Panic Output
n/a

### Expected Behavior
Since vCloud offers multiple IP modes for a NIC I would expect to be able to declare which mode to use.

### Actual Behavior
Currently it's only possible to work with two of the possibe three IP mode options. Unfortunately the mode we'd prefer to use is number three.

### Steps to Reproduce
This can be easily reproduced by deploying a new vm to a vCloud instance

### Important Factoids
n/a

### References
n/a

**Comment by vbauzysvmware** [comment]
Hi @WildWon 
Please try `ip = "allocated"`.
I tried and as in documentation stated `allocated` means static ip pool.

**Comment by dn1s** [comment]
This issue should be closed correct answer how to solve the issue was given by @vbauzysvmware .

**Comment by lvirbalas** [comment]
@WildWon closing the issue as answer was given above, but if you have any more comments, please comment/reopen.

**Comment by StanGanin** [comment]
What would be the correct way to get the IP of the VM when using 'allocated'?

**Comment by lvirbalas** [comment]
@StanGanin are you referring to the issue during read (referencing below)?
#50
#176

**Comment by StanGanin** [comment]
No, I had no idea that the self reference contained the allocated IP, but that is what I actually needed.
