### ISSUE TITLE
Implement Insert Catalog Media for VM resource

### ISSUE THREAD

**Issue by vbauzysvmware** [terraform-providers/terraform-provider-vcd#126]
Feature request for a new Insert Catalog Media for VM resource
### Context

Recently, we have added ability to upload Media to catalog.
Now we need ability to insert Media to VM as CD/DVD and it will be mounted and can boot up using ISO.

Let's implement a new resource in Terraform to be able to insert Media as part of the Terraform plan apply.
### Affected Resource(s)

Addition of the Insert Media will be useful for the following resources: 

-  vcd_vapp_vm 

### Terraform Configuration Files

Suggested configuration:

```hcl
resource "vcd_inserted_media" "PhotonISO" {
org = "Solpan" # Optional, if defined at provider level
catalog = "OperatingSystems" # In which catalog Media file exists
name = "Photon-3.0-Beta"

vapp_name="new_VAPP1"
vm_name="new_VM1"
}
```

### Expected Behavior

Terraform vCD provider should insert media ISO file as CD/DVD to VM. It should wait until mount is finished. Destroying resource will umount media ISO file from VM (detach).

### References

Few old intro videos on these topics (the vCD clips are actual):
https://www.youtube.com/watch?v=SIk5S_inCw8
https://www.youtube.com/watch?v=3S8dWAraosU

**Comment by lvirbalas** [comment]
@vbauzysvmware thanks for an issue write up!

One suggestion is about the naming of the media resource. Resources should be nouns (as opposed to verbs), so what about an adjusted name:  `vcd_inserted_media`. On a noun succeeding semantics on it (like destroy operation) flow out naturally - you "destroy" an "insert**ed** media".

Note: in vCD API there is `insert` and `eject` media notions.

**Comment by vbauzysvmware** [comment]
Resource name updated.
> @vbauzysvmware thanks for an issue write up!
> 
> One suggestion is about the naming of the media resource. Resources should be nouns (as opposed to verbs), so what about an adjusted name: `vcd_inserted_media`. On a noun succeeding semantics on it (like destroy operation) flow out naturally - you "destroy" an "insert**ed** media".
> 
> Note: in vCD API there is `insert` and `eject` media notions.

**Comment by ybaumy** [comment]
the initial description sounds good to me. Since the iso items will remain in the catalog as long as the VM exists, we would need a remove catalog item function as well.

**Comment by vbauzysvmware** [comment]
Terraform destroy for Insert will Eject ISO file and Media resource destroy will remove ISO file from catalog.

**Comment by vbauzysvmware** [comment]
@ybaumy Feature available in vmware-stash-while-master-pr-open branch at the moment.

**Comment by ybaumy** [comment]
@vbauzysvmware have to test but probably will find time not before next week.

**Comment by vbauzysvmware** [comment]
@ybaumy Have you find time to try it?:)

**Comment by ybaumy** [comment]
Will try to do that tomorrow. Sorry for the delay.

**Comment by vbauzysvmware** [comment]
Just wanted to note that code is in master with all new functionality and binary automatically can be download with Terraform.

**Comment by ybaumy** [comment]
Sorry but I was testing on Friday last week when i ran into errors. Now I am sick at home the complete week. Will be in the office on Monday and will try again.
