### ISSUE TITLE
Tests shouldn't require pre-existing catalog and should create it instead

### ISSUE THREAD

**Issue by lvirbalas** [terraform-providers/terraform-provider-vcd#137]
Now that we have functionality to create catalogs, tests shouldn't have a prerequisite for existing catalog - they should just create it.

### Affected Files

- vcd/sample_vcd_test_config.json
- vcd/vcd_test_config.json
- make testacc

### Test Configuration Files

We need to  define the following section in `vcd_test_config.json`

```json
# ...
 "vcd": {
    "//": "This section contains the organization composition",
    "org": "Solpan",
    "vdc": "SolpanVDC",
    "catalog": {
      "name": "OperatingSystems",
      "catalogItem": "MicroCore-Linux.ova"
    }
  }
# ...
```

### Expected Behaviour

We would expect that the above catalog is created automatically.

### Actual Behavior

If catalog doesn't exist in vCD (like in a fresh instance), an error is thrown:

```
--- FAIL: TestAccVcdCatalogItemBasic (10.52s)
    testing.go:434: Step 0 error: Error applying: 1 error(s) occurred:

        * vcd_catalog_item.TestAccVcdCatalogItemBasic: 1 error(s) occurred:

        * vcd_catalog_item.TestAccVcdCatalogItemBasic: error finding Catalog: <nil>
```

### Important Factoids

We need to adjust the catalog tests so they create the catalog, upload the item and media and then destroy the catalog. This will remove one prerequisite from test environment and will make running tests easier.

**Comment by lvirbalas** [comment]
> I think the catalog name should be pre-configured as a constant by the test suite, and have a name that reflects its origin, such as TestUploadCatalogItem.

I agree, only the name for this test case should not contain "Item" - only "Catalog", something like "TestCreateCatalog".

**Comment by lvirbalas** [comment]
> Another thing to take into account is that the test suite will become slower when the OVA needs to be uploaded before every other operation starts. We may want to let in place the current setting, so that users may decide to run a quicker test with an existing catalog and item, rather than uploading a new one at every test run.

Not an issue. Default OVA for test is small and it takes around a minute to pass.

```
=== RUN   TestAccVcdCatalogItemBasic
vcd_catalog_item.TestAccVcdCatalogItemBasic: Upload progress 0.00%
vcd_catalog_item.TestAccVcdCatalogItemBasic: Upload progress 100.00%
vcd_catalog_item.TestAccVcdCatalogItemBasic: vCD import catalog item progress 1%
vcd_catalog_item.TestAccVcdCatalogItemBasic: vCD import catalog item progress 1%
vcd_catalog_item.TestAccVcdCatalogItemBasic: vCD import catalog item progress 100%
--- PASS: TestAccVcdCatalogItemBasic (76.03s)
```

Compare that to the following test case, which takes 16 minutes (?!). This one is a much more pressing issue.

```
=== RUN   TestAccVcdVApp_PowerOff
--- PASS: TestAccVcdVApp_PowerOff (1000.30s)
```

**Comment by dataclouder** [comment]
Probably the name should be more general, because the purpose is not only to create a catalog, but to support a large part of the test suite. So, it should have a name that shows that it is created at the start of the suite, used for many tests, and removed at the end.

**Comment by lvirbalas** [comment]
That's a good point.

Actually, reflecting on this, it's a question whether current default test OVA `../test-resources/test_vapp_template.ova` is good enough for the VM tests.

**Comment by dataclouder** [comment]
About the timing, don't forget that the upload test uses a 80 KB OVA, while a more realistic OVA is at least 100 MB.

**Comment by vbauzysvmware** [comment]
So to summarize: 
* Idea is remove catalog and catalogItem from config.json as they will be created in testsuite and dropped after all test played with them
* currently vapp and vm test uses these prepared vapptemplates for their test, I am not sure they will work with dummy (80kb) we have now

**Comment by lvirbalas** [comment]
> Idea is remove catalog and catalogItem from config.json as they will be created in testsuite and dropped after all test played with them

Correct. To be more precise, this section can be removed completely:

```hcl
    "catalog": {
      "name": "OperatingSystems",
      "catalogItem": "MicroCore-Linux.ova"
    }
```

These sections however should be kept as is:

```hcl
  "ova": {
    "ovaPath": "../test-resources/test_vapp_template.ova",
    "//": "Size in megabytes",
    "uploadPieceSize": 5,
    "uploadProgress": true
  },
  "media": {
    "mediaPath": "../test-resources/test.iso",
    "//": "Size in megabytes",
    "uploadPieceSize": 5,
    "uploadProgress": true
  }
```

OVA from `ova.ovaPath` should be used as the new "golden" OVA, replacing the old `catalog.catalogItem`.

> currently vapp and vm test uses these prepared vapptemplates for their test, I am not sure they will work with dummy (80kb) we have now

Right, though we don't know that yet. If that's the case we should replace the default `../test-resources/test.iso` with the smallest yet safest OVA which works:
- This will have to be a thousand times larger photon-custom-hw11-2.0-304b817.ova (108M) by default
- When you want to run tests faster, you can set ovaPath to a smaller OVA like MicroCore-Linux.ova (11M).

**Comment by vbauzysvmware** [comment]
In that case we have to add ~120mb to git repo.

**Comment by lvirbalas** [comment]
I don't mind that. However, alternative is to create a target `download-photon` in GNUmakefile, which would download the file to `test-resources/` if it doesn't exist and run the tests like this by default:

```
make download-photon
make testacc
```

**Comment by dataclouder** [comment]
I think that adding a large blob to the repository is a bad idea. 
Besides, GitHub complains loudly when you add a file larger than 50 MB.
Alternatives:
1. Let users define which OVAs want to upload to the test catalog.
2. Add the URL to the recommended OVA and use that one without bloating the repository.

**Comment by lvirbalas** [comment]
See my comment above, this is exactly the place where makefile can help.
