### ISSUE TITLE
RFE: Allow configuring VM affinity and anti-affinity rules

### ISSUE THREAD

**Issue by pasikarkkainen** [terraform-providers/terraform-provider-vcd#140]
Currently terraform-provider-vcd does not support vCloud Director VM affinity / anti-affinity rules.

They're useful for example for:
- Keeping certain VMs on the same physical host, for example VMs which should have low latency between each other, and/or high throughput between each other.
- Keeping VMs of a HA cluster on different physical hosts, so that if there's a physical host failure it will only affect one of the VMs, not multiple VMs, and the HA cluster keeps working.

vCloud Director documentation "Virtual Machine Affinity and Anti-Affinity":
https://pubs.vmware.com/vcd-820/topic/com.vmware.vcloud.user.doc/GUID-103BE81A-0762-45C6-915D-19B2B75DEE05.html

vCloud API docs:
https://code.vmware.com/doc/preview?id=5960#/doc/GUID-76B6FD76-C036-4FEC-9B39-D9C79B8F5A92.html
https://vdc-repo.vmware.com/vmwb-repository/dcr-public/76f491b4-679c-4e1e-8428-f813d668297a/a2555a1b-22f1-4cca-b481-2a98ab874022/doc/doc/types/VmAffinityRuleType.html
https://vdc-repo.vmware.com/vmwb-repository/dcr-public/76f491b4-679c-4e1e-8428-f813d668297a/a2555a1b-22f1-4cca-b481-2a98ab874022/doc/doc/types/VmAffinityRulesType.html

"Affinity and anti-affinity rules allow you to spread a group of virtual machines across different hosts or keep a group of virtual machines on a particular host."

vCloud Director supports VM affinity/anti-affinity feature since version 8.10.

**Comment by lvirbalas** [comment]
Good feature request! Thank you. BTW, are you from TeliaSonera by chance? :)

**Comment by pasikarkkainen** [comment]
@lvirbalas nope, but from the same region indeed :) working with multiple service providers here.

**Comment by tobru** [comment]
I would _love_ to see this feature. Setting Affinity and Anti-Affinity is a very important task when setting up infrastructure for clustered systems.

**Comment by lvirbalas** [comment]
@vbauzysvmware I believe you'll be in a good position to tackle this one once we get our heads up from current work.

Unless, someone from community want to have a crack at it without waiting?

**Comment by jlarmstrong** [comment]
This is still a needed feature.

**Comment by d2rj2** [comment]
Any update on this one? Waiting for it as well :) Thanks.

**Comment by lvirbalas** [comment]
We added it to the near roadmap, so it's a matter of time.
CC: @dataclouder

**Comment by dataclouder** [comment]
Implemented with PR #514 and released in terraform-probider-vcd 2.9.0
