### ISSUE TITLE
Replace vendor folder with go modules

### ISSUE THREAD

**Issue by dataclouder** [terraform-providers/terraform-provider-vcd#146]
The [Terraform repository](https://github.com/hashicorp/terraform) is using [Go Modules](https://github.com/golang/go/wiki/Modules) as supported by Go 1.11.

We should upgrade our repository to use the newest Go version. This has two practical implications:

1. The code formatting has changed, meaning that code formatted for 1.10 may not be always considered correctly formatted by 1.11. We need to re-format all our code base.

2. The vendor directory can be dismissed, and replaced by [Go Modules](https://github.com/golang/go/wiki/Modules), which imports repositories based on their version tags.

This issue is directly connected to [Issue 139](https://github.com/vmware/go-vcloud-director/issues/139) in `go-vcloud-director`.

**Comment by Didainius** [comment]
We have moved to Go 1.12 with #178, but vendor directory will stay a bit longer here. It doesn't require much effort from now on as we rebuild it with `go mod vendor` from our `go.mod` module definition.
