### ISSUE TITLE
apply ko with vmware-takes-ownership // org not found

### ISSUE THREAD

**Issue by merlin145160** [terraform-providers/terraform-provider-vcd#150]
Hi 
I've successfully build the plugin from vmware-takes-ownership yesterday.
Everything seems fine but 
$ terraform apply "plan"
fails with couldn't find org with name

$ terraform -v
Terraform v0.11.11
\+ provider.vcd (unversioned)
$ go version
go version go1.11.4 linux/amd64
$ terraform init

Initializing provider plugins...

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.

$ terraform plan --out plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

\------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  + vcd_network.org_netkubernetes
      id:                                     <computed>
      dns1:                                   "8.8.8.8"
      dns2:                                   "8.8.4.4"
      edge_gateway:                           "vCDESG_INET_S1_S3"
      gateway:                                "10.10.0.1"
      href:                                   <computed>
      name:                                   "OrgNet-Kubernetes"
      netmask:                                "255.255.255.0"
      shared:                                 "false"
      static_ip_pool.#:                       "1"
      static_ip_pool.241192955.end_address:   "10.10.0.200"
      static_ip_pool.241192955.start_address: "10.10.0.10"

Plan: 1 to add, 0 to change, 0 to destroy.

\------------------------------------------------------------------------

This plan was saved to: plan

To perform exactly these actions, run the following command to apply:
    terraform apply "plan"

	
$ terraform apply "plan"
vcd_network.org_netkubernetes: Creating...
  dns1:                                   "" => "8.8.8.8"
  dns2:                                   "" => "8.8.4.4"
  edge_gateway:                           "" => "vCDESG_INET_S1_S3"
  gateway:                                "" => "10.10.0.1"
  href:                                   "" => "<computed>"
  name:                                   "" => "OrgNet-Kubernetes"
  netmask:                                "" => "255.255.255.0"
  shared:                                 "" => "false"
  static_ip_pool.#:                       "" => "1"
  static_ip_pool.241192955.end_address:   "" => "10.10.0.200"
  static_ip_pool.241192955.start_address: "" => "10.10.0.10"

Error: Error applying plan:

1 error(s) occurred:

\* vcd_network.org_netkubernetes: 1 error(s) occurred:

\* vcd_network.org_netkubernetes: error retrieving Org and VDC: error retrieving Org MyOrg: organization 'MyOrg' fetch failed: &errors.errorString{s:"couldn't find org with name: MyOrg"}

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

$ cat vdc.tf
variable "net_kubernetes" { default = "10.10.0.0/24" }

\# Configure the VMware vCloud Director Provider
provider "vcd" {
  user                 = "terraform"
  password             = "xxxxxxxxx"
  org                  = "MyOrg"
  url                  = "https://apivcloud.interne/api"
  vdc                  = "VDC_kubernetes"
  max_retry_timeout    = "160"
  allow_unverified_ssl = "true"
}

\# Create Kubernetees networks
resource "vcd_network" "org_netkubernetes" {
    name = "OrgNet-Kubernetes"
    edge_gateway = "vCDESG_INET_S1_S3"
    gateway = "${cidrhost(var.net_kubernetes, 1)}"
    static_ip_pool {
        start_address = "${cidrhost(var.net_kubernetes, 10)}"
        end_address = "${cidrhost(var.net_kubernetes, 200)}"
    }
}

**Comment by lvirbalas** [comment]
Hi @merlin145160 , does letter case match for Org and VDC to what is inside vCD?

**Comment by vbauzysvmware** [comment]
I recommend to check Org and VDC as they are case sensitive.

**Comment by merlin145160** [comment]
You were right: org name are case sensitive which was not the case with the old plugin.
Thank you very much @vbauzysvmware and @lvirbalas
