### ISSUE TITLE
Index out of range when creating new vm

### ISSUE THREAD

**Issue by spengilley** [terraform-providers/terraform-provider-vcd#157]
### Terraform Version
0.11.11

### Affected Resource(s)
vcd_~vapp_vm

### Terraform Configuration Files
```hcl
# * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
# Create a vApp
# * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
resource "vcd_vapp" "master" {
    name         = "master"
    depends_on   = ["vcd_network_routed.INTERNET"]
}

# * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
# Create a Vm
# * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
resource "vcd_vapp_vm" "master" {
    vapp_name     = "${vcd_vapp.master.name}"
    name          = "master"
    
    # Define the catalog and template
    catalog_name  = "VANILLA"
    template_name = "VANILLA"

    # Give the app internet access so that it can be provisioned
    # This network resource is defined in networks.tf
    network_name  = "${vcd_network_routed.INTERNET.name}"
    ip            = "192.168.30.2"
    
    # Do enough to be able to run puppet agent
    # These steps are specifically for a puppet agent
    # provisioner "remote-exec" {
    #     inline    = [
    #         "apt-get update && apt-get install -y puppet",
    #         "echo ${local.flavour}:01 > /flavour.txt"
    #     ]
    # } 

    # These steps are specifically for a puppet master
    provisioner "remote-exec" {
        inline    = [
            "apt-get update && apt-get install -y unzip"
        ]
    }
}

```

### Panic Output
https://gist.github.com/spengilley/5e6b0210a23b6d269c0e13d253510005

### Expected Behavior
Create vm

### Actual Behavior
crashes

### Steps to Reproduce
1. `terraform apply`

- GH-1234

### Comment from Developer

In issue real error is that vApp template returned something but not fully what was expected and govcd panicked. According user issue was that vApp template(OVA) wasn't uploaded successfully. I couldn't recreate same error but got different null pointer exception when ova is partly uploaded. I added check that before using vApp template to check it status. Status 8 is parsed from responses - didn't find explanations in documentations. When vApp template was with error then status was 0.
-> Add check for vApp template to be valid #151

**Comment by vbauzysvmware** [comment]
Which branch or version of provider you are using?
Is any possibility to get `template_name = "VANILLA"` ? cause at first glance seems something missing there.

**Comment by spengilley** [comment]
I'm using latest master

This occurred because the template I was using hadn't uploaded successfully into the catalog. Suggests that the error caused by t his needs to be handled rather than Terraform crashing

**Comment by vbauzysvmware** [comment]
I will look for possibility to add additional check.

**Comment by vbauzysvmware** [comment]
@spengilley Would be nice, if you could verify that changein PR solves this issue.

**Comment by spengilley** [comment]
I actually can't at the minute because I am making use of the VM that I have provisioned... Give me this week and hopefully by the end of it I will be in a position to run this script again...

Thanks for implementing a fix :)

**Comment by vbauzysvmware** [comment]
In issue real error is that vApp template returned something but not fully what was expected and govcd panicked. According user issue was that vApp template(OVA) wasn't uploaded successfully. I couldn't recreate same error but got different null pointer exception when ova is partly uploaded. I added check that before using vApp template to check it status. Status 8 is parsed from responses - didn't find explanations in documentations. When vApp template was with error then status was 0. - > Add check for vApp template to be valid #151
