### ISSUE TITLE
[PROPOSAL] Switch to Go Modules

### ISSUE THREAD

**Issue by appilon** [terraform-providers/terraform-provider-vcd#162]
As part of the preparation for Terraform v0.12, we would like to migrate all providers to use [Go Modules](https://github.com/golang/go/wiki/Modules). We plan to continue checking dependencies into vendor/ to remain compatible with existing tooling/CI for a period of time, however go modules will be used for management. Go Modules is the official solution for the go programming language, we understand some providers might not want this change yet, however we encourage providers to begin looking towards the switch as this is how we will be managing all Go projects in the future. Would maintainers please react with :+1: for support, or :-1: if you wish to have this provider omitted from the first wave of pull requests. If your provider is in support, we would ask that you avoid merging any pull requests that mutate the dependencies while the Go Modules PR is open (in fact a total codefreeze would be even more helpful), otherwise we will need to close that PR and re-run `go mod init`. Once merged, dependencies can be added or updated as follows:

```
$ GO111MODULE=on go get github.com/some/module@master
$ GO111MODULE=on go mod tidy
$ GO111MODULE=on go mod vendor
```

GO111MODULE=on might be unnecessary depending on your environment, this example will fetch a module @ master and record it in your project's go.mod and go.sum files. It's a good idea to tidy up afterward and then copy the dependencies into vendor/. To remove dependencies from your project, simply remove all usage from your codebase and run:

```
$ GO111MODULE=on go mody tidy
$ GO111MODULE=on go mod vendor
```

Thank you sincerely for all your time, contributions, and cooperation!

**Comment by lvirbalas** [comment]
Hi @appilon 

We are planning to switch to Go Modules. @dataclouder is working on this. We even have an issue for this :)
#146 

However, the timing is of essence as we need to align with vCloud Director releases. Please help to understand:

> Would maintainers please react with 👍 for support, or 👎 if you wish to have this provider omitted from the first wave of pull requests.

1. When is the first wave planned?
2. When should we switch to Go Modules to react with 👍 to your message?

> If your provider is in support, we would ask that you avoid merging any pull requests that mutate the dependencies while the Go Modules PR is open

3. Are you referring to pull requests to master in our provider?
4. Which Go Modules PR?

Thanks for helping out!

CC: @dataclouder @vbauzysvmware

**Comment by dataclouder** [comment]
Hi @appilon,
I would like a clarification on a point that you have mentioned.

> ﻿﻿﻿﻿copy the dependencies into vendor

Why do we still need the vendor if we are using modules?

Thanks in advance

**Comment by paultyng** [comment]
@dataclouder there are a number of reasons. We haven't yet upgraded all the build scripts as we can't fully until everything is on modules, and we do not yet have a module proxy setup / running yet, so its easiest on the build system if all the dependencies are cached, otherwise that is a lot of git activity in each build that would significantly slow it down (and probably get us tagged for GitHub abuse).

**Comment by appilon** [comment]
Hello @lvirbalas I will answer your questions with numbers

1) We don't have an explicit timeline however we encourage the switch as soon as possible, we were probably going to explore automating a wave of pull requests in the next few weeks

2) Reacting is so we could programmatically (via the GH API) collect the providers who are in support and tackle them first. Feel free to react, if you are handling modules yourselves we won't interfere (unless you need support!)

3) We had an instance where we had the modules PR open, but unfortunately another PR made it in that just so happened to add a new dependency with the old tool. It's not a big deal, but in that scenario you need to open a new PR running `go mod init` again.

4) The PR doesn't exist yet. To be clear we were planning on using this mass issue (we sent it to every provider) to collect the list of providers to try and automatically (in a perfect world) open modules switched PRs for. As you mentioned it appears its already in progress so carry on!

**Comment by Didainius** [comment]
@appilon, starting with d231051 we're coming there (not yet in master).
Could you elaborate on what HC build environment uses now. We're set to maintain vendor with `go mod vendor` but would want to know if there are any specific requirements to make builds work. 
Do let us know if we have to do any extra homework.
Thanks

**Comment by Didainius** [comment]
Done. 2.1 is using Go modules.
