### ISSUE TITLE
Problems uploading to catalog

### ISSUE THREAD

**Issue by mdacrema** [terraform-providers/terraform-provider-vcd#167]
Hi,
I've problems uploading ISOs or OVAs through vcd_catalog_item and vcd_catalog media resources.
Terraform exits with:
error finding Catalog: &errors.errorString{s:"error retrieving catalog: Get https:///.c2.kvdc.it/api: http: no Host in request URL"} 

Catalog has been found because if I specify a non-existent catalog the error is:
vcd_catalog_item.OVA01: error finding Catalog: <nil>

Thank you
Matteo
-------------
### Terraform Version
Terraform v0.11.11
+ provider.vcd v2.0.0

### Affected Resource(s)

vcd_catalog_item
vcd_catalog_media

### Terraform Configuration Files
vcd_user = "admin"
vcd_org = "*************"
vcd_vdc = "*************"
vcd_url = "https://***.***.kvdc.it/api/"
vcd_pass = "************"
vcd_edge = "*************"

provider "vcd" {
  user                 = "${var.vcd_user}"
  password             = "${var.vcd_pass}"
  org                  = "${var.vcd_org}"
  url                  = "${var.vcd_url}"
  vdc                  = "${var.vcd_vdc}"
  allow_unverified_ssl = "true"
}

resource "vcd_catalog_item" "OVA01" {
  org                  = "****************"
  catalog              = "test"
  name                 = "Portus"
  ova_path             = "/terraform/vcloud/media/ecs-portus-vmware-52-master.ova"
  upload_piece_size    = 10
  show_upload_progress = true
}

### Expected Behavior
Image is uploaded to the catalog

### Actual Behavior
Terraform exit with:
1 error(s) occurred:

* vcd_catalog_item.OVA01: 1 error(s) occurred:

* vcd_catalog_item.OVA01: error finding Catalog: &errors.errorString{s:"error retrieving catalog: Get https:///.c2.kvdc.it/api: http: no Host in request URL"}

### Steps to Reproduce
terraform apply

### Important Factoids
VMware vCloud Director 9.0

**Comment by lvirbalas** [comment]
> https:///.c2.kvdc.it/api
The URL looks broken.

**Comment by mdacrema** [comment]
@lvirbalas yes, but the one I provided is not broken and it work with other resources

**Comment by lvirbalas** [comment]
@mdacrema Sorry, but I don't understand. Aren't you providing the following host in configuration?
```
vcd_url = "https://***.***.kvdc.it/api/"
```

> * https:///.c2.kvdc.it/api: http: no Host in request URL
There are three forward slashes at the beginning and host begins with a dot, so Terraform complains.

**Comment by vbauzysvmware** [comment]
@mdacrema `no Host in request URL` is internal HTTP lib error. So I recommend to check API URL and verify the link. A different but with URL issue was here too: https://github.com/terraform-providers/terraform-provider-vcd/issues/12

**Comment by mdacrema** [comment]
@lvirbalas @vbauzysvmware I double checked the API URL and it's correct. I also tried creating VMs and networks using the same vars and it works. Could it be related to an incorrect api response from vCloud Director or a misconfiguration of it?

**Comment by vbauzysvmware** [comment]
@mdacrema Maybe something wrong with url construct in your specific case. Could you provide the govcd logs?  It can be turned on with `logging= "true"` https://www.terraform.io/docs/providers/vcd/index.html#logging

**Comment by mdacrema** [comment]
@vbauzysvmware you can find the logs for the single "terraform apply" here: https://pastebin.com/fsx3HxFM

**Comment by vbauzysvmware** [comment]
Thank you @mdacrema. Now we figure out the issue. Is due url you are using http://admin... . We will make fix in govcd and then we will incorporate in terraform and this will took a little. And if you are using binary - you have to wait for release. Well, temporarily you can change url to use IP Address or change dns name "admin" part to something else.

**Comment by mdacrema** [comment]
@vbauzysvmware ok thank you very much! It still doesn't work with IP address. I think it's because of the API response that contains URLs with "admin".

**Comment by vbauzysvmware** [comment]
Could you provide logs with IP address, I hope I could identify workaround until fix comes around.

**Comment by mdacrema** [comment]
@vbauzysvmware https://pastebin.com/kmA9nJXf

**Comment by vbauzysvmware** [comment]
@mdacrema Yes, IP address works only for direct calls, vCD endpoint is configured to use FQDN and responds with name - not IP. `find catalog` finds URL in reponse where address isn't IP.

**Comment by mdacrema** [comment]
@vbauzysvmware any idea about when it will be fixed?

**Comment by vbauzysvmware** [comment]
I have fix ready.. but we have urgent request to move on to go modules - as result other PR stopped :-(

**Comment by vbauzysvmware** [comment]
@mdacrema You can try master or in day or two we expect binary release 2.1.0 ;-)

**Comment by vbauzysvmware** [comment]
2.1 version released with the fix. Let me us know it it's good now :)
