### ISSUE TITLE
vcd_app_vm: VMs are not powered on if "power_on" change

### ISSUE THREAD

**Issue by mdacrema** [terraform-providers/terraform-provider-vcd#170]
Hi there,

I need to boot the VM with CD-ROM attached.
To do this I create the VM with power_on=false then I attach the ISO and then I issue again VM creation with power_on=true.
VM remain off. Is there another way to do this? Is it correct that VM is still off?

### Terraform Version
Terraform v0.11.10
+ provider.consul v2.2.0
+ provider.external v1.0.0
+ provider.null v2.0.0
+ provider.random v2.0.0
+ provider.template v2.0.0
+ provider.vcd v2.0.0

### Affected Resource(s)
vcd_vapp_vm 
vcd_vapp

### Terraform Configuration Files
```
resource "vcd_vapp" "vApp" {
 name = "vApp_${var.name}"
 network_name = "${var.network_name}"
}

resource "vcd_vapp_vm" "instance" {
 vapp_name = "vApp_${var.name}"
 count = "${var.quantity}"
 name = "${var.name}-${count.index}"
 catalog_name  = "${var.catalog}"
 template_name = "${data.external.image_sync.result.template_name}"
 memory = "${var.memory}"
 cpus = "${var.cpus}"
 network_name = "${var.network_name}"
 depends_on = ["vcd_vapp.vApp"]
 power_on = "false"
}
resource "vcd_inserted_media" "ISO" {
 count = "${var.quantity}"
 catalog = "${var.catalog}"
 name = "${var.name}-${count.index}-user-data.iso"
 vapp_name = "vApp_${var.name}"
 vm_name = "${var.name}-${count.index}"
 depends_on = ["vcd_vapp_vm.instance"]
}

resource "vcd_vapp_vm" "instance_on" {
 vapp_name = "vApp_${var.name}"
 count = "${var.quantity}"
 name = "${var.name}-${count.index}"
 catalog_name  = "${var.catalog}"
 template_name = "${data.external.image_sync.result.template_name}"
 memory = "${var.memory}"
 cpus = "${var.cpus}"
 network_name = "${var.network_name}"
 depends_on = ["vcd_vapp.vApp"]
 power_on = "true"
}
```

### Expected Behavior
VMs should be turned on

### Actual Behavior
VMs are still off

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
`terraform apply`

## Terrafrom output
module.etcd.module.etcd.vcd_vapp_vm.instance[0]: Creating...
  accept_all_eulas: "" => "true"
  catalog_name:     "" => "Privato"
  cpus:             "" => "1"
  href:             "" => "<computed>"
  ip:               "" => "<computed>"
  memory:           "" => "4096"
  name:             "" => "etcd-0"
  network_name:     "" => "TerraformNetwork01"
  power_on:         "" => "false"
  template_name:    "" => "ecs-etcd-master-21-2"
  vapp_name:        "" => "vApp_etcd"
module.etcd.etcd.vcd_vapp_vm.instance.0: Still creating... (10s elapsed)
module.etcd.etcd.vcd_vapp_vm.instance.0: Still creating... (20s elapsed)
module.etcd.etcd.vcd_vapp_vm.instance.0: Still creating... (30s elapsed)
module.etcd.etcd.vcd_vapp_vm.instance.0: Still creating... (40s elapsed)
module.etcd.etcd.vcd_vapp_vm.instance.0: Still creating... (50s elapsed)
module.etcd.module.etcd.vcd_inserted_media.ISO[0]: Creating...
  catalog:   "" => "Privato"
  name:      "" => "etcd-0-user-data.iso"
  vapp_name: "" => "vApp_etcd"
  vm_name:   "" => "etcd-0"
module.etcd.module.etcd.vcd_inserted_media.ISO[0]: Creation complete after 7s (ID: vApp_etcd_etcd-0_etcd-0-user-data.iso)
module.etcd.module.etcd.vcd_vapp_vm.instance_on[0]: Creating...
  accept_all_eulas: "" => "true"
  catalog_name:     "" => "Privato"
  cpus:             "" => "1"
  href:             "" => "<computed>"
  ip:               "" => "<computed>"
  memory:           "" => "4096"
  name:             "" => "etcd-0"
  network_name:     "" => "TerraformNetwork01"
  power_on:         "" => "true"
  template_name:    "" => "ecs-etcd-master-21-2"
  vapp_name:        "" => "vApp_etcd"
module.etcd.etcd.vcd_vapp_vm.instance_on.0: Still creating... (10s elapsed)
module.etcd.etcd.vcd_vapp_vm.instance_on.0: Still creating... (20s elapsed)
module.etcd.etcd.vcd_vapp_vm.instance_on.0: Still creating... (30s elapsed)
module.etcd.etcd.vcd_vapp_vm.instance_on.0: Still creating... (40s elapsed)
module.etcd.etcd.vcd_vapp_vm.instance_on.0: Still creating... (50s elapsed)
module.etcd.etcd.vcd_vapp_vm.instance_on.0: Still creating... (1m0s elapsed)

**Comment by vbauzysvmware** [comment]
Interesting case. I don't see any errors and logs so would hard to guess the core error. Nevertheless I recreated case and it won't work that way. Yours Terraform `instance_on` will try to create new instance cause Terraform treat it as new resource and you will get similar to this `"error instantiating a new VM: API Error: 400: [ d5506278-a285-4df0-a456-6b483a7f1d9f ] There is already a VM named \"add1\"."`

**Comment by lvirbalas** [comment]
I believe @vbauzysvmware meant `power_on = "true"` in step (3) above.

@mdacrema is your use case to auto-install an OS from the CD-ROM, meaning you need to boot it up automatically?

**Comment by mdacrema** [comment]
@lvirbalas is right. 
I don't need to auto-install an OS, I need to have the CD-ROM attached when the VM boot up. It need to read some files from the CD-ROM at boot time.

**Comment by vbauzysvmware** [comment]
@mdacrema Is my suggestion solves your issue? I tough how  automatically to solve this. And another approach would be is to have two script files. One which creates resouces and second one which uses same terraform VM resource, but with `power_on = "true"`. So just run one script after another.

**Comment by mdacrema** [comment]
@vbauzysvmware I tried to rerun the script changing power_on from false to true but nothing happen. VM is still off. Can you reproduce this?

**Comment by vbauzysvmware** [comment]
My script:
```
resource "vcd_vapp" "vappNetVAppTestResource" {
  name = "vappNetVAppTest"
  #power_on = false
  network_name = "my1_netw2"
}

resource "vcd_vapp_vm" "vmAmdNet1" {
  # vapp_name  = "TestAccVcdVAppForFwTest"
  #  vapp_name         = "vApp_system_1"
  vapp_name = "vappNetVAppTest"
  count = 1

  power_on = false
  #power_on = true

  name              = "add1"
  network_name = "my1_netw2"

  #network_name = "my1_netw2"

  #catalog_name      = "testCatalog"
  catalog_name = "TestSuiteCatalog"

#  template_name     = "photon-hw11"
  #  template_name     = "Photon-2.0-HW11_second4"
  template_name = "TestSuiteOVA"

  memory     = 1024
  cpus       = 2
  ip         = "192.168.100.8"
  depends_on = ["vcd_vapp.vappNetVAppTestResource"]
}

resource "vcd_catalog_media"  "TestAccVcdCatalogMediaBasicForInsert" {
  org = "my1"
  catalog = "testCatalog"

  name = "TestAccVcdCatalogMediaBasicForInsert"
  description = "TestAccVcdCatalogMediaBasicDescriptionForInsert"
  media_path = "/home/vbauzys/work/vcd/src/github.com/terraform-providers/terraform-provider-vcd/test-resources/test.iso"
  upload_piece_size = 5
  show_upload_progress = "true"
}


resource "vcd_inserted_media" "ISO" {
 count = "1"
 catalog = "testCatalog"
 name = "TestAccVcdCatalogMediaBasicForInsert"
 vapp_name = "vappNetVAppTest"
 vm_name = "add1"
 depends_on = ["vcd_vapp_vm.vmAmdNet1"]
}
```
And terraform runing:
```
terraform apply -auto-approve
vcd_catalog_media.TestAccVcdCatalogMediaBasicForInsert: Refreshing state... (ID: testCatalog:TestAccVcdCatalogMediaBasicForInsert)
vcd_vapp.vappNetVAppTestResource: Creating...
  accept_all_eulas: "" => "true"
  href:             "" => "<computed>"
  ip:               "" => "<computed>"
  name:             "" => "vappNetVAppTest"
  network_name:     "" => "my1_netw2"
  power_on:         "" => "true"
vcd_catalog_media.TestAccVcdCatalogMediaBasicForInsert: Creating...
  catalog:              "" => "testCatalog"
  description:          "" => "TestAccVcdCatalogMediaBasicDescriptionForInsert"
  media_path:           "" => "/home/vbauzys/work/vcd/src/github.com/terraform-providers/terraform-provider-vcd/test-resources/test.iso"
  name:                 "" => "TestAccVcdCatalogMediaBasicForInsert"
  org:                  "" => "my1"
  show_upload_progress: "" => "true"
  upload_piece_size:    "" => "5"
vcd_catalog_media.TestAccVcdCatalogMediaBasicForInsert: Upload progress 0.00%
vcd_catalog_media.TestAccVcdCatalogMediaBasicForInsert: Still creating... (10s elapsed)
vcd_vapp.vappNetVAppTestResource: Still creating... (10s elapsed)
vcd_vapp.vappNetVAppTestResource: Creation complete after 14s (ID: vappNetVAppTest)
vcd_vapp_vm.vmAmdNet1: Creating...
  accept_all_eulas: "" => "true"
  catalog_name:     "" => "TestSuiteCatalog"
  cpus:             "" => "2"
  href:             "" => "<computed>"
  ip:               "" => "192.168.100.8"
  memory:           "" => "1024"
  name:             "" => "add1"
  network_name:     "" => "my1_netw2"
  power_on:         "" => "false"
  template_name:    "" => "TestSuiteOVA"
  vapp_name:        "" => "vappNetVAppTest"
vcd_catalog_media.TestAccVcdCatalogMediaBasicForInsert: Upload progress 100.00%
vcd_catalog_media.TestAccVcdCatalogMediaBasicForInsert: vCD import catalog item progress 100%
vcd_catalog_media.TestAccVcdCatalogMediaBasicForInsert: Creation complete after 17s (ID: testCatalog:TestAccVcdCatalogMediaBasicForInsert)
vcd_vapp_vm.vmAmdNet1: Still creating... (10s elapsed)
vcd_vapp_vm.vmAmdNet1: Still creating... (20s elapsed)
vcd_vapp_vm.vmAmdNet1: Still creating... (30s elapsed)
vcd_vapp_vm.vmAmdNet1: Still creating... (40s elapsed)
vcd_vapp_vm.vmAmdNet1: Still creating... (50s elapsed)
vcd_vapp_vm.vmAmdNet1: Still creating... (1m0s elapsed)
vcd_vapp_vm.vmAmdNet1: Still creating... (1m10s elapsed)
vcd_vapp_vm.vmAmdNet1: Still creating... (1m20s elapsed)
vcd_vapp_vm.vmAmdNet1: Creation complete after 1m27s (ID: add1)
vcd_inserted_media.ISO: Creating...
  catalog:   "" => "testCatalog"
  name:      "" => "TestAccVcdCatalogMediaBasicForInsert"
  vapp_name: "" => "vappNetVAppTest"
  vm_name:   "" => "add1"
vcd_inserted_media.ISO: Still creating... (10s elapsed)
vcd_inserted_media.ISO: Creation complete after 13s (ID: vappNetVAppTest_add1_TestAccVcdCatalogMediaBasicForInsert)
```
Then change   power_on = true
```
terraform apply -auto-approve
vcd_vapp.vappNetVAppTestResource: Refreshing state... (ID: vappNetVAppTest)
vcd_catalog_media.TestAccVcdCatalogMediaBasicForInsert: Refreshing state... (ID: testCatalog:TestAccVcdCatalogMediaBasicForInsert)
vcd_vapp_vm.vmAmdNet1: Refreshing state... (ID: add1)
vcd_inserted_media.ISO: Refreshing state... (ID: vappNetVAppTest_add1_TestAccVcdCatalogMediaBasicForInsert)
vcd_vapp_vm.vmAmdNet1: Modifying... (ID: add1)
  power_on: "false" => "true"
vcd_vapp_vm.vmAmdNet1: Still modifying... (ID: add1, 10s elapsed)
vcd_vapp_vm.vmAmdNet1: Still modifying... (ID: add1, 20s elapsed)
vcd_vapp_vm.vmAmdNet1: Still modifying... (ID: add1, 30s elapsed)
vcd_vapp_vm.vmAmdNet1: Modifications complete after 40s (ID: add1)
```

**Comment by mdacrema** [comment]
@vbauzysvmware yes thank you for explaining how to do that, now it works

**Comment by vbauzysvmware** [comment]
Great!
