### ISSUE TITLE
Media Eject with Powered ON VM fail

### ISSUE THREAD

**Issue by mdacrema** [terraform-providers/terraform-provider-vcd#171]
Hi there,

I'm trying to eject and destroy an ISO media from a running VM but terraform fails with:

* module.etcd.module.etcd.vcd_inserted_media.ISO (destroy): 1 error(s) occurred:

* vcd_inserted_media.ISO: error: &errors.errorString{s:"to eject media, vm has to be in power off state"}

when I launch terraform destroy.
I think it's caused by the depends_on clause specified below:

### Terraform Version
Terraform v0.11.10
+ provider.consul v2.2.0
+ provider.external v1.0.0
+ provider.null v2.0.0
+ provider.random v2.0.0
+ provider.template v2.0.0
+ provider.vcd v2.0.0

### Affected Resource(s)
Please list the resources as a list, for example:
- vcd_inserted_media

### Terraform Configuration Files
```
resource "vcd_vapp" "vApp" {
 name = "vApp_${var.name}"
 network_name = "${var.network_name}"
 power_on = "false"
}

resource "vcd_vapp_vm" "instance" {
 vapp_name = "vApp_${var.name}"
 count = "${var.quantity}"
 name = "${var.name}-${count.index}"
 catalog_name  = "${var.catalog}"
 template_name = "${data.external.image_sync.result.template_name}"
 memory = "${var.memory}"
 cpus = "${var.cpus}"
 network_name = "${var.network_name}"
 depends_on = ["vcd_vapp.vApp"]
 power_on = "false"
}
resource "vcd_inserted_media" "ISO" {
 count = "${var.quantity}"
 catalog = "${var.catalog}"
 name = "${var.name}-${count.index}-user-data.iso"
 vapp_name = "vApp_${var.name}"
 vm_name = "${var.name}-${count.index}"
}
```

### Expected Behavior
Media ejected from VM

### Actual Behavior
Terraform error

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform destroy`

### Important Factoids
I need the depends_on clause on VM because I need to create multiple VMs. If I don't use depends_on Media attach will fail complaining about No VM found:

* module.etcd.module.etcd.vcd_inserted_media.ISO: 1 error(s) occurred:

* vcd_inserted_media.ISO: error: &errors.errorString{s:"unable to find VM. Removing from tfstate. Err: #found results 0"}

If I remove the depends_on clause when destroying I'am able to delete the VM but after that terraform still complain about missing VM.

**Comment by vbauzysvmware** [comment]
Hi @mdacrema - well eject media is quite restrictable.  As error says `to eject media, vm has to be in power off state` to eject VM has to be off. `depends_on` clause is terraform handler and not providers deed as we don't have means to do it.

Eject resource don't automatically power down VM, cause it would be to risky - users couldn't expect that and as such it is left to user to handle.

In your case destroy will work if you power off VM before destroy.

**Comment by mdacrema** [comment]
Hi @vbauzysvmware I got it but in my opinion this introduce some restrictions.
Let's make an Example: I deployed one vApp with three VMs. These VMs configure itself by reading an inserted ISO media at boot time.
Then I need to scale down (change terraform quantity) the infrastructure and to do that I need to completely remove a VM from the infra. To remove it I need to completely shutdown the VM but I'am unable ( as far as I understand ) because I first need to undeploy the vApp otherwise VM will go in a partially shutdown state. 
In that state I'm able to detach the media but not to delete the VM.
I think that the vcd_inserted_media resource need kind of "force" options to allow to detach the media on a running VM ( letting the VM configuration to decide if override possible OS guest lock or not ). In that case it will be much more easier manage this kind of dependency and the VM lifecycle.
Another workaround would be to deploy only one VM per vApp but it's not so good.

Thank you

**Comment by mdacrema** [comment]
@vbauzysvmware I tried removing count and quantity form main.tf. 
During destroy VM has been deleted correctly but after that terraform try to eject media from a VM that does not exists and fail for the first time with:
Error: Error applying plan:

1 error(s) occurred:

* module.etcd.module.etcd.vcd_inserted_media.ISO (destroy): 1 error(s) occurred:

* vcd_inserted_media.ISO: error: &errors.errorString{s:"to eject media, vm has to be in power off state"}

and the second time with:
Error: Error refreshing state: 1 error(s) occurred:

* module.etcd.module.etcd.vcd_inserted_media.ISO: 1 error(s) occurred:

* module.etcd.module.etcd.vcd_inserted_media.ISO: vcd_inserted_media.ISO: error: &errors.errorString{s:"unable to find VM. Removing from tfstate. Err: #found results 0"}

If I run again terraform for creating new resources it will fail with the same error above

**Comment by vbauzysvmware** [comment]
@mdacrema Regarding issue with destroy - if dependencies are not correct - then you destroy vm before ejecting media. As result insert/eject resource will fail.
Logs tells that when VM isn't found - `tf state` is removed and create should run fine. I recheck that in the code.

**Comment by vbauzysvmware** [comment]
@mdacrema Regarding issue with running VM to eject media - at the moment API don't allow any force capabilities. I will investigate what could be possible to be done.

**Comment by mdacrema** [comment]
@vbauzysvmware Yes logs tells that it will be removed from tfstate but I find it's not true. This occur when no dependecies are set in terrafrom. If I set "depends_on" -> instance then on destroy Terraform will try to eject media when the VM is still running and then fail. I fixed it using a local exec that issue a curl to the vCloud API and shut down the VM.

**Comment by lvirbalas** [comment]
@vbauzysvmware you wrote:

> Regarding issue with running VM to eject media - at the moment API don't allow any force capabilities. I will investigate what could be possible to be done.

Just to confirm, vCD API doesn't allow forcing of eject if VM is powered on?

> If I set "depends_on" -> instance then on destroy Terraform will try to eject media when the VM is still running and then fail. I fixed it using a local exec that issue a curl to the vCloud API and shut down the VM.

@mdacrema and @vbauzysvmware would a new option of `power_off_vm_before_eject` (default: false) help here?

**Comment by mdacrema** [comment]
@lvirbalas yes it will help. Now for make it works I'm doing what follow. It's like have "power_off_vm_before_eject" option.

```
resource "vcd_inserted_media" "ISO" {
 count = "${var.quantity}"
 catalog = "${var.catalog}"
 name = "${var.name}-${count.index}-user-data.iso"
 vapp_name = "vApp_${var.name}-${count.index}"
 vm_name = "${var.name}-${count.index}"
 provisioner "local-exec" {
  when = "destroy"
  environment {
    VCD_AUTH = "${var.vcd_username}@${var.vcd_org}:${var.vcd_password}"
    VCD_URL = "${var.vcd_url}"
    VAPP_NAME = "${var.name}-${count.index}"
  }
    interpreter = ["bash", "-c"]
    command = "${path.module}/undeploy_vapp.sh && sleep 30"
 }
 depends_on = ["vcd_vapp_vm.instance"] #if not set sometimes TF try to attach to VM that does not exist
}
```
and here the undeploy_vapp.sh script
```
#!/bin/bash
TOKEN=$(curl -I -s -i -k -H "Accept:application/*+xml;version=1.5" -u $VCD_AUTH -X POST $VCD_URL/sessions |grep  auth |awk {'print $2'} |sed -s 's/\r$//')
echo $TOKEN > undeploy_vcd_token.txt
VAPP_URL=$(curl -s -i -k -H "Accept:application/*+xml;version=1.5" -H "x-vcloud-authorization: $TOKEN" -X GET  "$VCD_URL/query?type=vApp" |grep name=\"vApp_$VAPP_NAME\"  |grep -o "href.*" | sed 's/\s.*$//' |sed -e 's/href="//' |sed -s 's/"//')
echo $VAPP_URL > undeploy_vapp_url.txt
UNDEPLOY=$(curl -s -i -k -H "Accept:application/*+xml;version=1.5" -H "x-vcloud-authorization: $TOKEN" -H "Content-Type:application/vnd.vmware.vcloud.undeployVAppParams+xml" -X POST $VAPP_URL"/action/undeploy" -d @undeploy_request)
echo $POWERON > undeploy_vapp.txt
sleep 30
jq -r -n --arg vm_name "${VAPP_NAME}" --arg output  "${ACTION}" '{"vm_name":$vm_name,"output":$output}'
```

**Comment by vbauzysvmware** [comment]
@lvirbalas - API don't have any force option and to be sure I asked vCD team to confirm that.

**Comment by vbauzysvmware** [comment]
So some good news. We figure out how to improve ejecting functionality. I have ready changes with additional API functionality and Terafform changes to answer question when ejecting with turned on VM.  So additional parameters `eject_force` introduced which will answer automatically to VM question to Yes and ejects media. 
New PR will come after go modules upgrade solved.
