### ISSUE TITLE
Add External Network operations

### ISSUE THREAD

**Issue by sam-calvert** [terraform-providers/terraform-provider-vcd#173]
Hello all, 

This is a new feature request and is related to the go-vcloud-director issue here:
https://github.com/vmware/go-vcloud-director/issues/129

Once the necessary functionality is implemented in go-vcloud-director, it would be really helpful for my use case to be able to create and/or modify External Networks through the terraform provider. 

### Expected Behaviour

This would be analogous to logging into the vCloud Director GUI home page and selecting "Create another external network" on the System tab and Home subtab. 

### Terraform Configuration 

Based on some preliminary research, the terraform configuration would look something like this: 
``` 
resource "vcd_external_network" "ext_net_test_parent" {
  description = "ExtNet-101"

  ip_scope {
    is_inherited = "false"
    gateway = "192.168.30.49"
    netmask = "255.255.255.240"
    dns1 = "192.168.0.164"
    dns2 = "192.168.0.196"
    ip_range {
      start = "192.168.30.51"
      end = "192.168.30.62"
    }
  }

  fence_mode = "isolated"
  retain_net_info_across_deployments = "false"
}

resource "vcd_external_network" "ext_net_test" {
  description = "ExtNet-101"

  ip_scope {
    is_inherited = "true"
    gateway = "192.168.30.49"
    netmask = "255.255.255.240"
    dns1 = "192.168.0.164"
    dns2 = "192.168.0.196"
    ip_range {
      start = "192.168.30.51"
      end = "192.168.30.62"
    }
  }

  fence_mode = "bridged"
  retain_net_info_across_deployments = "false"
  parent_network = "${ext_net_test_parent.id}"
}
```

**Comment by lvirbalas** [comment]
CC: @dataclouder @vbauzysvmware @Didainius
