### ISSUE TITLE
Feature request: Ability to specify number of cores

### ISSUE THREAD

**Issue by spengilley** [terraform-providers/terraform-provider-vcd#174]
I have a template VM which defaults to 2 cores.

If I specify "cpus = 2" this leaves me with a bad configuration of 2 cpus and 2 cores. This means VM won't boot and terraform provision fails.

Ideally I would like to be able to specify cores to avoid this situation.

**Comment by lvirbalas** [comment]
FYI: @vbauzysvmware

**Comment by lvirbalas** [comment]
Link for reference, which explains nicely how `cpus` actually represent the _total number of logical processors_ in the system (i.e. CPUs x cores):
https://communities.vmware.com/thread/576209

**Comment by vbauzysvmware** [comment]
Released :)

**Comment by spengilley** [comment]
Thank you!!
