### ISSUE TITLE
RFE: Allow configuring Edge Gateway Loadbalancer

### ISSUE THREAD

**Issue by pasikarkkainen** [terraform-providers/terraform-provider-vcd#182]
It would be nice to be able to utilize the vCloud Edge Gateway loadbalancing via Terraform. LB-as-a-Service, basicly. Also enables easier High Availability for services running in virtual datacenters.

Edge gateways provide load balancing for TCP, HTTP, and HTTPS traffic.

vCloud API documentation for Loadbalancer:
https://vdc-repo.vmware.com/vmwb-repository/dcr-public/f27d65ea-c25b-45ed-9193-c8cc77507622/9a1f04e3-359b-4a19-9c62-7c0fafdfeac8/doc/doc/types/LoadBalancerServiceType.html

vCloud documentation for Edge Gateway Loadbalancer:
https://docs.vmware.com/en/vCloud-Director/9.5/com.vmware.vcloud.admin.doc/GUID-EC5EE5F9-1A2C-4609-9347-4C3143727704.html

**Comment by lvirbalas** [comment]
Hi @pasikarkkainen 

Yes, we have this in future plans. However, right now what would really help if you could draft a suggestion of how the configuration in `.tf` of the load balancer resources could look like. This would make it easier for a developer to pick up the task.

CC: @vbauzysvmware @Didainius

**Comment by Didainius** [comment]
This was done some time ago.
