### ISSUE TITLE
branching strategy, branch with the newest features

### ISSUE THREAD

**Issue by floriankammermann** [terraform-providers/terraform-provider-vcd#185]
Hi there

I have problems to figure out what the meaning of the different branches is and what the releasing strategy is.

I was searching for this feature: https://github.com/terraform-providers/terraform-provider-vcd/issues/97
Then I realized its in the branch `vmware-stash-while-master-pr-open`.

There is the statement 
> Code for moment in dev branch: terraform-providers:vmware-stash-while-master-pr-open later will be merged to master.

When are changes merged to `master` from `terraform-providers:vmware-stash-while-master-pr-open`?  
And when is master released and the binary is available from the offcial terraform provider repository https://www.terraform.io/docs/providers/vcd/index.html?

**Comment by lvirbalas** [comment]
Hi Florian,

The "stash" branch is a temporary development branch, which we had to create while the "Christmas" PR was in review (it took a month to merge it). We are planning to merge this branch as soon as ongoing work is finalised - no additional features are planned for this stash branch. So, it will disappear pretty soon.
At that point we will prepare for releasing the binary from the master.

We are considering whether to use a similar development branch going forward or not. Using a dev branch means the tip of the master is kept stable. To contrast, if we work directly on master, it is simpler (less branches), but the tip of the master may become dirty and only the release tags in the master will be truly stable.

What's the community preference?

**Comment by lvirbalas** [comment]
We're about to merge vmware-stash-while-master-pr-open branch to master.

Given that it’s a common practice in Terraform we will try using master-only approach for PRs and see how it goes. Success criteria: keep it stable.
