### ISSUE TITLE
Error finding external network when using vcd_network_direct to create an org vDC network connected directly to external network

### ISSUE THREAD

**Issue by jarcher-e4** [terraform-providers/terraform-provider-vcd#190]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
c:\utilities\Terraform>terraform -v
Terraform v0.11.13
+ provider.vcd v2.0.0

### Affected Resource(s)
vcd_network_direct

### Terraform Configuration Files
# modules/private-cloud/veeam-vapp.tf

# Configure the VMware vCloud Director Provider
provider "vcd" {
    user                    = "${var.vcd_user}"
    password                = "${var.vcd_pass}"
    org                     = "${var.vcd_org}"
    vdc                     = "${var.vcd_vdc}"
    url                     = "${var.vcd_url}"
    max_retry_timeout       = "${var.vcd_max_retry_timeout}"
    allow_unverified_ssl    = "${var.vcd_allow_unverified_ssl}"
}

resource "vcd_network_direct" "veeam-transport" {
  org               = "${var.vcd_org}"
  vdc               = "${var.vcd_vdc}"
  name              = "veeam-transport"
  external_network  = "SWGR Private Cloud Veeam Transport Network"
}

# peregrine-infrastructure.tf

module "veeam-vapp" {
    source = "/modules/private-cloud/"

    vcd_user        = "e4automation"
    vcd_org         = "Peregrine-Data-Services"
    vcd_vdc         = "Peregrine-Data-Services-vDC"
    vcd_network     = "PDS_LAN"
    vcd_network_ip  = "10.50.254.100"
    org_abr         = "pds"
}

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
direct network is created and attached to existing external network "SWGR Private Cloud Veeam Transport Network"

### Actual Behavior
When running apply, I'm getting "vcd_network_direct.veeam-transport: unable to find external network SWGR Private Cloud Veeam Transport Network (external network link isn't found)".

### Steps to Reproduce
1. `terraform apply`

### Important Factoids
We're using a vCloud Organization Administrator account as "vcd_user" and "vcd_pass".
There is, for sure, an external network in VCD named "SWGR Private Cloud Veeam Transport Network".
![image](https://user-images.githubusercontent.com/38989617/54462632-d2b6f800-4746-11e9-9533-0664b2324dbd.png)

### References

**Comment by Didainius** [comment]
Thank you for your query, @jarcher-e4.

It seems however that you made your screenshot while logged in as `System administrator` user via web UI. It is not possible to do so in vCloud director at this point in time if you're logged in as `Organization administrator` (via web gui as well).

Excerpt from docs: https://docs.vmware.com/en/vCloud-Director/9.0/com.vmware.vcloud.admin.doc/GUID-E8A80C28-6C16-4E83-828C-0510DA3B00F8.html

> A system administrator can create an organization virtual datacenter network that connects directly to an external network. VMs on the organization can use the external network to connect to other networks, including the Internet.
Prerequisites
    * This operation is restricted to system administrators.
    * An external network is required. See Add an External Network

I'm afraid the only thing we can do at the moment is update documentation for `vcd_network_direct` resource.

**Comment by jarcher-e4** [comment]
Ah so if I switched to using a system administrator account instead of the org admin credential that would correct this issue - that makes sense. A documentation update would clarify this, for sure.

I also think another thing that could be done is improve the error message displayed, since it gave:

"vcd_network_direct.veeam-transport: unable to find external network SWGR Private Cloud Veeam Transport Network (external network link isn't found)"

This message didn't make it obvious to me that this was a permission or account-type issue.

Thanks!

**Comment by Didainius** [comment]
Yep, I've considered that and added to my own future wishlist, however we're working quite a few pending things now so this won't get immediate priority.

**Comment by jarcher-e4** [comment]
Makes sense - thank you for the quick response and updating documentation!
