### ISSUE TITLE
Terraform crash - invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by jarcher-e4** [terraform-providers/terraform-provider-vcd#192]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
c:\utilities\Terraform>terraform -v
Terraform v0.11.13
+ provider.vcd v2.0.0

### Affected Resource(s)
Unsure - the error occurred when referencing a module during terraform plan. This module was previously working until I updated the module to authenticate with a system user and changed the provider org assignment from "${var.vcd_org}" to "System" in the provider resource.

### Terraform Configuration Files
I've sanitized these, and also included the crash.log in the zip
https://send.firefox.com/download/e337a7c13d/#Ve_LsyURJLcDxrBEf3zHmw

### Debug Output
https://gist.github.com/jarcher-e4/f9305444251f324c5045afa8d2720140

### Panic Output
https://gist.github.com/jarcher-e4/f9305444251f324c5045afa8d2720140

### Expected Behavior
terraform plan should have printed the expected changes based on the configuration files.

### Actual Behavior
terraform encountered a panic and crashed, which appears to have occurred while loading a module.

### Steps to Reproduce
terraform plan

### Important Factoids
N/A

### References

**Comment by jarcher-e4** [comment]
As an update, I did want to mention another issue which may have some association:
https://github.com/terraform-providers/terraform-provider-vcd/issues/190

I don't think this is directly related but I wanted to mention it since the change I made to use system org authentication is where I encountered the panic crash, and that change stemmed from the answer to issue 190.

**Comment by lvirbalas** [comment]
Note on issue posting: it's better to include the .tf configuration directly in the issue text, so the reviewers can easily see the configuration (as opposed to downloading). You may get feedback from more people like that too, as it would be searchable and easier to read.

**Comment by jarcher-e4** [comment]
Makes sense - I'll make it easier in that case:

#terraform module "veeam-vapp":
#veeam-vapp.tf
# modules/private-cloud/veeam-vapp.tf

# Configure the VMware vCloud Director Provider
provider "vcd" {
    user                    = "${var.vcd_user}"
    password                = "${var.vcd_pass}"
    org                     = "System"
    vdc                     = "${var.vcd_vdc}"
    url                     = "${var.vcd_url}"
    max_retry_timeout       = "${var.vcd_max_retry_timeout}"
    allow_unverified_ssl    = "${var.vcd_allow_unverified_ssl}"
}

resource "vcd_network_direct" "veeam-transport" {
  org               = "${var.vcd_org}"
  vdc               = "${var.vcd_vdc}"
  name              = "veeam-transport"
  external_network  = "SWGR Private Cloud Veeam Transport Network"
}

# Create a new Veeam vApp
resource "vcd_vapp" "veeam" {
    org     = "${var.vcd_org}"
    vdc     = "${var.vcd_vdc}"
    name    = "veeam"
}

# Create a new Veeam Server VM
resource "vcd_vapp_vm" "vbr" {
    vapp_name       = "${vcd_vapp.veeam.name}"
    name            = "${var.org_abr}-vbr"
    catalog_name    = "Element 4 Public Catalog"
    template_name   = "Veeam Server 2019"
    memory          = 4096
    cpus            = 2

    network_name    = "${var.vcd_network}"
    ip              = "${var.vcd_network_ip}"

    depends_on      = ["vcd_vapp.veeam"]

    # Bootstrap scripts
    initscript      = <<EOF
    @echo off
    if "%1%" = "precustomization" (
    ) else if "%1%" = "postcustomization" (
        @Set KMS server and activate
        START "C:\Windows\System32\cscript.exe" "C:\Windows\System32\slmgr.vbs" /skms kmshostname
        START "C:\Windows\System32\cscript.exe" "C:\Windows\System32\slmgr.vbs" /ato
        @Install Automate Agent
        msiexec.exe /i C:\bootstrap\automate\Agent_Install.msi /quiet /norestart
        @Install SQL Server
        START "C:\bootstrap\sql\setup.exe" /ConfigurationFile="C:\bootstrap\sql\install.ini"
        @Install Veeam
        msiexec.exe /qn /i "C:\bootstrap\veeam\Catalog\VeeamBackupCatalog64.msi" ACCEPT_THIRDPARTY_LICENSES="1"
        msiexec.exe /L*v "C:\logs\vbr-install.log" /qn /i "C:\bootstrap\veeam\Backup\Server.x64.msi" ACCEPTEULA="YES" ACCEPT_THIRDPARTY_LICENSES="1"
        msiexec.exe /L*v "C:\logs\vex-ad-install.log" /qn /i "C:\bootstrap\veeam\Explorers\VeeamExplorerForActiveDirectory.msi" ACCEPTEULA="YES" ACCEPT_THIRDPARTY_LICENSES="1"
        msiexec.exe /L*v "C:\logs\vex-ex-install.log" /qn /i "C:\bootstrap\veeam\Explorers\VeeamExplorerForExchange.msi" ACCEPTEULA="YES" ACCEPT_THIRDPARTY_LICENSES="1"
        msiexec.exe /L*v "C:\logs\vex-or-install.log" /qn /i "C:\bootstrap\veeam\Explorers\VeeamExplorerForOracle.msi" ACCEPTEULA="YES" ACCEPT_THIRDPARTY_LICENSES="1"
        msiexec.exe /L*v "C:\logs\vex-sp-install.log" /qn /i "C:\bootstrap\veeam\Explorers\VeeamExplorerForSharePoint.msi" ACCEPTEULA="YES" ACCEPT_THIRDPARTY_LICENSES="1"
        msiexec.exe /L*v "C:\logs\vex-sql-install.log" /qn /i "C:\bootstrap\veeam\Explorers\VeeamExplorerForSQL.msi" ACCEPTEULA="YES" ACCEPT_THIRDPARTY_LICENSES="1"
        msiexec.exe /L*v "C:\logs\vbr-console-install.log" /qn /i "C:\bootstrap\veeam\Backup\Shell.x64.msi" ACCEPTEULA="YES" ACCEPT_THIRDPARTY_LICENSES="1"
        @Add static routes for SWGR and SWLV hypervisor networks
        route -p add CIDR GW
        route -p add CIDR GW
        route -p add CIDR GW
        @Backup hosts file and add SWGR and SWLV hypervisor hostfile entries
        cp C:\Windows\System32\drivers\etc\hosts C:\bootstrap\hosts.original
        echo.127.0.0.1○${var.org_abr}-vbr○localhost
        echo %DATE% %TIME% - VM Customization Complete > C:\vm-customization.log
    )
    EOF
}



#Configuration file which calls the module:
# peregrine-infrastructure.tf

module "veeam-vapp" {
    source = "/modules/private-cloud/"
    vcd_org         = "Peregrine-Data-Services"
    vcd_vdc         = "Peregrine-Data-Services-vDC"
    vcd_network     = "PDS_LAN"
    vcd_network_ip  = "10.50.254.100"
    org_abr         = "pds"
}

**Comment by jarcher-e4** [comment]
Also, the referenced variables' defaults are in "veeam-vapp.tf" (again, I've sanitized some content here):

variable vcd_user {
  default = "<vcd user username>"
}
variable vcd_pass {
  default = "<vcd user password>"
}
variable vcd_org {
  default = "Element-4"
}

variable org_abr {
  default = "E4"
}

variable vcd_url {
  default = "https://<vcd URL>/api"
}
variable vcd_vdc {
  default = "e4-lab-vdc"
}
variable vcd_max_retry_timeout {
  default = "60"
}
variable vcd_network {
  default = "e4-lab-lan"
}
variable vcd_network_ip {
  default = "<ip address>"
}

variable vcd_allow_unverified_ssl {
  default = "FALSE"
}

**Comment by jarcher-e4** [comment]
Okay I think I figured this out.

I switched to using a system admin account to be able to create a direct to external network on a vDC.

I then added an org and vdc specification on the vApp resource to ensure that vApp was being added to the intended organization and vdc.

I thought I had checked the VM resource and didn't see an org or vdc parameter on that resource, so I had assumed that the dependency mention of the vApp resource would tell Terraform that the VM should be added to the specific org and vdc mentioned in the vApp resource.

That said, I looked back at the documentation for https://www.terraform.io/docs/providers/vcd/r/vapp_vm.html again and I'm seeing "org" and "vdc" optional parameters in the documentation. I cleared my state file, cleaned up the orphaned items in vCloud Director, and re-ran after updating the VM resource to specify the org and vdc, and everything was created as expected.

I'm going to go ahead and close this out - I just messed something already clear enough in the documentation.

Thanks!

**Comment by lvirbalas** [comment]
It's great you were able to narrow down on this. Thanks for explanation! It is an interesting angle of user expectations. If most of your resources are in a single org, you can set a default at the provider level like this too to avoid setting in each resource (note the `sysorg` and `org` parameters):

```
# Configure the VMware vCloud Director Provider
provider "vcd" {
  user                 = "administrator"
  password             = "password"
  sysorg               = "System"
  org                  = "MyOrg"                                               # Default for resources
  vdc                  = "MyOrgVDC"                                            # Default for resources
  url                  = "https://myvcd/api"
  max_retry_timeout    = "300"
  allow_unverified_ssl = "true"
}
```

Then you'll only need to use `org` and `vdc` for the resources that need the non-default org.
