### ISSUE TITLE
Crash creating resource_vcd_network_routed with DHCP

### ISSUE THREAD

**Issue by jordips** [terraform-providers/terraform-provider-vcd#210]
Hi everyone,

I'm trying to create a "VCD Network routed" with DHCP option but it throws a Crash. 

### Terraform Version
Terraform v0.11.13

### Affected Resource(s)
- resource_vcd_network_routed

### Terraform Configuration Files
```hcl

resource "vcd_network_routed" "net" {
  org = "cust001"
  vdc = "cust001-vdc01"

  name         = "terraform_routed_example"
  edge_gateway = "edge1001"
  gateway      = "192.168.50.1"

  dhcp_pool {
    start_address = "192.168.50.100"
    end_address   = "192.168.50.200"
  }
}
```

### Panic Output
```hcl
 panic: runtime error: invalid memory address or nil pointer dereference
 [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xc9f4d9]

 goroutine 25 [running]:
 github.com/vmware/go-vcloud-director/v2/govcd.(*EdgeGateway).AddDhcpPool(0xc00014f1b0, 0xc0003f2000, 0xc0001429c0, 0x1, 0x1, 0x100c000053d98, 0x0, 0x1, 0x3)
      /home/jordi/go/pkg/mod/github.com/vmware/go-vcloud-director/v2@v2.1.0/govcd/edgegateway.go:48 +0x1b9
 github.com/terraform-providers/terraform-provider-vcd/v2/vcd.resourceVcdNetworkRoutedCreate.func2(0xc0003826e8)
      /mnt/c/terraform/terraform-provider-vcd/vcd/resource_vcd_network_routed.go:229 +0x2af
```
### Expected Behavior
A new network routed created in the Organitzation with DHCP feature in the specified edge

### Actual Behavior
Network is created but DHCP is not configured in the specified edge (it crashes adding DHCP).

### Steps to Reproduce
Just apply the terraform configuration specified. 

### Observations

I made some test in the code. At first it creates the network with this configuration:

```hcl
orgVDCNetwork := &types.OrgVDCNetwork{
                Xmlns: "http://www.vmware.com/vcloud/v1.5",
                Name:  d.Get("name").(string),

                EdgeGateway: &types.Reference{
                        HREF: edgeGateway.EdgeGateway.HREF,
                },
                Configuration: &types.NetworkConfiguration{
                        FenceMode: "natRouted",
                        IPScopes: &types.IPScopes{
                                IPScope: types.IPScope{
                                        IsInherited: false,
                                        Gateway:     gatewayName,
                                        Netmask:     d.Get("netmask").(string),
                                        DNS1:        d.Get("dns1").(string),
                                        DNS2:        d.Get("dns2").(string),
                                        DNSSuffix:   d.Get("dns_suffix").(string),
                                        IPRanges:    &ipRanges,
                                },
                        },
                        BackwardCompatibilityMode: true,
                },
                IsShared: d.Get("shared").(bool),
        }
```
I printed "edgeGateway.EdgeGateway.HREF" and it returns something like "https://@ipvcdserver/api/admin/edgeGateway/15141255c7-6d48-4daf-b1ed-bf77219abded" so when the create method is called it sends correctly the EdgeGateway information.

When the network is created, then is called  "vdc.FindVDCNetwork" to return again all the information of the created network object. I print the object and the EdgeGateway information is null.

```
&{XMLName:{Space:http://www.vmware.com/vcloud/v1.5 Local:OrgVdcNetwork} Xmlns:http://www.vmware.com/vcloud/v1.5
HREF:https://@ipne/api/network/d8cc5f62-61fe-4e48-8fa6-fdec1ea764b1
Type:application/vnd.vmware.vcloud.orgVdcNetwork+xml 
ID:urn:vcloud:network:d8cc5f62-61fe-4e48-8fa6-fdec1ea764b1 
OperationKey: 
Name:terraform_routed_example 
Status:1 Configuration:0xc000579600 
Description: 
EdgeGateway:<nil> I
sShared:false 
Link:[{HREF:https://92.54.20.5/api/vdc/9f2f7c8f-22e0-45c7-9774-b16f599c946a ID: Type:application/vnd.vmware.vcloud.vdc+xml Name: Rel:up} {HREF:https://92.54.20.5/api/network/d8cc5f62-61fe-4e48-8fa6-fdec1ea764b1/metadata ID: Type:application/vnd.vmware.vcloud.metadata+xml Name: Rel:down} {HREF:https://92.54.20.5/api/network/d8cc5f62-61fe-4e48-8fa6-fdec1ea764b1/allocatedAddresses/ ID: Type:application/vnd.vmware.vcloud.allocatedNetworkAddress+xml Name: Rel:down}] 
ServiceConfig:<nil> Tasks:<nil>}
```

I think that the problem is  when the network is created, is not linked propertly with the Edge and then when the method "AddDhcp" wants to get access to the Edge through the OrgNetwork object (returned by the FindVDCNetwork) it has a null pointer.

**Comment by lvirbalas** [comment]
Which vCD version?
Which provider version or where it is built from?

Could you try adding static_ip_pool section, that's the obvious diff from mine which works fine:
```
  static_ip_pool {
    start_address = "192.168.0.2"
    end_address   = "192.168.0.100"
  }
```

**Comment by jordips** [comment]
Hi Ivirbalas,

Sorry:
vCloud Director: v9.5
provider version: 2.1

I try adding static_ip_pool part but it gives the same error. Which vCD version do you have?

Thanks a lot!

**Comment by lvirbalas** [comment]
vCD 9.5 and provider built from master's HEAD.

More thoughts:
- Check that your Edge Gateway is advanced one
- Out of curiosity, try running the script with sys admin user (or org admin user, if you're sys admin right now)

**Comment by jordips** [comment]
The edge is an advanced one (with HA enabled). It's checked "distributed routing" function (for DLR) as well. Do you have this function enabled in your edge?

I'm running the script with "org admin user" and "sys admin user". It throws the same exactly error. 

I appreciate your help.

**Comment by lvirbalas** [comment]
> The edge is an advanced one (with HA enabled). It's checked "distributed routing" function (for DLR) as well. Do you have this function enabled in your edge?
Mine is without HA and without distributed routing, but advanced.

@dataclouder please take a look at this once you're back.

FYI: @Didainius @vbauzysvmware

**Comment by jordips** [comment]
Let me try without HA and without distributed routing. Maybe is some of this features that are breaking the code.

**Comment by lvirbalas** [comment]
Thanks! It would be really useful to understand it.

**Comment by jordips** [comment]
Ivirbalas it works if Edge is created without HA and without distributed routing.

Now I will try the next steps:
- Edge with HA and without distributed routing
- Edge without HA and with distributed routing

Then I will confirm which of the two features  are breaking the code.

Thanks a lot!

**Comment by lvirbalas** [comment]
These are really great findings @jordips ! Looking forward to hearing which of the one is breaking, then let's rename the issue accordingly and put the details to summary.

Do you have ability to fix it and propose a PR, or should we look for someone?

**Comment by jordips** [comment]
@lvirbalas Thank you very much! Sorry for answering so late. All of you are making a lot of work in this kind of projects and you share them without any profit. That is the very least I can contribute :)

It's weird, but making some diferent tests I realised that creating another edge in the same organitzation and then apply the terraform config it works well :S .  I created the edge 3 times:

- Edge with HA and without distributed routing
- Edge without HA and with distributed routing
- Edge with HA and with distributed routing

I applied the terraform config on all of them and it works well. **So, I can confirm there is no problem with the provider ** and it seems that there is something wrong with the two edges that I tested before I opened the issue (bad luck :( ).  The two edges that I tested where created some time ago and both have networks and vm.

I will try to find which is the problem with them, just for knowledge. Last question:

- Are you using vCloud Director 9.5 appliance (OVA) or Centos/Redhat and vCD installation?

Thanks for all!

**Comment by lvirbalas** [comment]
Hi Jordi,

Our goal is to make vCD integrated with Terraform as fully as possible. We are trying to balance in-house development with community contributions and to progress on both, though it's not always trivial.

To answer your question, we have vCD deployed both ways. @Didainius I believe you actually have even both on the same machine?

**Comment by Didainius** [comment]
>     * Are you using vCloud Director 9.5 appliance (OVA) or Centos/Redhat and vCD installation?

I've got both - OVA and on CentOS with slightly different 9.x minor versions.

**Comment by jordips** [comment]
Ok, so I can't reproduce and edge with the same error. Maybe the two fake edges where created bad or something else...

I close the issue. thank you very much for your help.

OFF-topic: I've installed vCloud Director 9.7 and I tested the same resource and all is working well.

**Comment by lvirbalas** [comment]
> OFF-topic: I've installed vCloud Director 9.7 and I tested the same resource and all is working well.

Thanks @jordips ! Keep us posted if you hit anything else.
