### ISSUE TITLE
Introduce hypervisor nesting option for VMs

### ISSUE THREAD

**Issue by Didainius** [terraform-providers/terraform-provider-vcd#219]
This community requested feature will allow to setup nested hypervisors in vCD (which is very useful for various LAB scenarios).

This issue is set to track work on both repos. It was originally driven in PR #71, but is abandoned and does not cover `go-vcloud-director` related work.

In a nutshell it allows to run ESXi (and other hypervisors) on ESXi. More details can be found in [documentation](https://docs.vmware.com/en/VMware-vSphere/6.7/com.vmware.vsphere.vm_admin.doc/GUID-2A98801C-68E8-47AF-99ED-00C63E4857F6.html).

GUI-wise the below checkbox will get enabled:
<img width="369" alt="image" src="https://user-images.githubusercontent.com/15804230/56208155-190aba00-6059-11e9-9f6f-ff5a69bbfb20.png">

**Comment by Didainius** [comment]
@pasikarkkainen, FYI.
You could test this out by building from PR https://github.com/terraform-providers/terraform-provider-vcd/pull/220
Let me know if you see any issues/expected something else.

**Comment by Didainius** [comment]
@pasikarkkainen, if you're still interested - this is in master now.

**Comment by pasikarkkainen** [comment]
@Didainius Great, thanks a lot! I'm currently travelling, but i'll give master branch a go next week, and file new issues if something comes up.
