### ISSUE TITLE
Allow specifying protocol for SNAT/DNAT rules

### ISSUE THREAD

**Issue by pasikarkkainen** [terraform-providers/terraform-provider-vcd#22]
Currently Terraform vcloud director provider allows specifying "protocol" (tcp/udp/icmp/any) for firewall rules, but not for snat/dnat rules. Instead currently snat/dnat rules always assume protocol to be "tcp".

To be able to create port forwarding rules for, say, DNS, NTP, or OpenVPN connections one needs to be able to configure protocol to be tcp/udp/icmp/any, just like one can for firewall rules.

For backwards compatibility we should default to "tcp" if protocol hasn't been specified.

**Comment by bobbydeveaux** [comment]
This is currently hardcoded in the govcloudair library:

```
natRule := &types.NatRule{
		RuleType:  nattype,
		IsEnabled: true,
		GatewayNatRule: &types.GatewayNatRule{
			Interface: &types.Reference{
				HREF: uplink.HREF,
			},
			OriginalIP:     externalIP,
			OriginalPort:   externalPort,
			TranslatedIP:   internalIP,
			TranslatedPort: internalPort,
			Protocol:       "tcp",
		},
	}
```

We'll just need to parameterise this.

**Comment by urajio** [comment]
please fix this

**Comment by pasikarkkainen** [comment]
Let us know when it's possible to specify protocol for snat/dnat rules. I'm happy to test the functionality!

**Comment by vbauzysvmware** [comment]
Hi Everyone, 

Changes are pushed and you are welcome to try.

P.s. Note that missing in documentation that "-1" for port means "any".

**Comment by pasikarkkainen** [comment]
@vbauzysvmware : Great, I'll give it a go soon and let you know what happens :)

One small typo I noticed with a quick glance in go-vcloud-director changes: "provided protocol is not one of TCP, UDP, TCP_UDP, ICPM, ANY". That should obviously say "ICMP", not "ICPM".

**Comment by vbauzysvmware** [comment]
Thank you, @pasikarkkainen. Mistype noted.
Also resource supports now ICMP sub types. Current implementations supports everything you can do it in VCD UI.

**Comment by pasikarkkainen** [comment]
@vbauzysvmware : Seems to work fine for me! I was able to do for example:

resource "vcd_dnat" "dnat-test1" {
    edge_gateway  = "${var.edge_gateway}"
    external_ip   = "${var.edge_ext_ip}"
    port = 1234
    translated_port = 10234
    protocol = "udp"
    internal_ip   = "${var.testvm_int_ip}"
}

Thanks a lot!

**Comment by vbauzysvmware** [comment]
Great, I am closing issue. If you spot something please open it ant let with details what issue are ;)

**Comment by urajio** [comment]
Great! Thank you!
When does it go into the master branch?

**Comment by vbauzysvmware** [comment]
We stream to do this Asap. And yet to happen this we have to provide infrastructure to verify changes. We are working on this to happen.

**Comment by lvirbalas** [comment]
@urajio We just opened up the master PR #143 
Happy upcoming Holidays!
