### ISSUE TITLE
RFE: Allow deployment of OrgVDC's

### ISSUE THREAD

**Issue by mgaruccio** [terraform-providers/terraform-provider-vcd#222]
It would be helpful to be able to create a new Organization Virtual Datacenter's.  Now that the 2.0 release is done and admin operations are supported this seems like a logical next step after configuration of the org itself.

**Comment by lvirbalas** [comment]
Thank you for this request! We are actually actively working on a PR for creating Org VDCs with a contributor and would also like to have it as soon as possible: #149

**Comment by lvirbalas** [comment]
p.s. You're of course most welcome to review the above work-in-progress code or at least the resource definition and provide feedback!

**Comment by mgaruccio** [comment]
Awesome, thanks for the update!  checked issues but didn't think to look at PR's before posting.  Also took a look at the resource definition and it looks perfect for my use-case.  looking forward to the release!

**Comment by vbauzysvmware** [comment]
Update and read added, so now Org vDC fully capable.
