### ISSUE TITLE
Add ability to configure DNAT or SNAT rules for external network

### ISSUE THREAD

**Issue by vbauzysvmware** [terraform-providers/terraform-provider-vcd#225]
Current behaviour allows in edge gateway to apply on DNAT and SNAT rules for organization networks. In vCD UI it allows to apply on external network too.

New feature would allow to provide external network name in existing DNAT, SNAT resources or would have separate resource.

Ref: https://github.com/terraform-providers/terraform-provider-vcd/pull/224

**Comment by lvirbalas** [comment]
We decided to add `network_type` to support this. Now it will only support `org`, but we'll add `ext` (external) to it afterwards.

```
resource "vcd_snat" "outbound" {
  edge_gateway = "Edge Gateway Name"
 
  network_type = "org"
  network_name = "Org vDC network name"
 
  external_ip  = "78.101.10.20"
  internal_ip  = "10.10.0.0/24"
}
 
resource "vcd_snat" "outbound" {
  edge_gateway = "Edge Gateway Name"
 
  network_type = "ext"
  network_name = "External network name"
 
  external_ip = "10.150.211.102/32"
  internal_ip = "192.168.0.0/24"
}
```

**Comment by carmineesposito73** [comment]
Working on vcloud 8.20 with not advanced edge I got this error
```
Error: unable to find external network: EXT-NET-NAME, err: functionality requires system administrator privileges
```

**Comment by pasikarkkainen** [comment]
hmm, configuring EdgeGw SNAT/DNAT rule for the External Network does not require sysadmin privileges, as long as the Edge External IPs are sub-allocated properly.

**Comment by lvirbalas** [comment]
This issue is logged here:
https://github.com/terraform-providers/terraform-provider-vcd/issues/294

**Comment by carmineesposito73** [comment]
It works omitting `network_type` and `network_name`, nat rules using external ip are automatically applied on external network (note: description is ignored).
```
resource "vcd_snat" "out1" {
  description  = "default-out"
  edge_gateway = "${var.vcd_edge_1}"
#  network_name = "${var.vcd_ext_net_1}"
#  network_type = "ext"
  external_ip  = "${var.ext_ip[0]}"
  internal_ip  = "192.168.0.0/24"
}

resource "vcd_dnat" "in1" {
  description  = "http-in-vm11"
  edge_gateway = "${var.vcd_edge_1}"
#  network_name = "${var.vcd_ext_net_1}"
#  network_type = "ext"
  port = 80
  external_ip  = "${var.ext_ip[1]}"
  internal_ip  = "172.16.1.11"
}
```
I got this warning
```
WARNING: this resource will require network_name and network_type in the next major version
```
I hope it continues working when both parameter will become mandatory

**Comment by lvirbalas** [comment]
> I hope it continues working when both parameter will become mandatory
For the time being there's no major version (i.e. 3.0.0) planned, so it will work (next version is 2.5.0). CC: @vbauzysvmware 

BTW, there was an issue with using `vcd_dnat` and `vcd_snat` resources, which use the pure vCD API, on **advanced** (NSX-V) EG together with the new HTML5 UI, so we have added two new resources, which talk to NSX-V advanced EG proxied API directly. They are in master scheduled for 2.5.0:
- New Resource: vcd_nsxv_dnat DNAT for advanced edge gateways using proxied NSX-V API - [#328]
- New Resource: vcd_nsxv_snat SNAT for advanced edge gateways using proxied NSX-V API - [#328]

**Comment by nicslatts** [comment]
Hi @carmineesposito73 just an FYI, vCloud Director 8.20 went End-of-General-Support in February 2019. In light of this, the Terraform vCD Provider will not be tested against vCD 8.20 from v2.5.0. The provider may still work with vCD 8.20, but it will be not be tested by VMware engineering so we can't guarantee interoperability. Do you have a plan to upgrade to vCD 9.x or vCD 10?

**Comment by carmineesposito73** [comment]
Thanks @nicslatts 
Yes, upgrade to vCD 9.x is planned
