### ISSUE TITLE
vcd_catalog_media does not include auth

### ISSUE THREAD

**Issue by lroellin** [terraform-providers/terraform-provider-vcd#227]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.

Terraform v0.11.13

### Affected Resource(s)
Please list the resources as a list, for example:

- vcd_catalog_media

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl

provider "vcd" {
  user                 = "${var.vcd_user}"
  password             = "${var.vcd_password}"
  org                  = "${var.vcd_org}"
  vdc                  = "${var.vcd_vdc}"
  url                  = "${var.vcd_url}"
  max_retry_timeout    = "${var.vcd_max_retry_timeout}"
  allow_unverified_ssl = "${var.vcd_allow_unverified_ssl}"
}

resource "vcd_catalog" "customer_catalog" {
  name             = "${var.customer_name}_catalog"
  description      = "catalog for customer"
  delete_recursive = "true"
  delete_force     = "true"
}



resource "vcd_catalog_media" "day0_iso" {
  name                 = "${var.customer_name}_day0.iso"
  catalog              = "${vcd_catalog.customer_catalog.name}"
  description          = "Config ISO for customer"
  media_path           = "../../day0.iso"
  show_upload_progress = true

  depends_on = ["vcd_catalog.customer_catalog"]
}
```

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

* It requires some time to set this up. If needed, I can produce it.

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

**Did not produce a panic!**

### Expected Behavior
What should have happened?

* The media should be (1) uploaded and (2) imported
* For this, the request (the one to `/transfer`) includes `X-Vcloud-Authorization` 

### Actual Behavior
What actually happened?

* The media is (1) uploaded but (2) not imported
* For this, the request (the one to `/transfer`) does not `X-Vcloud-Authorization` (but every other request does)

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`
2. Observe:

A repeating log pattern
```
module.xyz.vcd_catalog_media.day0_iso: Creating...
  catalog:              "" => "customer2_catalog"
  description:          "" => "Config ISO for customer"
  media_path:           "" => "../../day0.iso"
  name:                 "" => "customer2_day0.iso"
  show_upload_progress: "" => "true"
  upload_piece_size:    "" => "1"
vcd_catalog_media.customer2_day0.iso: Upload progress 0.00%
module.xyz.vcd_catalog_media.day0_iso: Still creating... (10s elapsed)
vcd_catalog_media.customer2_day0.iso: Upload progress 100.00%
vcd_catalog_media.customer2_day0.iso: vCD import catalog item progress 1%
module.xyz.vcd_catalog_media.day0_iso: Still creating... (20s elapsed)
vcd_catalog_media.customer2_day0.iso: vCD import catalog item progress 1%
module.xyz.vcd_catalog_media.day0_iso: Still creating... (30s elapsed)
vcd_catalog_media.customer2_day0.iso: vCD import catalog item progress 1%
```

The lines 'Still creating...' and 'Import catalog item progress 1%' repeat. The import progress never progresses.

Also, observe that the item also shows the importing status in the UI (Flash or HTML5)

### Important Factoids
Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? Custom version of OpenStack? Tight ACLs?

Running behind an F5 which requires the header.

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- GH-1234

N/A

**Comment by lvirbalas** [comment]
@vbauzysvmware please take a look at this issue.

**Comment by vbauzysvmware** [comment]
Hi @lroellin 
As far as I understood from report, that upload happens, but import takes long time. From our perspective import is done by vCD and not terraform/provider issue as file was accepted by vCD. 
Our experienced showed that import can take a long time and depends on Env performance and file size. Under hood file is upload to temporary space and later vCD verifies and copies to where is needed. So import takes time due Env and file size. In slow env and 2GB file it can take 10-20 minutes.

Another option that media file is bad - in that way in UI and terraform task you should see that import task failed after some time.

To analyse more we would need you enable https://www.terraform.io/docs/providers/vcd/ logging part and provide logs files. And provide iso file.

**Comment by lroellin** [comment]
I don't think the problem is the ISO file. Via the GUI, it imports in ~30 seconds fine. The ISO file is ~400KB.

> As far as I understood from report, that upload happens, but import takes long time. 

That is a symptom yes. The actual problem is, that the request is not authenticated. We recorded the session with Fiddler and saw the following happen:

Any other request (not the call to /transfer)

![goodrequest](https://user-images.githubusercontent.com/3150983/56794547-a8109280-680e-11e9-8f34-f5e9ec1ccbf7.png)

The call to /transfer:

![badrequest](https://user-images.githubusercontent.com/3150983/56794618-cb3b4200-680e-11e9-9e76-be36ddbde5c8.png)

If logging is needed, how can I provide it in a secure way, and would you need DEBUG or TRACE?

Note that the example above is simplified to the relevant points. I'm also creating a vApp and a VM inside, but these steps happen after the upload.

**Comment by vbauzysvmware** [comment]
I checked the code and yes, in this request we don't send authorization header. Normally vCD doesn't require it for this particular request. In your case I suspect F5 filters out requests without authorization header. Can you add specific rule? 

I will check If it doesn't hurt to add it and if it is positive, improvement will come with next 2.2.0 release.

**Comment by lroellin** [comment]
Yes, the F5 does filter requests without this header. I don't think security wants to add the rule for this specific URL.

Thanks for checking out, looking forward :)

**Comment by vbauzysvmware** [comment]
Seems that we can make this change, so will do this ;-) Thank you for investigation from your part!
