### ISSUE TITLE
ovf attribute on VM level

### ISSUE THREAD

**Issue by xcompass** [terraform-providers/terraform-provider-vcd#228]
Currently ovf attributes (to set OVF properties/guest properties) can only be set on vApp level (https://www.terraform.io/docs/providers/vcd/r/vapp.html#ovf). There is no such attribute on VM level. Because some/most of the attributes will be different on the VMs within the same vApp, e.g. hostnames, IPs, etc.

For example, I would like to use terraform to provision CoreOS on vcloud. CoreOS is using guest property to retrieve hostname, IP information.

**Comment by lvirbalas** [comment]
Assigning to @vbauzysvmware who has been diving close to this as part of #74 review/closure and the resulted #217

**Comment by vbauzysvmware** [comment]
Thank's for info - this will additional way of improving vapp/vm.

**Comment by Didainius** [comment]
WIP #313
