### ISSUE TITLE
network creation with incorrect VDC name crashes terraform

### ISSUE THREAD

**Issue by dataclouder** [terraform-providers/terraform-provider-vcd#229]
Using a configuration file with a name mistake results in a crash:

### Terraform Configuration Files

```hcl
# config.tf
provider "vcd" {
  user                 = "${var.user}"
  password             = "${var.password}"
  url                  = "https://${var.vcd_address}/api"
  sysorg               = "${var.sysorg}"
  org                  = "govcd"
  allow_unverified_ssl = "true"
  version              = "~> 2.0"
}

resource "vcd_network_routed" "second-net-govcd" {
  name         = "second-net-govcd"
  org          = "govcd"
  vdc          = "wrong-vdc-govcd"
  edge_gateway = "egw-govcd"
  gateway      = "192.168.2.1"

  static_ip_pool {
    start_address = "192.168.2.2"
    end_address   = "192.168.2.100"
  }
}
```

### Debug Output
https://gist.github.com/dataclouder/aefbd7ae4a86bbb8ebb38aee25687dfd

### Panic Output
https://gist.github.com/dataclouder/136fe515317a8e2a2c8e600abf763e29

### Expected Behavior
We should get an actionable error saying that the vdc does not exist.

### Actual Behavior
Terraform crashes with cryptic error.

### Steps to Reproduce
Using the above `config.tf`:
1. `terraform plan`
2. `terraform apply`

**Comment by vbauzysvmware** [comment]
This is fixed. With wrong vdc we get error:
`Error: error retrieving Org and VDC: error retrieving VDC a vbVdc: [ENF] entity not found`
