### ISSUE TITLE
~Feature request: Load balancer

### ISSUE THREAD

**Issue by spengilley** [terraform-providers/terraform-provider-vcd#234]
Hi there,

It would be wonderful if this provider gave the ability to configure the load balancer in the Edge gateway

**Comment by Didainius** [comment]
Hi @spengilley,
Not yet, but there is a draft and work should commence pretty soon. #223

**Comment by Didainius** [comment]
Any comments on the design or in general are appreciated in #223  post. I will close this if you don't mind.
