### ISSUE TITLE
The hostname is missing

### ISSUE THREAD

**Issue by koma85** [terraform-providers/terraform-provider-vcd#24]
### Terraform Version
Terraform v0.10.0

### Affected Resource(s)
vapp and vm

### Terraform Configuration Files
```hcl
provider "vcd" {
  user                 = "admin"
  password             = "blah"
  org                  = "blah"
  url                  = "https://admin.blah.io/api/"
  vdc                  = "vdc01"
  maxRetryTimeout      = "1800"
  allow_unverified_ssl = "true"
}

resource "vcd_network" "labnet01" {
  name         = "labnet01"
  edge_gateway = "gw01"
  gateway      = "192.168.3.1"

  dhcp_pool {
    start_address = "192.168.3.2"
   end_address   = "192.168.3.100"
  }

  static_ip_pool {
    start_address = "192.168.3.152"
    end_address   = "192.168.3.254"
  }
}
resource "vcd_dnat" "ssh" {
  depends_on    = ["vcd_network.labnet01"]
  edge_gateway = "gw01"
  external_ip  = "11.22.33.44"
  port         = 22
  internal_ip  = "192.168.3.152"
}
resource "vcd_snat" "outbound" {
  depends_on    = ["vcd_network.labnet01"]
  edge_gateway = "gw01"
  external_ip  = "11.22.33.44"
  internal_ip  = "192.168.3.0/24"
}

resource "vcd_vapp" "vapp01" {
  depends_on    = ["vcd_network.labnet01"]
  name          = "vapp01"
  network_name = "labnet01"
  power_on     = false
}


resource "vcd_vapp_vm" "vm01" {
  depends_on    = ["vcd_network.labnet01", "vcd_vapp.vapp01" ]
  vapp_name	= "vapp01"
  name          = "vm01"
  catalog_name  = "Vagrant"
  template_name = "tmpl_kqi_01"
  memory        = 1024
  cpus          = 1
  network_name = "labnet01"
  ip           = "allocated"
  power_on     = true
}

```

Host customization should change the hostname but the provided hostname is composed by something like $templatename-$resourcenumber

In this case the template is named centos70-x64 and the machine became named correctly vm01 but with hostname centos70-x6-001.

**Comment by bobbydeveaux** [comment]
Hey Andrea,

Thanks so much for this. I shall take it a look into it. I hope the multi-vm for vApps is working well for you other than this but please report anything untoward! :)

Many thanks

**Comment by robcoward** [comment]
HI @koma85, I haven't looked since the introduction of the "vcd_vapp_vm" resource, but there has always been an issue with the original "vcd_vapp" resource where the api call to trigger the guest customisation is only called when an initscript value is passed. If you include one such as my favourite string below to setup ssh public key authentication, the hostname will also be updated to reflect terraform's settings:

```
resource "vcd_vapp" "haproxy" {
  name          = "lb01.demo.devops-consultants.com"
  catalog_name  = "${var.catalog}"
  template_name = "${var.vapp_template}"
  memory        = 1024
  cpus          = 1
  network_name  = "${vcd_network.web_net.name}"
  ip            = "${var.haproxy_int_ip}"

  initscript = "mkdir -p ${var.ssh_user_home}/.ssh; echo \"${file("~/.ssh/${var.ssh_userid}.pub")}\" >> ${var.ssh_user_home}/.ssh/authorized_keys; chmod -R go-rwx ${var.ssh_user_home}/.ssh; restorecon -Rv ${var.ssh_user_home}/.ssh"
}
```

**Comment by koma85** [comment]
@bobbydeveaux Yes, I definitely am enjoing the multi-vm. I've found a bug  but i need to make another pair of test before open an issue.

@robcoward I'll try that.

Actually the vm name and the hostname should be two different things. In fact in the vcloud api the cputername is the hostname and the vmname is in fact the name of the virtual machine.

We should be able to differentiate the two things.

**Comment by koma85** [comment]
Confirmed.
Using init script the machine is correctly renamed.

**Comment by bobbydeveaux** [comment]
@robcoward @koma85  - I've pushed a changed to ignore checking the "initscript" variable to do guest customisation. The Guest Customistation will now be made regardless:

https://github.com/terraform-providers/terraform-provider-vcd/pull/31

One of you okay to look over it and give it a thumbs up please? :)

**Comment by bobbydeveaux** [comment]
Merged into master! :)

**Comment by koma85** [comment]
Cool! Thank you!
