### ISSUE TITLE
MAC Address duplicate

### ISSUE THREAD

**Issue by koma85** [terraform-providers/terraform-provider-vcd#25]
Latest version.

When using a template built in VCD mantaining the existing network interface you encounter an error on duplicate Mac Address.

After cloning the VM you chould refresh/regenerate the interface MAC.

**Comment by koma85** [comment]
My bad.
The error is only in vsphere.
In realty the mac address is regenerated.

**Comment by stack72** [comment]
@koma85 can this be closed?

**Comment by koma85** [comment]
Absolutely

**Comment by stack72** [comment]
👍
