### ISSUE TITLE
Add `import ressource` support

### ISSUE THREAD

**Issue by buec011** [terraform-providers/terraform-provider-vcd#252]
Similar to data sources it would be really helpful to have a import function for some resources.

This is used to update your terraform state file with existing resources, that have not been created by terraform.
Use case examples: 
The vCD provider does not have the capability yet to create ressource XY. Now it get this ability. We want to import the already created resources to manage them with terraform now. Example: The new vcd_org_vdc ressource.
In most cases we will need to import a VM that has been created without terraform, so an import function for vcd_vapp_vm would one of the most useful for us. 

### Links to documentation
https://www.terraform.io/docs/import/index.html

### Affected Resource(s)
Please list the resources as a list, for example:
- vcd_vapp_vm
- vcd_org_vdc
- other

### Expected Behavior
You can import an existing VM to your terraform state file

### Actual Behavior
terraform import vcd_vapp_vm $vm_id
is not available

**Comment by buec011** [comment]
Another use case: This can be used for migration if the provider deprecates code again: 
E.g. the commit

https://github.com/terraform-providers/terraform-provider-vcd/commit/7204e626524711e619e31a7846bf5971443aab78

deprecates `ip`, `network_name`, `vapp_network_change`

With a import for vcd_vapp_vm you can migrate as follow:
* Change the old code of vcd_vapp_vm to the new version
* Forget the state: terraform state rm vcd_vapp_vm
* Update the provider: terraform init
* Import the new version: terraform import vcd_vapp_vm $id
* terraform plan should not show changes.
* You migrated successfully

**Comment by lvirbalas** [comment]
@Didainius has the first import support being prepared for the upcoming EG Load Balancer Service Monitor resource:
https://github.com/terraform-providers/terraform-provider-vcd/pull/256/files

We'll be adding this functionality to other resources as well.

**Comment by Didainius** [comment]
The only thing resource not having an import is now VM.

**Comment by Didainius** [comment]
All the resources support imports as os 2.6.
