### ISSUE TITLE
Memory and CPU quotas in vcd_org_vdc definition

### ISSUE THREAD

**Issue by sam-calvert** [terraform-providers/terraform-provider-vcd#265]
Hello Team, 

The issue I am reporting is that new Org VDCs created with the provider appear not to respect the resource guarantees for cpu and memory resources as defined here:

https://www.terraform.io/docs/providers/vcd/r/org_vdc.html#memory_guaranteed
https://www.terraform.io/docs/providers/vcd/r/org_vdc.html#cpu_guaranteed

Setting those values to 0 results in the created VDC guaranteeing 20%. 

Here's a screen shot of a freshly created VDC with these values set to 20% despite 0's in the config: 

https://imgur.com/a/TZl7WNe

### Terraform Version
$ terraform version
Terraform v0.12.2
+ provider.vcd v2.3.0
+ provider.vsphere v1.11.0

### Affected Resource(s)
Please list the resources as a list, for example:
- vcd_org_vdc

### Expected Behavior
What should have happened? A value of 0 for memory_guaranteed and cpu_guaranteed should be respected.

### Actual Behavior
What actually happened?
Both values were set to 20% instead

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
Create a new org_vdc with cpu and memory guarantees set to 0. 

EDIT: I edited the actual behavior description to clarify that values were set to 20%, rather than changed. They seem to be initialized with incorrect values, not changed to them after the fact.

**Comment by vbauzysvmware** [comment]
Fix is merged and available with next release.
