### ISSUE TITLE
Computer name value is not adjusted when creating new VMs

### ISSUE THREAD

**Issue by gpritt** [terraform-providers/terraform-provider-vcd#273]
Hello all, I am attempting to create three ubuntu 18.04 machines in a vApp in our VCD environment and when I create them using a template in a catalog it appears that the Computer Name value doesn't change. I am using version 0.12.2 of Terraform and version 2.3.0 of the vcd provider

Here is part of my code:
```
resource "vcd_vapp" "ordswarmmasters" {
  name = "ordswarmmasters"
}

resource "vcd_vapp_vm" "ordswarmmaster1" {
  depends_on    = ["vcd_vapp.ordswarmmasters"]
  vapp_name     = "${vcd_vapp.ordswarmmasters.name}"
  name          = "ordswarmmaster1"
  catalog_name  = "ORD"
  template_name = "ubuntu-template"
  memory        = 4096
  cpus          = 2
  cpu_cores     = 1

  network_name  = "ORD-NET"
  ip            = "dhcp"
}
```

### Expected Behavior
I should have three VMs named ordswarmmaster1, 2, and 3 with the computer name values to match.

### Actual Behavior
I have three VMs where the Virtual Machine name reflects the value I put in the name property of the vcd_vapp_vm resource. However the Computer Name still remains ubuntu-template, which in turn produces three VM's with the hostname of ubuntu-template. Here is an example:
![image](https://user-images.githubusercontent.com/39133478/60364980-95087300-99b5-11e9-97e5-7e1d57232c2f.png)

Guest customization does occur and will rename the hostnames of the VM's but without changing the Computer Name property within VCD it doesn't give the VM's the correct hostname that I want. Hopefully I've made that clear enough, if it needs more clarification let me know. Thanks in advance!

**Comment by vbauzysvmware** [comment]
Currently computer name will be applied if `initscript` is provided.

**Comment by wjdavis5** [comment]
Where is that documented?

**Comment by vbauzysvmware** [comment]
Seems this isn't documented - this old code, can't comment much why this done like this. I suggest you expect computer name shouldn't be coupled with `initscript`. At the moment as workaround you may pass empty initsript to change computer name. I will look in code for possible changes if needed.

**Comment by wjdavis5** [comment]
Cool thanks for the additional info.
