### ISSUE TITLE
Reverse Terraform

### ISSUE THREAD

**Issue by wjdavis5** [terraform-providers/terraform-provider-vcd#276]
General Question here. It seems to me that it should be possible to use this provider to generate tf and tfstate files based on the existing configuration. I dont have any experience with go however, so I was curious if anyone had done something like this, and if any pointers could be offered.

Thanks!

Will.

**Comment by Didainius** [comment]
Hello @wjdavis5,
Terraform allows to do so called `import` but it must be implemented for each resource. At the moment this provider doesn't have them, but some new resources will get it in near future.

It does not however allow to generate `.tf` files as per https://www.terraform.io/docs/import/#currently-state-only

**Comment by Didainius** [comment]
Feel free to reopen if you have more questions.

**Comment by lvirbalas** [comment]
Just to add to Dainius', here's the tracking issue for adding the `import` capabilities:
https://github.com/terraform-providers/terraform-provider-vcd/issues/252
