### ISSUE TITLE
Add other authentication method to avoid VCD_PASSWORD in environment

### ISSUE THREAD

**Issue by buec011** [terraform-providers/terraform-provider-vcd#280]
Hello,
it would be really helpful for us to have an authentication method which is not password based or to use temporary tokens.
One possible solution will be similar to Openstack with its OS_TOKEN option:
Instead of
export VCD_PASSWORD=xxx
in the environement, we may get a temporary token via API
e.g.
```
curl -i -k -H "Accept:application/*;version=32.0" -u USER -X POST https://1.2.3.4/api/sessions
```
(edit: see line with x-vcloud-authorization) 
and use a VCD_TOKEN option instead.

### Terraform Version
terraform -v
Terraform v0.12.3

### Affected Resource(s)
- provider "vcd"

### Terraform Configuration Files
```hcl
provider "vcd" {
  user                 = "administrator"
  token             = "${var.vcd_token}"
  org                  = "System"
  url                  = "${var.vcd_url}"
  max_retry_timeout    = "${var.vcd_max_retry_timeout}"
  allow_unverified_ssl = "${var.vcd_allow_unverified_ssl}"
}
```

### Expected Behavior
Avoid password in environement or in files

### Actual Behavior
Critical credential file needed or password in env of the operating system

**Comment by dataclouder** [comment]
Probably the interface might require a few header items, such as: `X-VMWARE-VCLOUD-ACCESS-TOKEN`, `x-vcloud-authorization`, `X-VMWARE-VCLOUD-TOKEN-TYPE`.

We could implement this enhancement by allowing either a password or a set of `auth_header`  items.

Since tokens are associated with user + org, it should be possible to make also `user` and `sysorg` optional, such as

```hcl
provider "vcd" {
  auth_header {
    key   = "x-vcloud-authorization"
    value = "$var.vcd.sys_admin_token"
  }
  auth_header {
    key   = "token-type"
    value = "bearer"
  }
  url                  = "${var.vcd_url}"
  max_retry_timeout    = "${var.vcd_max_retry_timeout}"
  allow_unverified_ssl = "${var.vcd_allow_unverified_ssl}"
}
```

```hcl
provider "vcd" {
  auth_header {
    key   = "x-vcloud-authorization"
    value = "$var.vcd.org_xyz_token"
  }
  auth_header {
    key   = "token-type"
    value = "bearer"
  }
  url                  = "${var.vcd_url}"
  max_retry_timeout    = "${var.vcd_max_retry_timeout}"
  allow_unverified_ssl = "${var.vcd_allow_unverified_ssl}"
}
```
I don't know if user and sysorg can be pulled out from the provider, as we may have some places where we use such fields for unrelated operations.
 
Needs some research and testing.

**Comment by dataclouder** [comment]
[Pull #393](https://github.com/terraform-providers/terraform-provider-vcd/pull/393) is addressing this issue.
[The docs](https://github.com/dataclouder/terraform-provider-vcd/blob/auth-token/website/docs/index.html.markdown) show how it would work.

**Comment by buec011** [comment]
From the doc:
> When using a token, the fields user and password will be ignored, but they need to be in the script.

We do not have a provider block in our templates yet, we work with environment.
Is it sufficient to have
VCD_USER=''
VCD_PASSWORD=''
in the environment?

**Comment by buec011** [comment]
Is it possible to define the token with
VCD_TOKEN?

**Comment by buec011** [comment]
From the doc:

> When using a token, the fields user and password will be ignored, but they need to be in the script.
Should the field
	SysOrg          string // Org used for authentication
ignored as well?

**Comment by dataclouder** [comment]
You can define the token with VCD_TOKEN, but be careful that it's as dangerous as using an environment variable for password, as the bearer of this token will be able to run everything.
You should leave VCD_USER and VCD_PASSWORD with some values, as the provider complains when they are missing.
The field SysOrg is needed, as the token is produced for a given URL+ organization+ user.
Even after you have the token, you need the sysOrg to connect to the provider.

**Comment by buec011** [comment]
> The field SysOrg is needed, as the token is produced for a given URL+ organization+ user.

I thought only Org is needed, not SysOrg? 
(SysOrg ist optional according to the documentation. If it is needed for token auth, it is missing in the doc of the PR )

If I do something on provider level, I will use org=system. If I do something in org (but as provider), I will use e.g. org=test-org1. In both cases I got the token with my provider user and system org.
Am I wrong?


> You can define the token with VCD_TOKEN

Ok, it is missing in the doc of your PR.


> You can define the token with VCD_TOKEN, but be careful that it's as dangerous as using an environment variable for password, as the bearer of this token will be able to run everything.

It depends on how you trust your environment: 
Is it more secure to save it in a file? 
 - can be read by OS administrators
 - will be saved on a hard disk/SAN storage: non-ephemeral storage, which of course need to be erased without the possibility to restore this data
- someone accidentally upload the credentials file/provider section with credentials to a bug report here
- this is mitigated with a token, because the token will become invalid after SessionTimeoutMinutes has been reached

Is it more secure to save it in the environment?
- is ephemeral (maybe memory dump contain it)
- someone can see it on your display if you show him your env (accidentally), but this is under my control
- this is mitigated with a token, because the token will become invalid after SessionTimeoutMinutes has been reached

So both is dangerous and it depends if a credential file or environment is more safe

**Comment by dataclouder** [comment]
About `sysOrg`, my bad. What I mean is that either `org` or `sysOrg` must be set. If there is no `sysOrg`, the provider takes the value of `org` for that purpose.

To simplify the requirements: when a token is defined, user and password are ignored. Everything else is needed or optional just as when we user regular credentials.

I mentioned the *dangerous* environment only because you seemed to express concern about it in the feature request ("Add other authentication method to avoid VCD_PASSWORD in environment").

`VCD_TOKEN` is now mentioned in the docs.

**Comment by buec011** [comment]
> I mentioned the dangerous environment only because you seemed to express concern about it in the feature request ("Add other authentication method to avoid VCD_PASSWORD in environment").

Ah, understood. For me the mitigation by a temporary session token was important.

Well done.

**Comment by dataclouder** [comment]
Thanks.
Could you confirm whether you can safely operate with tokens using this PR?
We're about to merge

**Comment by buec011** [comment]
Ok, will need ~1hour
(Compile and test)

**Comment by buec011** [comment]
Added my comment to the PR directly: Works for me.

**Comment by dataclouder** [comment]
Thanks
