### ISSUE TITLE
terraform doesnt find provider vdc when creating new vdc vcd 9.7 & nsxt 2.4.1

### ISSUE THREAD

**Issue by aambert** [terraform-providers/terraform-provider-vcd#287]
code-->
resource "vcd_org_vdc" "my-vdc" {
  name        = "my-vdc"
  description = "The pride of my work"
  org         = "testclient"

  allocation_model = "AllocationPool"
  #network_pool_name = "vDC1-VXLAN-NP"
  provider_vdc_name = "nsxtpvdc"

  compute_capacity {
    cpu {
      allocated = 2048
    }

    memory {
      allocated = 2048
    }
  }

  storage_profile {
    name     = "storage-name"
    limit    = 10240
    default  = true    
  }

  enabled                  = true
  enable_thin_provisioning = true
  enable_fast_provisioning = true
  delete_force             = true
  delete_recursive         = true
}

<---endofcode
wsl@vm-admin:/mnt/c/GitSrc/vCD/VCD$ terraform -v
Terraform v0.11.13
+ provider.vcd v2.3.0

wsl@vm-admin:/mnt/c/GitSrc/vCD/VCD$ terraform plan -out plan1.out
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

vcd_org.testclient: Refreshing state... (ID: b8f9d4cb-e0f2-4f38-af71-e099c3983ea9)

------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  + vcd_org_vdc.my-vdc
      id:                                                      <computed>
      allocation_model:                                        "AllocationPool"
      allow_over_commit:                                       "true"
      compute_capacity.#:                                      "1"
      compute_capacity.2941852481.cpu.#:                       "1"
      compute_capacity.2941852481.cpu.1292085343.allocated:    "2048"
      compute_capacity.2941852481.cpu.1292085343.limit:        ""
      compute_capacity.2941852481.memory.#:                    "1"
      compute_capacity.2941852481.memory.1292085343.allocated: "2048"
      compute_capacity.2941852481.memory.1292085343.limit:     ""
      delete_force:                                            "true"
      delete_recursive:                                        "true"
      description:                                             "The pride of my work"
      enable_fast_provisioning:                                "true"
      enable_thin_provisioning:                                "true"
      enabled:                                                 "true"
      name:                                                    "my-vdc"
      org:                                                     "testclient"
      provider_vdc_name:                                       "nsxtpvdc"
      storage_profile.#:                                       "1"
      storage_profile.0.default:                               "true"
      storage_profile.0.enabled:                               "true"
      storage_profile.0.limit:                                 "10240"
      storage_profile.0.name:                                  "storage-name"

Plan: 1 to add, 0 to change, 0 to destroy.

------------------------------------------------------------------------

This plan was saved to: plan1.out

To perform exactly these actions, run the following command to apply:
    terraform apply "plan1.out"

wsl@vm-admin:/mnt/c/GitSrc/vCD/VCD$ terraform apply "plan1.out"
Releasing state lock. This may take a few moments...
vcd_org_vdc.my-vdc: Creating...
  allocation_model:                                        "" => "AllocationPool"
  allow_over_commit:                                       "" => "true"
  compute_capacity.#:                                      "" => "1"
  compute_capacity.2941852481.cpu.#:                       "" => "1"
  compute_capacity.2941852481.cpu.1292085343.allocated:    "" => "2048"
  compute_capacity.2941852481.cpu.1292085343.limit:        "" => ""
  compute_capacity.2941852481.memory.#:                    "" => "1"
  compute_capacity.2941852481.memory.1292085343.allocated: "" => "2048"
  compute_capacity.2941852481.memory.1292085343.limit:     "" => ""
  delete_force:                                            "" => "true"
  delete_recursive:                                        "" => "true"
  description:                                             "" => "The pride of my work"
  enable_fast_provisioning:                                "" => "true"
  enable_thin_provisioning:                                "" => "true"
  enabled:                                                 "" => "true"
  name:                                                    "" => "my-vdc"
  org:                                                     "" => "testclient"
  provider_vdc_name:                                       "" => "nsxtpvdc"
  storage_profile.#:                                       "" => "1"
  storage_profile.0.default:                               "" => "true"
  storage_profile.0.enabled:                               "" => "true"
  storage_profile.0.limit:                                 "" => "10240"
  storage_profile.0.name:                                  "" => "storage-name"

Error: Error applying plan:

1 error(s) occurred:

* vcd_org_vdc.my-vdc: 1 error(s) occurred:

* vcd_org_vdc.my-vdc: no provider VDC found with name nsxtpvdc

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

name of the pvdc with vcd cli

vcd pvdc list
name
--------
nsxtpvdc

**Comment by vbauzysvmware** [comment]
@aambert  Could you double check that name is correct? Cause this error only happens if vCD API doesn't return provider vdc with such name. Not much code handling in this case. To see something more valuable I would need logs from go-vcloud-director which should be enabled - docs(logging, logging_file): https://www.terraform.io/docs/providers/vcd/index.html

**Comment by aambert** [comment]
I double checked with vcd cli you can see logs here for the plan and the apply [Terraform TRACE](https://pastebin.com/tHG97T9a) see screenshot of vcdcli and vcd 9.7 backed by nsxt 2.4.1 [SCREENSHOT](https://ibb.co/8djGFZP)

**Comment by vbauzysvmware** [comment]
Hi @aambert. Thank you for information. Seems name correct. Could you add go-vcloud-director logs, cause all important info is there.

**Comment by aambert** [comment]
Hi @vbauzysvmware can you tell me how do i enable and get go-vcloud-director ?

**Comment by vbauzysvmware** [comment]
You can find mentioned here https://www.terraform.io/docs/providers/vcd/index.html. You need to add logging, logging_file attributes to `providers` part

**Comment by aambert** [comment]
@vbauzysvmware  sorry for the delay here go logs thank you [pastebinlogsgo](https://pastebin.com/haGUHBcf)

**Comment by vbauzysvmware** [comment]
https:/uip/api/query?&type=providerVdc&filter=(name==nsxtpvdc) - returns zero results. Something different is culprit.

**Comment by aambert** [comment]
vcd cli return the same answear nsxtpvdc maybe its the api version 27 to 32 ? what can i do to troubleshoot ?

**Comment by vbauzysvmware** [comment]
Very low chance that's it is something with API versions.
Possible issue with user which is used for terraform. 
Also maybe possible to check by creating another simple providerVdc. Maybe some configuration impact queries.

**Comment by aambert** [comment]
i'll do that create another pvdc with another user and get back to you

**Comment by ihumster** [comment]
Get the same problem. When provider trying find pVDC with using query service he make request:
GET https://vcloud-lab.xxxxxxx.com/api/query?&type=providerVdc&filter=(name==Lab Cloud LAB01) <- with brackets and vcloud return 400 Bad request

If I try this request from Postman - I get the same error. Need making url without brackets - and vcloud return right answer:
GET https://vcloud-lab.xxxxxxx.com/api/query?&type=providerVdc&filter=name==Lab Cloud LAB01

**Comment by vbauzysvmware** [comment]
I think this will solved this issue also: https://github.com/vmware/go-vcloud-director/pull/233

**Comment by ihumster** [comment]
@vbauzysvmware I don’t think so. This pull request adds string escaping, but the brackets themselves remain in the request.

![image](https://user-images.githubusercontent.com/557105/63846776-25067100-c995-11e9-9b66-4143cf433d5c.png)

**Comment by dataclouder** [comment]
@ihumster The fix was merged to master yesterday, and I confirm that  names with spaces are properly escaped and it works well in practice.

**Comment by aambert** [comment]
@ihumster say it's not working with that query:
https://{{host}}/api/query?&type=providerVdc&filter=(name==onprempvdc)

here the log of the last compiled code of master yesterday against vcd 10 backed by nsxt 2.5 no space no special char, etc..

logging:
2019/10/07 22:51:30 --------------------------------------------------------------------------------
2019/10/07 22:51:30 Request caller: schema.(*Provider).Apply-->schema.(*Resource).Apply-->vcd.resourceVcdVdcCreate-->vcd.getVcdVdcInput-->govcd.QueryProviderVdcByName-->govcd.(*VCDClient).QueryWithNotEncodedParams-->govcd.(*Client).QueryWithNotEncodedParams
2019/10/07 22:51:30 GET https://{{host}}/api/query?&type=providerVdc&filter=(name==onprempvdc)


Postman answer the correct pvdc when you use this request:
https://{{host}}/api/query?type=providerVdc&filter=name==onprempvdc 
it's not a problem of space or special characters just ( )

The problem is critical because if you create vdc's for each of your client the provider_vdc_name is mandatory so nothing is working.

i ll fork and correct this for me to get further but it would be really great if you correct this.

Thank you

**Comment by aambert** [comment]
Hello did you fix this in some # release?

**Comment by vbauzysvmware** [comment]
Changes were done and now in master.
