### ISSUE TITLE
Doc is missing features

### ISSUE THREAD

**Issue by dn1s** [terraform-providers/terraform-provider-vcd#30]
Hi,

doc is missing features already implemented.

Kind regards,

dn1s

**Comment by bobbydeveaux** [comment]
The doc in GitHub? or the doc on Terraform.io?

**Comment by bobbydeveaux** [comment]
<img width="675" alt="screen shot 2017-08-03 at 14 52 12" src="https://user-images.githubusercontent.com/5550105/28924963-5f12ebd6-785b-11e7-889e-aae01470f206.png">

**Comment by dn1s** [comment]
I was talking about terraform.io but your 2nd post answers why it's still the old website.
I'd let this issue open until TC job is fixed.

**Comment by bobbydeveaux** [comment]
This has now been resolved.
