### ISSUE TITLE
Add support for `Change SID`

### ISSUE THREAD

**Issue by vtodorovv** [terraform-providers/terraform-provider-vcd#303]
Add support for `Change SID`

**Comment by Didainius** [comment]
Hello, @vtodorovv 
Can you please share more details which resources do you want this to work for and any suggestion for how the HCL configuration should look like?

**Comment by vtodorovv** [comment]
Hey, apologies, would be great if this was available for vcd_vapp_vm. Can probably go with https://github.com/terraform-providers/terraform-provider-vcd/issues/300 ? No suggestion for HCL i'm afraid.

**Comment by buec011** [comment]
Hello,
we would like to see this as well. This is needed for Windows VMs that you want to join to an active directory.

The customization block mentioned in https://github.com/terraform-providers/terraform-provider-vcd/pull/310 looks like a good place for this:

> The customization block was introduced as there is already demand to make other customization features available as the GUI has in "Guest customization" tab.

**Comment by Didainius** [comment]
This should go into the [customization](https://www.terraform.io/docs/providers/vcd/r/vapp_vm.html#customization) block for VM.

**Comment by Didainius** [comment]
@vtodorovv,
I would appreciate if you can test out the code in pull request https://github.com/terraform-providers/terraform-provider-vcd/pull/462

**Comment by vtodorovv** [comment]
Thank you @Didainius
