### ISSUE TITLE
Ability to deploy catalog template with multiple VMs in it

### ISSUE THREAD

**Issue by elandmancrs** [terraform-providers/terraform-provider-vcd#305]
Terraform Version
Terraform v0.12.6
provider.vcd v2.4.0

Affected Resource(s)
vcd_vapp_vm

vCloud allows you to capture a vApp as a catalogue template which contains more than one VM in it. The current vcd plugin only allows a vApp template within a catalogue with one VM in it.
Perhaps add an attribute called vm_name, so one can specify deploying a specific VM within the template. Or deploy a vApp template outright with all VM's within it, allowing to specify the VM's details, or not. If not, then deploy as captured.

```
resource "vcd_vapp_vm" "web1" {
  vapp_name     = "${vcd_vapp.web.name}"
  name          = "web1"
  catalog_name  = "Boxes"
  template_name = "myNewvAppTemplate"
  vm_name  = "web"
  memory        = 2048
  cpus          = 1
```

**Comment by elandmancrs** [comment]
ping

**Comment by lvirbalas** [comment]
Hi @elandmancrs 

Allow me to rephrase/confirm your request.

vApp template may contain more than one VM, hence need ability to:
1. Deploy the whole vApp with all of the VMs from the template
2. Deploy VM by choosing specific VM from the multi-VM vApp template 

Would you share how would you envision HCL configuration for the (1) one? That's actually quite a big structure change. Would (2) be enough? (2) is more realistic to solve in a reasonable time frame.

p.s. Which company are you coming from?

CC: @dataclouder @Didainius

**Comment by elandmancrs** [comment]
Hi, 
If I'm not mistaken, Option 2 will allow Option 1, just not as elegantly. It'll also allow me to better implement what I currently have. I have a network of PS scripts which interact with vCloud, and a mixture of Terraform, where first win would be pure Terraform.

I'd say then if we can accomplish 2, then 1 would be a nice to have at a later stage.

I'd envision the HCL to look for Option 1 as follows...
`resource "vcd_vapp" "tf-vapp" {
    name     = var.envname
    catalog_name  = "Prebuilt_vApps"
    template_name = "Kafka_v1.1"
    power_on     = true

    network {
    type               = "org"
    name               = "OrgNet_Kafka1"
    ip_allocation_mode = "POOL"
    }
  }`
The tricky bit admittedly is to customise the attributes of contained vm's within the vApp with multiple VM's.

That's where for now, Option 2 trumps 1.

Do we have an idea of what the HCL will look like with Option 2?

**Comment by dataclouder** [comment]
`catalog_name` and `template_name` within the vApp are deprecated, with good reason, as their usage creates an implicit VM that is not referenced by a resource.

To solve the issue in a clean manner we could:
1. add a vApp Template resource, with its list of VMs
2. Add another parameter to the VM resource to identify which VM we want from the template.

**Comment by elandmancrs** [comment]
The cleaner option being the first. Makes it a first class citizen.

Whereas the second just opens functionality. 

Either suits me fine 😊

**Comment by elandmancrs** [comment]
Hi there, 
Just a quick ping as to the progress here?

**Comment by Didainius** [comment]
@elandmancrs,
This is not forgotten, but we haven't yet started actively working on it.

**Comment by elandmancrs** [comment]
> @elandmancrs,
> This is not forgotten, but we haven't yet started actively working on it.

Thank you!

**Comment by vbauzysvmware** [comment]
Implemented possibility 2: Deploy VM by choosing specific VM from the multi-VM vApp template

**Comment by carlschroder** [comment]
Never actually thanked you all for adding this way back when. Boy have we used this functionality!
