### ISSUE TITLE
Add support for VM and vApp guest properties in `vcd_vapp_vm` and `vcd_vapp` resources

### ISSUE THREAD

**Issue by Didainius** [terraform-providers/terraform-provider-vcd#313]
VM has a possibility to set guest properties (OVF properties) for images that support this. This provider does not yet support this feature and this issue is set to track it.

**Comment by swerveshot** [comment]
Currently there seems to be some support for ovf attributes, but only at the vApp level. And when you try to use it you get the following error message:
```
PS H:\Documents\Code\Terraform-vCD-vSphereLab> terraform apply --auto-approve
vcd_vapp.vsphere67lab: Creating...

Error: error setting the ovf: &errors.errorString{s:"vApp doesn't contain any children, aborting customization"}

  on main.tf line 19, in resource "vcd_vapp" "vsphere67lab":
  19: resource "vcd_vapp" "vsphere67lab" {
```

My use case: creating vSphere lab environments based on @lamw's nested ESXi virtual appliances.

**Comment by Didainius** [comment]
Hello @swerveshot,
The support for OVF properties is already in `master` branch and will be released in 2.5.0 (aimed for end of october).
If you have a chance and wish to test you could try building the provider from master and say what you think. We cannot guarantee that it will be 100% as it is in master when it is released (if we find some bugs/problems as final pre-release testing).

This is how it looks in both vApp and VM levels:
```hcl
guest_properties = {
    "guest.hostname" = "my-hostname"
    "guest.other"    = "another-setting"
  }
```
You could also explore the VM and vApp documentation in master for examples:
https://github.com/terraform-providers/terraform-provider-vcd/blob/master/website/docs/r/vapp_vm.html.markdown

https://github.com/terraform-providers/terraform-provider-vcd/blob/master/website/docs/r/vapp.html.markdown
```

**Comment by Didainius** [comment]
The functionality is in `master` and is targeted for 2.5.0 release. Feel free to reopen if you see any issues.

**Comment by swerveshot** [comment]
Thanks for the feedback @Didainius! And good to know where to find the most up-to-date documentation.

**Comment by marwanhammad** [comment]
do you publish your code to create nested ESX in vcd for  vSphere lab?

**Comment by marwanhammad** [comment]
> 
> 
> Currently there seems to be _some_ support for [ovf attributes](https://www.terraform.io/docs/providers/vcd/r/vapp.html#ovf), but only at the vApp level. And when you try to use it you get the following error message:
> 
> ```
> PS H:\Documents\Code\Terraform-vCD-vSphereLab> terraform apply --auto-approve
> vcd_vapp.vsphere67lab: Creating...
> 
> Error: error setting the ovf: &errors.errorString{s:"vApp doesn't contain any children, aborting customization"}
> 
>   on main.tf line 19, in resource "vcd_vapp" "vsphere67lab":
>   19: resource "vcd_vapp" "vsphere67lab" {
> ```
> 
> My use case: creating vSphere lab environments based on @lamw's nested ESXi virtual appliances.
> 
> Having the ability to set the guest properties is required to create a lab environment unattended.

do you publish your code to create nested ESX in vcd for vSphere lab?

**Comment by Didainius** [comment]
> do you publish your code to create nested ESX in vcd for vSphere lab?

@marwanhammad ,
We don't have a ready example to do that however the parameter to run nested ESXi is - https://www.terraform.io/docs/providers/vcd/r/vapp_vm.html#expose_hardware_virtualization
