### ISSUE TITLE
vcd_firewall_rules needs update functionality

### ISSUE THREAD

**Issue by vbauzysvmware** [terraform-providers/terraform-provider-vcd#318]
Resource vcd_firewall_rules needs update function to support resource updates and not recreation.

**Comment by Didainius** [comment]
`vcd_firewall_rules` is using vCD API which is not recommended anymore. A new resource (vcd_nsxv_firewall_rule)[https://www.terraform.io/docs/providers/vcd/r/nsxv_firewall_rule.html] is the recommended resource now and it supports update, import and data source.
