### ISSUE TITLE
Add subinterface as interface type when creating a routed Org VDC Network

### ISSUE THREAD

**Issue by swerveshot** [terraform-providers/terraform-provider-vcd#321]
### Terraform Version
Terraform v0.12.7
\+ provider.vcd v2.4.0

### Affected Resource(s)
- vcd_network_routed
- vcd_edgegateway

### Expected Behavior
As a vCD system user I would like to have the ability to create an Organization VDC routed network that is created as a subinterface on an Edge Gateway.

![image](https://user-images.githubusercontent.com/10358044/64327753-85686480-cfcc-11e9-8a33-b2b917ec32f5.png)

### Actual Behavior
Currently when creating a routed network with the vCloud Director Provider this network is attached to the edge gateway as a regular interface. This means that only a maximum of 9 networks can be attached to that edge. As you can attach a maximum of 10 NICs to a vSphere VM. If you were to use the option to have the network use a subinterface a maximum of 200 networks can be used.

### Steps to Reproduce
- `terraform apply`
- observe the network created in the vCD UI and check the interface type

### References
- [vCloud Director Administrator's Guide](https://docs.vmware.com/en/vCloud-Director/9.7/com.vmware.vcloud.admin.doc/GUID-6E69AF88-31E0-4DD8-A79E-E8E4B6F68878.html)

**Comment by lvirbalas** [comment]
Thank you @swerveshot for defining the needed feature so nicely!

**Comment by dataclouder** [comment]
IMplemented with #402
