### ISSUE TITLE
Routed vApp Network

### ISSUE THREAD

**Issue by lvirbalas** [terraform-providers/terraform-provider-vcd#329]
Currently the `vcd_vapp_network` resource supports the _isolated_ vApp network type. We need to extend it and add _routed_ vApp network support.

# Possible implementation

1. Add three new parameters to `vcd_vapp_network` which allow defining a _routed_ vApp network:
```hcl
resource "vcd_vapp_network" "VAppNetwork" {
  name         = "vapp-net"
  vapp_name = "vapp-test-net"

  # Parameters (all optional) which allow connecting this vApp network to the Org VDC network
  network = “org-vdc-net1” 
  nat_enabled = “true”
  firewall_enabled = “true”
...
}
```

2. Add new resources two manage Firewall, NAT and Static Routing at vApp network level:

- `vcd_vapp_dnat`
- `vcd_vapp_snat`
- `vcd_vapp_firewall_rule`
- `vcd_vapp_static_route`

### Affected Resource(s)

- vcd_vapp_network

### References

https://github.com/terraform-providers/terraform-provider-vcd/pull/155#issuecomment-530483460

**Comment by jgreenback** [comment]
Hi @lvirbalas, I hope this clarifies the issue/request a bit better.  If not I'd be happy to further clarify.

1.	Add 4 new parameters to `vcd_vapp_network` which should allow defining a routed vApp network:

```
resource "vcd_vapp_network" "vAppNetwork" {
  name         = "vapp-net"
  vapp_name = "vapp-test-net"

  # 4 Parameters (all optional) which allow connecting the vApp network to an Org VDC network
      org_network = “org01-network-01”
      nat_enabled = “true”
      firewall_enabled = “true”
      retainip_enabled = “true”
...
}
```
**vCD Flex UI Screenshots depicting above:** 
![image](https://user-images.githubusercontent.com/32180972/65557748-43568280-dee9-11e9-9efb-5e032499b5b4.png)
![image](https://user-images.githubusercontent.com/32180972/65557788-5c5f3380-dee9-11e9-8a35-3322f507f54c.png)

2.	Add new resources to manage Firewall, NAT and Static Routing at vApp network level:
•	`vcd_vapp_nat_type`
o	2 values, `iptranslation` (should be default), and `portforwarding`
     	With ip translation enabled S/DNAT is handled automatically.  Need to be able to add VMs.
![image](https://user-images.githubusercontent.com/32180972/65557842-8a447800-dee9-11e9-9f3a-cd47cfe92be0.png)

     	With port forwarding you’re given additional config options, enable, disable ip masquerade and add, delete port forwarding rules.  Additional config fields for adding new rules below:
![image](https://user-images.githubusercontent.com/32180972/65557854-94667680-dee9-11e9-9477-2b798692cddf.png)

       •	`vcd_vapp_firewall_rule`
       o	Enable, disable, add, delete, + full config fields.  Example screenshot below:
        ![image](https://user-images.githubusercontent.com/32180972/65557865-9d574800-dee9-11e9-9f11-1bc8cb8e23bc.png)

       •	`vcd_vapp_static_route`
       o	Enable, disable, add, delete, + full config fields.  Example screenshot below:
        ![image](https://user-images.githubusercontent.com/32180972/65557868-a34d2900-dee9-11e9-9422-59ab0bebd2af.png)

**Comment by lvirbalas** [comment]
Thank you @jgreenback for a nice write-up.

**Comment by jgreenback** [comment]
**Thank you!** (@lvirbalas), @vbauzysvmware (and rest of team) for all you're hard work on this TF provider.
Cheers!

**Comment by danonh** [comment]
Hi, is this change has been implemented yet, or is it on your radar? We need this functionality as well to provisioned vApps with routed vApp networks. Regards,

**Comment by lvirbalas** [comment]
Hi @danonh , yes, this is a confirmed feature for the roadmap.

**Comment by vbauzysvmware** [comment]
All functionality implemented and released
