### ISSUE TITLE
Terraform can't import catalog items with dots in them

### ISSUE THREAD

**Issue by cheald** [terraform-providers/terraform-provider-vcd#343]
### Terraform Version

0.11.4, 0.12.9, HEAD version of the plugin

### Affected Resource(s)

Please list the resources as a list, for example:
- vcd_catalog_item.

Terraform can't import catalog items with dots in them (such as `ubuntu-18.04-server-cloudimg-amd64-20181124.ova`), since the current plugin implementation uses strings.Split() and checks for 3 pieces. Instead, it should use strings.SplitN(str, ".", 3) to split into no more than 3 piece.

```patch
diff --git a/vcd/resource_vcd_catalog_item.go b/vcd/resource_vcd_catalog_item.go
index 8ab8cfd..1bef4f9 100644
--- a/vcd/resource_vcd_catalog_item.go
+++ b/vcd/resource_vcd_catalog_item.go
@@ -248,7 +248,7 @@ func createOrUpdateCatalogItemMetadata(d *schema.ResourceData, meta interface{})
 //
 // Example import path (id): org_name.catalog_name.catalog_item_name
 func resourceVcdCatalogItemImport(d *schema.ResourceData, meta interface{}) ([]*schema.ResourceData, error) {
-       resourceURI := strings.Split(d.Id(), ".")
+       resourceURI := strings.SplitN(d.Id(), ".", 3)
        if len(resourceURI) != 3 {
                return nil, fmt.Errorf("resource name must be specified as org.catalog.catalog_item")
        }
```

**Comment by dataclouder** [comment]
This issue needs some careful consideration, because most every entity can have dots in the name. If the Org and Catalog have dots in their names, using `SplitN` will not solve the problem.

**Comment by lobbin** [comment]
In our case, same goes for vapp's and vapp vm's

**Comment by dataclouder** [comment]
In terraform-provider-vcd 2.5 we have added the ability of changing the import separation string.
The import separation can be changed in two ways:
* using the `import_separator` property [in the provider](https://www.terraform.io/docs/providers/vcd/index.html)
* using the environment variable `VCD_IMPORT_SEPARATOR`.

For example, if you want to import the following:

```hcl
resource "vcd_catalog_item" "my_template" {
  org     = "my.org.name"
  catalog = "my:catalog:name"

  name                 = "my.vapp.template"
  ova_path             = "/path/to/test-resources/test_vapp_template.ova"
  upload_piece_size    = 5
  show_upload_progress = "true"
}
```
We notice that two elements of the hierarchy have dots in their name, and one has colons.
We can import as follows:

```
export VCD_IMPORT_SEPARATOR="#"
terraform import \
     vcd_catalog_item.my_template \
    "my.org.name#my:catalog:name#my.vapp.template"
```
