### ISSUE TITLE
Cannot find the VDC storage policy with v0.10

### ISSUE THREAD

**Issue by Boran** [terraform-providers/terraform-provider-vcd#39]
Hi,

After updating 0.9.6 to v0.10, I can no longer create VMs on vCloud
```
* vcd_vapp.terravm: Error creating vapp: &errors.errorString{s:"Error creating vapp: &errors.errorString{s:\"error instantiating a new vApp: API Error: 400: [ e172bcb4-db68-49b4-bd87-8d8d04a95adb ] Cannot find the VDC storage policy \\\"545fb858-3a90-4801-86d4-00d275ae1b6d\\\".\"}"}
```

Switching back to terraform 0.9.6, the same main.tf works fine.

There is no storage reference in the TF file, and its not complicated:
```
provider "vcd" {
  user                 = "${var.username}"
  password             = "${var.password}"
  org                  = "${var.org}"
  url                  = "${var.url}"
  vdc                  = "${var.vdc}"
  maxRetryTimeout      = "${var.maxRetryTimeout}"
  allow_unverified_ssl = "${var.allow_unverified_ssl}"
}
resource "vcd_vapp" "terravm" {
  name          = "${var.vmname}"
  catalog_name  = "${var.catalog}"
  template_name = "${var.template}"
  memory        = "${var.memory}"
  cpus          = "${var.cpus}"
  metadata {
    owner       = "${var.owner}"
    description = "${var.description}"
  }
  network_name = "${var.network}"
  ip = "${var.ip}"
..
```
Any ideas?

**Comment by bobbydeveaux** [comment]
hi @Boran 

In the new provider, we have merged in this PR: https://github.com/terraform-providers/terraform-provider-vcd/pull/23

This introduces the storage profile support and changes the way VMs are created. Obviously something here is affecting your ability to use terraform. 

@dn1s - did you encounter this at all when adding storage profile support?

**Comment by bobbydeveaux** [comment]
@Boran - could you run this with env var TF_LOG=1 please?

**Comment by bobbydeveaux** [comment]
Also, you can specify which provider version to use if you see here, you can see when the storage profile support was added. 
https://github.com/terraform-providers/terraform-provider-vcd/blob/master/CHANGELOG.md

If you load the 0.1.1 version of the provider with terraform 0.10, you could confirm that this is indeed an issue introduced in 0.1.2 of the provider?

Cheers

**Comment by Boran** [comment]
Provider version:
> terraform init
> - Downloading plugin for provider "vcd"...
> * provider.vcd: version = "~> 0.1"

I added a parameter to main.tf, which corresponds to the name of the Storage Policy I have available in the vCloud UI.

storage_profile = "Fast Storage with Snapshot Site A2"

And then ... it works, I can create the VM!

So storage_profile is mandatory.
Thanks!

**Comment by bobbydeveaux** [comment]
Awesome thanks. 

@dn1s os this something you're able to look at at all, or do you need me to add it to my list? :)

**Comment by dn1s** [comment]
@bobbydeveaux I didn't find a way in go which allows me to add the storage policy dynamically to the xml map. If you can figure this out you can set storage policy to optional parameter again.

**Comment by bobbydeveaux** [comment]
Okay thanks @dn1s will take a look

**Comment by bobbydeveaux** [comment]
@dn1s - I was going to suggest the `omitempty` attribute of the storage profile, but it appears it is already set:

```
type SourcedCompositionItemParam struct {
	// Attributes
	SourceDelete bool `xml:"sourceDelete,attr,omitempty"` // True if the source item should be deleted after composition is complete.
	// Elements
	Source              *Reference           `xml:"Source"`                        // Reference to a vApp, vApp template or virtual machine to include in the composition. Changing the name of the newly created VM by specifying name attribute is deprecated. Include VmGeneralParams element instead.
	VMGeneralParams     *VMGeneralParams     `xml:"VmGeneralParams,omitempty"`     // Specify name, description, and other properties of a VM during instantiation.
	VAppScopedLocalID   string               `xml:"VAppScopedLocalId,omitempty"`   // If Source references a Vm, this value provides a unique identifier for the Vm in the scope of the composed vApp.
	InstantiationParams *InstantiationParams `xml:"InstantiationParams,omitempty"` // If Source references a Vm this can include any of the following OVF sections: VirtualHardwareSection OperatingSystemSection NetworkConnectionSection GuestCustomizationSection.
	NetworkAssignment   *NetworkAssignment   `xml:"NetworkAssignment,omitempty"`   // If Source references a Vm, this element maps a network name specified in the Vm to the network name of a vApp network defined in the composed vApp.
	StorageProfile      *Reference           `xml:"StorageProfile,omitempty"`      // If Source references a Vm, this element contains a reference to a storage profile to be used for the Vm. The specified storage profile must exist in the organization vDC that contains the composed vApp. If not specified, the default storage profile for the vDC is used.
	LocalityParams      *LocalityParams      `xml:"LocalityParams,omitempty"`      // Represents locality parameters. Locality parameters provide a hint that may help the placement engine optimize placement of a VM and an independent a Disk so that the VM can make efficient use of the disk.
}
```

This means if StorageProfile is nil, it won't be Marshalled into the XML, so there is no need to go and find the Default Profile in `resource_vcd_vapp.go`

```
default_storage_profile, err := vcdClient.OrgVdc.GetDefaultStorageProfileReference(storage_profiles.Results)
			if err != nil {
				return fmt.Errorf("Couldn't find storage_profile and no default storage_profile avaiable %s", err)
			}

			// Override default_storage_profile if we find the given storage profile
			if d.Get("storage_profile").(string) != "" {
				storage_profile_reference, err = vcdClient.OrgVdc.FindStorageProfileReference(d.Get("storage_profile").(string))
				if err != nil {
					storage_profile_reference = default_storage_profile
					log.Printf("Using default storage_profile: %s", storage_profile_reference)
				}
			} else {
				storage_profile_reference = default_storage_profile
			}
```

Do you agree? Be great to have a sanity check of my logic before we fix this :)

Cheers

**Comment by dn1s** [comment]
I'll check it later that day.

**Comment by dn1s** [comment]
@bobbydeveaux 

If I try this
```
storage_profile_reference := nil

// Override default_storage_profile if we find the given storage profile
if d.Get("storage_profile").(string) != "" {
	storage_profile_reference, err = vcdClient.OrgVdc.FindStorageProfileReference(d.Get("storage_profile").(string))
	if err != nil {
		log.Printf("Error assigning custom storage profile. Using default storage_profile.")
	}
} 
```
I get compile errors:
```
==> Checking that code complies with gofmt requirements...
go install
# github.com/terraform-providers/terraform-provider-vcd/vcd
vcd/resource_vcd_vapp.go:121: use of untyped nil
make: *** [GNUmakefile:7: build] Error 2
```
And if I try to use an empty types.Reference{} it fails to create a vapp due to this restriction:
```
type Reference struct {
	HREF string `xml:"href,attr"`
	ID   string `xml:"id,attr,omitempty"`
	Type string `xml:"type,attr,omitempty"`
	Name string `xml:"name,attr,omitempty"`
}
```
HREF for types.Reference structs can't be empty.

**Comment by bobbydeveaux** [comment]
@dn1s  @Boran  - believe I have a fix for this here:

https://github.com/terraform-providers/terraform-provider-vcd/pull/43

Works for me anyway.. :)

Are you both able to scan your eyes over it to see if it makes sense? If so I can get it merged it and will try and arrange a provider release too!

**Comment by dn1s** [comment]
@bobbydeveaux tested your changes works for me. Without specifying a storage profile and with specifying one, both times it worked.

**Comment by Boran** [comment]
Hi, I'm away on a holiday and will not be able to test/verify from my side. Sorry.

Sean

**Comment by bobbydeveaux** [comment]
@Boran @dn1s  - merged into master. Will arrange release of provider.
