### ISSUE TITLE
vCD URI Issue: invalid URI for request!!

### ISSUE THREAD

**Issue by Vikas-Little** [terraform-providers/terraform-provider-vcd#392]
Hi there,

We’re encountering a challenge in provisioning infra using code through terraform tool (Terraform v0.12.9) in VMware vCloud Director (v9.5). We’re trying this for the first time.

vCD URL: https://clientportal.nxtgen.com/cloud/org/nxtgen_presales/

As per the instructions on Github, we're using the below mentioned URL-

https://clientportal.nxtgen.com/api

Error: something went wrong while retrieving URL: parse $ {var.vcd_url}: invalid URI for request

For your reference, the content of main.tf is as follows:

# VMware vCloud Director Provider Variables (Blank)
variable "vcd_allow_unverified_ssl" {
   description = "Enable or Disable SSL Certificate Verification"
}
variable "vcd_org" {
   description = "vCD Tenant Org"
}
variable "vcd_pass" {
   description = "vCD Tenant Password"
}
variable "vcd_url" {
   description = "vCD Tenant URL"
}
variable "vcd_user" {
   description = "vCD Tenant User"
}
variable "vcd_vdc" {
   description = "vCD Tenant VDC"
}

# VMware vCloud Director Provider Configuration
provider "vcd" {
   allow_unverified_ssl = "${var.vcd_allow_unverified_ssl}"
   org = "$ {var.vcd_org}"
   password = "$ {var.vcd_pass}"
   url = "$ {var.vcd_url}"
   user = "$ {var.vcd_user}"
   vdc = "$ {var.vcd_vdc}"
}

resource "vcd_network_routed" "net" {
   name         = "my-net"
   edge_gateway = "presales_EDGE"
   gateway      = "10.10.0.1"

   static_ip_pool {
     start_address = "10.10.0.152"
     end_address   = "10.10.0.254"
  }
}

**Please suggest the solution!**

**Comment by Didainius** [comment]
Hello @Vikas-Little,
Could you enable logging:
export TF_LOG=trace and also enable logging using https://www.terraform.io/docs/providers/vcd/index.html#logging

Then try `terraform plan` or `terraform apply` and it should result in two log files being present in the directory. Double check that there are no credentials (or any other things you want to obfuscate) and share it with us.

Thanks!

**Comment by Vikas-Little** [comment]
Hi Didainius,

Thanks for the quick response.

The go-vcloud-director.log file is attached for your reference.

[go-vcloud-director.log](https://github.com/terraform-providers/terraform-provider-vcd/files/3835055/go-vcloud-director.log)

The updated content of main.tf file is as follows:

# VMware vCloud Director Provider Variables (Blank)
variable "vcd_allow_unverified_ssl" {
   description = "Disable SSL Certificate Verification? (true/false)"
}
variable "vcd_logging" {
   description = "Enable logging? (true/false)"
}
variable "vcd_org" {
   description = "vCD Tenant Org?"
}
variable "vcd_pass" {
   description = "vCD Tenant Password?"
}
variable "vcd_url" {
   description = "vCD Tenant URL?"
}
variable "vcd_user" {
   description = "vCD Tenant User?"
}
variable "vcd_vdc" {
   description = "vCD Tenant VDC?"
}

# VMware vCloud Director Provider Configuration
provider "vcd" {
   allow_unverified_ssl = "${var.vcd_allow_unverified_ssl}"
   logging = "${var.vcd_logging}"
   org = "$ {var.vcd_org}"
   password = "$ {var.vcd_pass}"
   url = "$ {var.vcd_url}"
   user = "$ {var.vcd_user}"
   vdc = "$ {var.vcd_vdc}"
}

resource "vcd_network_routed" "net" {
   name         = "my-net"
   edge_gateway = "presales_EDGE"
   gateway      = "10.10.0.1"

   static_ip_pool {
     start_address = "10.10.0.152"
     end_address   = "10.10.0.254"
  }
}

Please suggest where are we going wrong?

**Comment by Didainius** [comment]
I think you have incorrect definition. Please note there should not be extra spaces when using vars. It shold be `url = "${var.vcd_url}"` instead of `url = "$ {var.vcd_url}"`


Here's the definition you have (just formatting applied):

```hcl
provider "vcd" {
  allow_unverified_ssl = "${var.vcd_allow_unverified_ssl}"
  logging              = "${var.vcd_logging}"
  org                  = "$ {var.vcd_org}"
  password             = "$ {var.vcd_pass}"
  url                  = "$ {var.vcd_url}"
  user                 = "$ {var.vcd_user}"
  vdc                  = "$ {var.vcd_vdc}"
}

resource "vcd_network_routed" "net" {
  name         = "my-net"
  edge_gateway = "presales_EDGE"
  gateway      = "10.10.0.1"

  static_ip_pool {
    start_address = "10.10.0.152"
    end_address   = "10.10.0.254"
  }
}
```

It should be (not how using variables does not have extraneus spaces after `$` sign):
```hcl
provider "vcd" {
  allow_unverified_ssl = "${var.vcd_allow_unverified_ssl}"
  logging              = "${var.vcd_logging}"
  org                  = "${var.vcd_org}"
  password             = "${var.vcd_pass}"
  url                  = "${var.vcd_url}"
  user                 = "${var.vcd_user}"
  vdc                  = "${var.vcd_vdc}"
}

resource "vcd_network_routed" "net" {
  name         = "my-net"
  edge_gateway = "presales_EDGE"
  gateway      = "10.10.0.1"

  static_ip_pool {
    start_address = "10.10.0.152"
    end_address   = "10.10.0.254"
  }
}
```

**Comment by Vikas-Little** [comment]
Hi Didainius,

First of all, thanks a lot for the valuable advice as it worked.

However, when I'm applying the generated execution plan, I'm facing a new error.

The details are as follows:

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # vcd_network_routed.net will be created
  + resource "vcd_network_routed" "net" {
      + dns1         = "8.8.8.8"
      + dns2         = "8.8.4.4"
      + edge_gateway = "presales_EDGE"
      + gateway      = "10.10.0.1"
      + href         = (known after apply)
      + id           = (known after apply)
      + name         = "my-net"
      + netmask      = "255.255.255.0"
      + shared       = false

      + static_ip_pool {
          + end_address   = "10.10.0.254"
          + start_address = "10.10.0.152"
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

vcd_network_routed.net: Creating...

Error: error: &errors.errorString{s:"error creating the network: error instantiating a new OrgVDCNetwork: API Error: 500: [ 569a9d75-ed3e-45e5-b5d6-62521f1cbd48 ] Unable to perform this action. Contact your cloud administrator."}

  on main.tf line 35, in resource "vcd_network_routed" "net":
  35: resource "vcd_network_routed" "net" {

The go-vcloud-director.log file is attached for your reference.
[go-vcloud-director.log](https://github.com/terraform-providers/terraform-provider-vcd/files/3835721/go-vcloud-director.log)

Please suggest where am I again going wrong?

Since I'm pretty new to terraform, I would require your help to execute my first task successfully.

**Comment by Didainius** [comment]
This errors comes directly from vCD so this needs some more troubleshooting. What is your users role in the organization?

**Comment by Vikas-Little** [comment]
Hi Didainius,

The issue wasn't with "User Role" but instead it was some internal issue which has been resolved by sys admin.

Finally, I was successful in creating an Org VDC routed network by running code through terraform tool.

Thanks to you & your team from my side!!
