### ISSUE TITLE
How do I use VCD_CACHE

### ISSUE THREAD

**Issue by buec011** [terraform-providers/terraform-provider-vcd#405]
`VCD_CACHE` is mentioned in the documentation: 
`There is a cache engine, disabled by default, which can be activated by the VCD_CACHE environment variable.`

Is VCD_CACHE a boolean and I set 
`VCD_CACHE=true`
or is it a path to a cache file, e.g.
VCD_CACHE=/tmp/vcdcache

**Comment by dataclouder** [comment]
It's a Boolean.
Setting the variable to a non-empty string will enable it.

It is useful only with applications that run terraform-plugin-vcd for long time.
How does it work? 
When cache is active, a connection is kept in memory and reused every time there is a request for a provider. The usefulness of this cache is noticeable when running the test suite, as a new provider is instantiated for every test.

For application like the Terraform client, it is probably not worth using.
It won't hurt either, though. You may try benchmarking, but unless you are running the whole test suite, you may not see much difference.

**Comment by buec011** [comment]
Ok,
assume I have two terraform projects, for ORG1 and ORG2.
One admin runs terraform for ORG1 and another admin runs a second process for ORG2 (both on the same client).
They are using different credentials.
Does every process have his own cache or does this scenario has a conflict if both use VCD_CACHE=true?

**Comment by dataclouder** [comment]
The cache is hashed by credentials. Different credentials=different caches.
And besides, if there are two processes using it, there will be two different caches, even if they use the same credentials. It's all in memory: nothing is shared to other processes.

**Comment by buec011** [comment]
Understood.
