### ISSUE TITLE
vcd_vapp_vm: Adding a secondary network interface also changes the first interface

### ISSUE THREAD

**Issue by NilsBusche** [terraform-providers/terraform-provider-vcd#407]
### Terraform Version
Terraform v0.12.15
terraform-provider-vcd_v2.5.0_x4

### Affected Resource(s)
vcd_vapp_vm

### Terraform Configuration Files
```hcl
resource "vcd_vapp_vm" "instance" {
  name          = var.hostname
  computer_name = var.hostname
  vapp_name     = vcd_vapp.vapp.name
  catalog_name  = var.image_catalog
  template_name = var.image_string
  cpus          = var.cpu
  cpu_cores     = var.core
  memory        = var.ram

  network {
    type               = "org"
    name               = var.network
    ip_allocation_mode = "POOL"
    is_primary         = true
  }
}
```

### Expected Behavior
If we add a new `network` block, terraform should attach a new interface to the vm. The current first interface should not be changed.

### Actual Behavior
If we add a new `network` block, terraform also redeploys the first interface. It gets a new IP address and also a new MAC address.

### Steps to Reproduce
Roll out the configuration above.

Look into terraform.tfstate:
```hcl
[...]
            "network": [
              {
                "ip": "10.70.21.8",
                "ip_allocation_mode": "POOL",
                "is_primary": true,
                "mac": "00:50:56:0b:02:5f",
                "name": "XXX",
                "type": "org"
              }
            ],
[...]
```
Add the following to the configuration in the `vcd_vapp_vm` resource:
```hcl
  network {
    type               = "org"
    name               = var.network
    ip_allocation_mode = "POOL"
  }
```
Run `terraform apply` (it says that it only will add a new interface):
```hcl
[...]
        network {
            ip                 = "10.70.21.8"
            ip_allocation_mode = "POOL"
            is_primary         = true
            mac                = "00:50:56:0b:02:5f"
            name               = "XXX"
            type               = "org"
        }
      + network {
          + ip_allocation_mode = "POOL"
          + name               = "XXX"
          + type               = "org"
        }
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```
Look into the terraform.tfstate:
```hcl
[...]
            "network": [
              {
                "ip": "10.70.21.9",
                "ip_allocation_mode": "POOL",
                "is_primary": true,
                "mac": "00:50:56:0b:02:60",
                "name": "XXX",
                "type": "org"
              },
              {
                "ip": "10.70.21.10",
                "ip_allocation_mode": "POOL",
                "is_primary": false,
                "mac": "00:50:56:0b:02:61",
                "name": "XXX",
                "type": "org"
              }
            ],
[...]
```
Also the IP and MAC of the first interface have changed.

**Comment by Didainius** [comment]
Thanks. I will have a look at it

**Comment by NilsBusche** [comment]
Thanks for the quick response!

As additional information:
Same occurs if you want to add a third interface. In this case the first and secondary will be recreated, too.

**Comment by Didainius** [comment]
Thanks. I will just link #327 here as well as these are very close to each other internally and it may be worth to tackle them together.

**Comment by Didainius** [comment]
@NilsBusche ,
Would you be able to build and test provider from pull request https://github.com/terraform-providers/terraform-provider-vcd/pull/438
This should have the fix for your problem.
