### ISSUE TITLE
vcd_vapp_vm.name.id points to servername instead of vcd vm id

### ISSUE THREAD

**Issue by buec011** [terraform-providers/terraform-provider-vcd#410]
### Affected Resource(s)
- vcd_vapp_vm

### Terraform Configuration Files
```hcl
resource "vcd_vapp_vm" "instance" {
  lifecycle {
    prevent_destroy = "true"
  }

  name          = var.hostname
  vapp_name     = vcd_vapp.vapp.name
  catalog_name  = var.image_catalog
  template_name = var.image_string
  cpus          = var.cpu
  cpu_cores     = var.core
  memory        = var.ram
  power_on      = "false"

  network {
    type               = "org"
    name               = var.network
    ip_allocation_mode = "POOL"
    is_primary         = true
  }
}
output "instance_id" {
  value = vcd_vapp_vm.instance.id
}
```

### Expected Behavior
`vcd_vapp_vm.instance.id` shows the VCD VM id, e.g.
 `urn:vcloud:vm:123456-c39e-4305-bb5e-4562a184817c`
or
 `vm-123456-c39e-4305-bb5e-4562a184817c`

### Actual Behavior
`vcd_vapp_vm.instance.id` shows the servername

### Steps to Reproduce
1. Fill variables for HCL above with valid values
2. `terraform apply`

**Comment by buec011** [comment]
If you do not want to break something for current user, a new attribute like `vcd_vapp_vm.instance.vcdid`would be sufficient

**Comment by buec011** [comment]
IMHO: Maybe it is a good idea to use vcd ids and not name in general. Example: Maybe two servername with the same name exits (e.g. temporary for migration, e.g. in some cases for SAP migration needed)

**Comment by dataclouder** [comment]
Hi. Thanks for reporting an issue.
Which version of the provider are you using?

**Comment by dataclouder** [comment]
Using version 2.6.0 (not yet released, but you can compile it on your own), you get the ID as expected.

**Comment by buec011** [comment]
Hi,
we are using 2.5.0 in production

**Comment by buec011** [comment]
> Using version 2.6.0 (not yet released, but you can compile it on your own), you get the ID as expected.

Oh. Confirmed with 
`terraform-provider-vcd_v2.6.0-cfd72e7c576cf94d897a2d932d7ea11e89a0af51`
