### ISSUE TITLE
Failure to create vcd_vapp_vm if vApp is empty.

### ISSUE THREAD

**Issue by rejanu** [terraform-providers/terraform-provider-vcd#413]
### Terraform Version
Terraform v0.12.16
+ provider.vcd v2.5.0

### Affected Resource(s)
- vcd_vapp_vm

### Panic Output
`Error: [VM creation] error adding VM: vApp Template must have at least one child VM`

### Expected Behavior
vcd_vapp_vm resource being created

### Actual Behavior
The implicit inclusion of one VM in a vApp is Deprecated in 2.5, however it is required that [at least one vm](https://github.com/vmware/go-vcloud-director/blob/master/govcd/vapp.go#L161) exists in the vapp template when creating `vcd_vapp_vm`. Which means it is impossible to create an empty vapp and add a vm to it.

### Example
https://gist.github.com/rejanu/97f66c485ec6114e7a39bfcad126cbe2

### Steps to Reproduce
1. `terraform plan`
2. `terraform apply`

**Comment by vbauzysvmware** [comment]
Hi @rejanu. For empty vApp you don't need any template. 
For e.g.

```
resource "vcd_vapp" "Vapp1" {
  name = "TestVapp1"
  org  = "myOrg"
  vdc  = "myVdc"
}
```
