### ISSUE TITLE
Add support for Flex allocation model in vcd_org_vdc resource

### ISSUE THREAD

**Issue by nilic** [terraform-providers/terraform-provider-vcd#423]
Since vCloud Director 9.7, a new "Flex" allocation model is available when creating Org vDC through HTML5 admin portal and API. Flex allocation model supports all allocation configurations that are available in the other three allocation models.

It would be great if Terraform vCD provider would allow for creating Flex Org vDCs (if API >= 32.0), since most of the input arguments for Flex vDC are already a part of the `vcd_org_vdc` resource (CPU and memory allocations and reservations, vCPU limit etc). Flex Org vDC basically allows for combining all of these inputs freely and brings two new configurable options:

- Elasticity
- whether to use Org vDC resources for VM memory overhead.

Here are a few screenshots from the UI:

![image](https://user-images.githubusercontent.com/6827325/70909771-72732080-200e-11ea-8b00-a116bd1a3e46.png)

![image](https://user-images.githubusercontent.com/6827325/70909817-90d91c00-200e-11ea-8f32-28cafd5cf446.png)

![image](https://user-images.githubusercontent.com/6827325/70909847-a3535580-200e-11ea-9976-10aef33992a8.png)

### Affected Resource(s)
- vcd_org_vdc

### References
[https://docs.vmware.com/en/vCloud-Director/9.7/com.vmware.vcloud.spportal.doc/GUID-4F67C95E-4278-4150-94A6-D37D0AF398CC.html](url)

[https://docs.vmware.com/en/vCloud-Director/9.7/com.vmware.vcloud.spportal.doc/GUID-BE4CD03D-0644-4E12-81D7-74FABFF9D7A9.html](url)

**Comment by vbauzysvmware** [comment]
Released with 2.7 version
