### ISSUE TITLE
VM guest customization force=false crashes with interface {} is nil 

### ISSUE THREAD

**Issue by rhysjtevans** [terraform-providers/terraform-provider-vcd#427]
Hi folks, trying to deploy a VM to a vapp and terraform crashes on this line with the error below.

https://github.com/terraform-providers/terraform-provider-vcd/blob/759be139ecfadaf78198876d0392530d50f40391/vcd/resource_vcd_vapp_vm.go#L1343

Here's config

> resource "vcd_vapp_vm" "k8s-masters" {
  count         = var.k8s_master_count
  vapp_name     = var.vapp_name
  name          = "centos-7-test"
  computer_name = "centos-7-test"
  catalog_name  = var.catalog_name
  template_name = var.template_name
  memory        = 4096
  cpus          = 8
  cpu_cores     = 2
customization {
    force = false
  }
network {
    type               = "org"
    name               = var.network_name
    ip_allocation_mode = "POOL"
    is_primary         = true
  }
}
terraform versions: 
Terraform v0.12.18
+ provider.random v2.2.1
+ provider.vcd v2.6.0

> 2020-01-08T22:04:59.617Z [DEBUG] plugin.terraform-provider-vcd_v2.6.0_x4: github.com/terraform-providers/terraform-provider-vcd/vcd.isForcedCustomization(...)
2020-01-08T22:04:59.617Z [DEBUG] plugin.terraform-provider-vcd_v2.6.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-vcd/vcd/resource_vcd_vapp_vm.go:1343

Any thoughts?

**Comment by Didainius** [comment]
Hi @rhysjtevans, 
Thanks for the issue. Could you try to remove the `customization` block?
```
customization {
  force = false
}
```

Skipping it will be the same as setting to `false`.

**Comment by rhysjtevans** [comment]
Hi @Didainius 

customisation force = True - I get an issue with the vcloud web API (Looking into that separately)
customisation force = False - throws the error
No customization  - applies successfully but "Guest Customisation" is not enabled so the IP address from the IP pool in vcloud isn't applied to the guest machine.

**Comment by Didainius** [comment]
Thanks for the info - curious what errors happens when you try to enable customization.
Also - what is the guest OS you are using? Is it some public image or a private one?

It may be that the guest OS itself doesn't support getting the IPs. For example I tested with Photon OS - even when guest customization is not set - it still gets the POOL allocated IP.

**Comment by rhysjtevans** [comment]
packer virtualbox built Centos 7. Not much configuration. Based on https://github.com/geerlingguy/packer-boxes/tree/master/centos7
I think it could be a problem with the converted ova to get it working on vcloud. It appears as "other os" so fixing that and will try again.

Oh that's odd/interesting. I enabled Guest Customisation through the webui and it worked. I'll try that out.

**Comment by Didainius** [comment]
> Oh that's odd/interesting. I enabled Guest Customisation through the webui and it worked. I'll try that out.

That is interesting. Would be interested if you dig out what is wrong/different there. Maybe there is a bug/different in forcing customization although we usually try to clone UI behavior.

**Comment by Didainius** [comment]
@rhysjtevans,
You could try to build the provider from my branch where I have fix for the crash (when force=false):
https://github.com/Didainius/terraform-provider-vcd/tree/fix-customization

The process should be something like:
```shell
# git clone https://github.com/Didainius/terraform-provider-vcd
# cd terraform-provider-vcd/
# git checkout  fix-customization
# make install                                    # you must have Go compiler installed
==> Checking that code complies with gofmt requirements...
go install
/Users/xxx/go/bin/terraform-provider-vcd -> /Users/xxx/.terraform.d/plugins//terraform-provider-vcd_v2.6.0
Installed
total 127536
-rwxr-xr-x  1 xxx  32694820 Jan 11 09:00 terraform-provider-vcd_v2.6.0
```

Then you will have to do `terraform  init` once more.

**Comment by rhysjtevans** [comment]
No worries, will give it a go

**Comment by rhysjtevans** [comment]
Looks like that works 👍

**Comment by Didainius** [comment]
@rhysjtevans,
Cool - were you able to solve your customization problem?

**Comment by rhysjtevans** [comment]
Not yet. I've tried swapping to CoreOS based on your photonos comment, but vcloud isn't assigning the IP (from an IP Pool) and the guest machine assigning it to the NIC. Any thoughts?

**Comment by vbauzysvmware** [comment]
> Not yet. I've tried swapping to CoreOS based on your photonos comment, but vcloud isn't assigning the IP (from an IP Pool) and the guest machine assigning it to the NIC. Any thoughts?

Hi @rhysjtevans ,
Are vmware tools installed in VM you try?

**Comment by rhysjtevans** [comment]
Yeah, well technically open-vm-tools

**Comment by Didainius** [comment]
@rhysjtevans,

I just tested such config on `2.6` with an image named `photon-hw11-3.0-26156e2.ova` (can be dowloaded [here](http://dl.bintray.com/vmware/photon/3.0/GA/ova/photon-hw11-3.0-26156e2.ova)) and the IP address is everywhere after first `apply` run - statefile, vCD and even on VM itself (see below screenshots)

```
resource "vcd_vapp_vm" "test-vm" {
  org = "my-org"
  vdc = "my-org-vdc"

  vapp_name     = vcd_vapp.test-vapp.name
  name          = "TestAccVcdVAppVmUpdateCustomizationVM"
  catalog_name  = "my-catalog"
  template_name = "photon-os"
  memory        = 512
  cpus          = 2
  cpu_cores     = 1

  network {
    type               = "vapp"
    name               = vcd_vapp_network.vappNet.name
    ip_allocation_mode = "POOL"
  }
}

```

statefile extract:
```
           "description": "photon-os-description",
            "disk": [],
            "expose_hardware_virtualization": false,
            "guest_properties": null,
            "href": "https://192.168.1.109/api/vApp/vm-07687186-d70b-4a7a-8fa1-a77052ec7938",
            "id": "urn:vcloud:vm:07687186-d70b-4a7a-8fa1-a77052ec7938",
            "initscript": null,
            "ip": null,
            "mac": null,
            "memory": 512,
            "metadata": null,
            "name": "TestAccVcdVAppVmUpdateCustomizationVM",
            "network": [
              {
                "ip": "192.168.2.51",
                "ip_allocation_mode": "POOL",
                "is_primary": true,
                "mac": "00:50:56:01:31:3f",
                "name": "vapp-net",
                "type": "vapp"
              }
            ],
            "network_href": null,
            "network_name": null,
            "org": "my-org",
            "power_on": true,
            "storage_profile": "Development",
            "template_name": "photon-os",
            "vapp_name": "TestAccVcdVAppVmUpdateCustomization",
            "vapp_network_name": null,
            "vdc": "my-org-vdc"
          },
```


<img width="617" alt="image" src="https://user-images.githubusercontent.com/15804230/73538561-01f45780-4434-11ea-9f8b-23eb03777e31.png">

<img width="508" alt="image" src="https://user-images.githubusercontent.com/15804230/73538589-1173a080-4434-11ea-829b-4c5d5efe8a18.png">

**Comment by rhysjtevans** [comment]
Oh awesome! Thanks for the help @Didainius I will give that a go.

**Comment by lvirbalas** [comment]
@rhysjtevans How was it? It would be great to hear your feedback. If we decide to merge to master, it's better to do it sooner than later. Thanks!!

**Comment by rhysjtevans** [comment]
Sorry @Didainius  @lvirbalas you can merge, all worked fine as stated above. The latter is not related - just appreciated the help 👍

**Comment by Didainius** [comment]
Thanks for update, @rhysjtevans . We’ll aim this bugfix for master.

**Comment by Didainius** [comment]
#462 includes the fix and should solve it.
