### ISSUE TITLE
bus number and unit number disappear after frefresh

### ISSUE THREAD

**Issue by dataclouder** [terraform-providers/terraform-provider-vcd#429]
After a successful deployment of a VM with independent disks, if we run `terraform refresh`, the  bus information disappear.
```
vm = {
//... 
  "disk" = [
    {
      "bus_number" = "1"
      "name" = "TestAccVcdIndependentDiskBasic"
      "unit_number" = "0"
    },
  ]
// more ...
```

After refresh, the same section is shown as:
```
    {
      "bus_number" = ""
      "name" = "TestAccVcdIndependentDiskBasic"
      "unit_number" = ""
    }
```

To reproduce, run the test in `vcd.TestAccVcdVAppVm_Basic.tf` after running `make test-binary-prepare`, pause after apply, check terraform state, and run refresh.

**Comment by lvirbalas** [comment]
I confirm that this is very easy to reproduce. You actually see bus_number and unit_number only after the first apply.
```
Apply complete! Resources: 0 added, 1 changed, 0 destroyed.

Outputs:

disk = [
  {
    "bus_number" = "1"
    "name" = "demo-disk"
    "unit_number" = "0"
  },
]
```
If you run apply one more time, these field values are lost:
```
Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

disk = [
  {
    "bus_number" = ""
    "name" = "demo-disk"
    "unit_number" = ""
  },
]
```

Also, to be consistent with a similar `internal_disk` structure and UI representation what about adding the size field?

**Comment by vbauzysvmware** [comment]
Fixed
