### ISSUE TITLE
Terraform : How to use catalog name while creating VM

### ISSUE THREAD

**Issue by irfanjs** [terraform-providers/terraform-provider-vcd#435]
Hi,
I am trying to create the VM in VmWare Vcloud data center using terraform VCD provider. here is the entire code for that

**what i have done**

```
provider "vcd" {
  user                 = "abc"
  password             = "xyz"
  org                  = "I1250-Se"
  vdc                  = "I1250-Se"
  url                  = "https://nlu02.abc.com/api"
  max_retry_timeout    = "30"
  allow_unverified_ssl = "true"
}

resource "vcd_vapp" "web" {
  name = "web"
  power_on = "true"
}

data "vcd_vapp" "web" {
  name             = "web"
  org              = "I1250-Se"
}

data "vcd_catalog_item" "my-cat-item" {
  org  = "I1250-Se"
  name = data.vcd_catalog.my-cat.name
  catalog = data.vcd_catalog.my-cat.name
}

data "vcd_catalog" "my-cat" {
  org  = ""
  name = "ID120_ISO"
}


resource "vcd_vapp_vm" "web1" {
  vapp_name     = data.vcd_vapp.web.name
  name          = var.vmname
  catalog_name  = "ID120_ISO"
  template_name = ""
  memory        = 2048
  cpus          = 2
  cpu_cores     = 1
}

```
**what is the error**

> vcd_vapp_vm.web1: Creating...
> 
> Error: error finding catalog: [ENF] entity not found
> 
> on main.tf line 33, in resource "vcd_vapp_vm" "web1": 33: resource "vcd_vapp_vm" "web1" {
> 

**environment**

Terraform v0.12.18

**OS :**

Linux jenvm 4.4.0-142-generic #168-Ubuntu SMP Wed Jan 16 21:00:45 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**what is expected**

the script should accept the catalog name (which is already exist) and create the VM. I have verified that , catalog name does exist , but , still it says "not found, dont know why" . Another point to be noted is that , the catalog name which i am referring does not contain any VApp template, so not sure how it will behave. what i am expecting is , it should accept the catalog name and use the media (ISO image) to install the OS on the newly created VM through terraform.

please suggest. Thanks

**Comment by dataclouder** [comment]
The org name is missing in the catalog data source.
Also, in the data item data source, you are putting the catalog name as the item name.
That could happen , but is this your intention?

I also notice that the org and vdc have the same name (again, it can happen, but double check it) and that the vApp template field is empty (it should contain the name of the catalog item.

``` hcl
data "vcd_catalog" "my-cat" {
  org  = ""                //  << missing org name here
  name = "ID120_ISO"
}
```

**Comment by dataclouder** [comment]
I just noticed your remark about the catalog being empty.
The reason we have a catalog item for the VM is because we need to find the vapp-template. If the catalog is empty, that won't work. 
You need a vApp template, which is taken from a catalog. A media item can't be used with the current code

**Comment by vbauzysvmware** [comment]
Also would like to note - to install from ISO you have use vcd_inserted_media. Which will insert ISO file to VM cd-rom. As result you can boot from ISO filo.

**Comment by irfanjs** [comment]
thanks for your responses. appreciate it !.

here is modified code : 

```
provider "vcd" {
  user                 = ""
  password             = ""
  token                = "b1e6c2080ddf484cbfaae25e086116be"
  org                  = "ID4250-Sent"
  vdc                  = "ID4250-Sent"
  url                  = "https://nl9u102.abc.com/api"
  max_retry_timeout    = "30"
  allow_unverified_ssl = "true"
}

resource "vcd_vapp" "web" {
  name = "web"
  power_on = "true"
}

data "vcd_vapp" "web" {
  name             = "web"
  org              = "ID4250-Sent"
}

data "vcd_catalog" "my-cat" {
  org  = "ID4250-Sent"
  name = "ID14250_ISO"
}
resource "vcd_vapp_vm" "web1" {
  vapp_name     = data.vcd_vapp.web.name
  name          = var.vmname
  catalog_name  = "ID14250_ISO"
  template_name = ""
  memory        = 2048
  cpus          = 2
  cpu_cores     = 1
}

```

**here is the output of command : terraform apply** 

> root@jen:~/terraform# terraform apply
> data.vcd_vapp.web: Refreshing state...
> data.vcd_catalog.my-cat: Refreshing state...
> vcd_vapp.web: Refreshing state... [id=urn:vcloud:vapp:451de414-04c9-44e1-a3e6-185b6ef34466]
> 
> An execution plan has been generated and is shown below.
> Resource actions are indicated with the following symbols:
>   + create
> 
> Terraform will perform the following actions:
> 
>   # vcd_vapp_vm.web1 will be created
>   + resource "vcd_vapp_vm" "web1" {
>       + accept_all_eulas               = true
>       + catalog_name                   = "ID14250_ISO"
>       + computer_name                  = (known after apply)
>       + cpu_cores                      = 1
>       + cpus                           = 2
>       + description                    = (known after apply)
>       + expose_hardware_virtualization = false
>       + href                           = (known after apply)
>       + id                             = (known after apply)
>       + ip                             = (known after apply)
>       + mac                            = (known after apply)
>       + memory                         = 2048
>       + name                           = "web1"
>       + power_on                       = true
>       + storage_profile                = (known after apply)
>       + vapp_name                      = "web"
>     }
> 
> Plan: 1 to add, 0 to change, 0 to destroy.
> 
> Do you want to perform these actions?
>   Terraform will perform the actions described above.
>   Only 'yes' will be accepted to approve.
> 
>   Enter a value: yes
> 
> vcd_vapp_vm.web1: Creating...
> 
> Error: error finding catalog item: [ENF] entity not found
> 
>   on main.tf line 28, in resource "vcd_vapp_vm" "web1":
>   28: resource "vcd_vapp_vm" "web1" {
> 

**things which are there in my VCD.  (i double checked)**

1: ORG and VDC names are same.
2: catalog is not empty , if you see the above code, i have mentioned now correct catalog name. I am still not sure what is mean by catalog item ??
3: the catalog name which i am using above , does not have any VApp template. VApp template is mandatory ? , if yes, i have to create one ? is there any workaround to bypass vapp template and directly access media using catalog ? 

Pls suggest. Thanks.

**Comment by vbauzysvmware** [comment]
Hi @irfanjs 

Current provider implementation doesn't provide ability to create VM without `template_name`. We have such feature request in backlog (https://github.com/terraform-providers/terraform-provider-vcd/issues/85).
For your script to work you need valid vAPP template(OVA file) uploaded in configured catalog.
You can't use ISO file as template, ISO is used as Media files - with provider resource `vcd_inserted_media`.

**Comment by irfanjs** [comment]
thanks . will have a look
