### ISSUE TITLE
New IP Network function cidrnet(ip_address, netmask)

### ISSUE THREAD

**Issue by carmineesposito73** [terraform-providers/terraform-provider-vcd#437]
This is an enhancement request: a function like the following can be useful:
```
> cidrnet("10.10.10.10", "255.255.255.0")
10.10.10.0/24
> cidrnet("192.168.0.200", "255.255.255.128")
192.168.0.128/25
```
same result as:
```
$ ipcalc 192.168.0.200/255.255.255.128 | grep Network | awk '{ print $2 }'
192.168.0.128/25
```
this function is like to have a reverse for:
```
> cidrhost("192.168.0.200/25", 0)
192.168.0.128
> cidrnetmask("192.168.0.200/25")
255.255.255.128
```
also a simpler function:
```
> cidrbitmask("255.255.255.0")
24
> cidrbitmask("255.255.192.0")
18
```

**Comment by Didainius** [comment]
Hi @carmineesposito73,
I am afraid this should go to Terraform core itself to add to already existing functions (https://www.terraform.io/docs/configuration/functions/cidrhost.html), not to a particular provider.

**Comment by carmineesposito73** [comment]
I will open an issue on terraform core, thanks

**Comment by Didainius** [comment]
> I will open an issue on terraform core, thanks

Thanks. Feel free to put a reference here as well. I do know why you need it and would like it myself :)

**Comment by carmineesposito73** [comment]
I'm working on something like that:
I want to assign to a VM_N the Nth ip address of a subnet, I can use datasource to get information on the network like this
```
    "gateway" = "172.16.1.1"
    "netmask" = "255.255.255.0"
```
but the terraform cidrhost function requires a cidr subnet
```
cidrhost("172.16.1.0/24", N)
```

**Comment by carmineesposito73** [comment]
This is my open issue https://github.com/hashicorp/terraform/issues/23905 but seems that nobody cares :-(

**Comment by carmineesposito73** [comment]
I've got a negative answer
https://github.com/hashicorp/terraform/issues/23905#issuecomment-777155511
