### ISSUE TITLE
resource vcd_vApp_network doesn't support import

### ISSUE THREAD

**Issue by danonh** [terraform-providers/terraform-provider-vcd#447]
Hi,
I'm trying to find workaround for ability to link vApp network with externally routed one as this functionalilty is not currently available through vcd provider. 
I can provision empty vApp with all network settings through powercli successfully. Then I need to import vApp and networks created through powercli into Terraform to manage those resources. I can import vApp into Terraform as it supports import, but cannot import vApp network into it and I'm stuck. Any way to import vApp network into Terraform? If not can you estimate when native support for externally routed networks for vApp networks will be implemented into vcd provider? Best regards,

**Comment by vbauzysvmware** [comment]
Hi @danonh, I started to work on all missing functionality for vapp network. So bear with us.

**Comment by vbauzysvmware** [comment]
Added with  #455. Will be in next release.
