### ISSUE TITLE
vApp lock while creating vcd_vapp_vm

### ISSUE THREAD

**Issue by iamspector** [terraform-providers/terraform-provider-vcd#457]
### Terraform Version
Terraform v0.12.20
+ provider.template v2.1.2
+ provider.vcd v2.6.0

### Affected Resource(s)
- vcd_vapp
- vcd_vapp_vm

### Terraform Configuration Files
```
provider "vcd" {
  user                          = var.username
  password                  = var.password
  org                           = var.org_name
  vdc                           = var.vdc_name
  url                            = var.api_url
  max_retry_timeout    = "60"
  allow_unverified_ssl   = "true"
}

resource "vcd_vapp" "dev-test" {
  name     = "DEV-TEST"
}

resource "vcd_vapp_vm" "dev-test1" {
  vapp_name        = vcd_vapp.dev-test.name
  name                 = "DEV-TEST1"
  template_name  = var.shared-specs["template"]
  catalog_name     = var.shared-specs["catalog"]

  network {
    type               = "org"
    name               = "TEST-LAN"
    ip                 = "10.2.6.51"
    ip_allocation_mode = "MANUAL"
    is_primary         = true
  }

  depends_on = [vcd_vapp.dev-test]
}

resource "vcd_vapp_vm" "dev-test2" {
  vapp_name        = vcd_vapp.dev-test.name
  name             = "DEV-TEST2"
  template_name    = var.shared-specs["template"]

  network {
    type               = "org"
    name               = "TEST-LAN"
    ip                 = "10.2.6.52"
    ip_allocation_mode = "MANUAL"
    is_primary         = true
  }

  depends_on = [vcd_vapp.dev-test]
}
```

### Debug Output
apply.log
https://gist.github.com/iamspector/8e46d1d6aae4ca3910fb9473d8ece293 

### Expected Behavior
If Vcloud Director tenant settings allow multiple parallel tasks to run at the same time, the expected behavior of Terraform is to create multiple resources at the same time if no other dependencies are set.

### Actual Behavior
After creating vApp VCD provider starts creating VMs, but for each individual VM it puts lock on vApp until this VM is created. After that it starts this process for all other VMs, one by one. Assuming that in future I can have more than 1-2 VMs to be deployed this consecutive behaviour can lead to a very long running terraform plan appliance, which is not quite good.

### Steps to Reproduce
Vcloud Director 9.1
1. Create Terraform config from the example above
2. $ terraform apply

**Comment by vbauzysvmware** [comment]
Hi @iamspector currently vCD doesn't support multiple VMs creation for same vApp. But you can create multiple VMs parallelly for different vApps. Current provider implementation supports that. In future when vCD supports multiple parallel - we can adapt adapter too.

**Comment by iamspector** [comment]
> 
> 
> Hi @iamspector currently vCD doesn't support multiple VMs creation for same vApp. But you can create multiple VMs parallelly for different vApps. Current provider implementation supports that. In future when vCD supports multiple parallel - we can adapt adapter too.

Hi @vbauzysvmware. Thanks for your quick reply. I am trying to clarify everything for myself about vCD multiple parallel support. 

I tried to see if my issue was about my vApp inability to handle parallel tasks: I've set one VM for creation through terraform and while it was creating I've started creation of second VM through web-GUI. Both VMs were started in one vApp. And task which was made via GUI was sent successfully to VCD and I had two VMs creating in one vApp at the same time in a parallel manner.

Thus, can you please clarify what you mean under "vCD supports multiple parallel" ?

**Comment by vbauzysvmware** [comment]
Hi @iamspector I checked once more time and as I said, vApp doesn't support two changes on same time. If you use UI to add VM one by one, you will see that UI blocks actions until first actions is finished. Your case just bypass UI blocks and just accepts tasks, but in reality if sometimes it succeeds it doesn't mean it works faster. Our terraform provider solution depends on 100% working way. Good thing you still capable spawn VM in different vApps in parallel way.

**Comment by iamspector** [comment]
Hi @vbauzysvmware. 

Recently, I found a solution in this API method:
POST /vApp/{id}/action/recomposeVApphttps://code.vmware.com/apis/442/vcloud/doc/doc/operations/POST-RecomposeVApp.html

There is an element in XML called RecomposeVAppParams which can contain multiple SourcedItem elements which "Represents a vApp, vApp template or Vm to include in a composed vApp". 

This way it is only one change for vApp at a time.

**Comment by vbauzysvmware** [comment]
Hi @iamspector 

Yes it's possible in some cases and please be aware that works only `Vms must be powered off and cannot have an independent disk attached.` We can't use in that in terraform case as we can't aggregate one request from different resources.
