### ISSUE TITLE
vcd_vapp_vm: is_primary is not read correctly

### ISSUE THREAD

**Issue by jpbuecken** [terraform-providers/terraform-provider-vcd#458]
Hello,
we have an VM such that:
- there is no nic 0
- it has a nic 1
- it has a nic 2

So we have two network interfaces, but counting starts with 1.
The second interface is primary

![image](https://user-images.githubusercontent.com/38046041/75141984-62ed1380-56f2-11ea-927e-8ca624e79479.png)

In this case, is_primary value is calculated wrong.

netIndex for primary is 1, but primaryNetworkConnectionIndex is 2:

https://github.com/terraform-providers/terraform-provider-vcd/blob/a7172f483940ed50ffeed9d4809c29d965e3ea1d/vcd/resource_vcd_vapp_vm.go#L1638

Instead, you need to compare networkConnectionIndex of the interface with primaryNetworkConnectionIndex

This changes worked for us on VCD 10

```
-       for netIndex, vmNet := range vm.VM.NetworkConnectionSection.NetworkConnection {
+       for _, vmNet := range vm.VM.NetworkConnectionSection.NetworkConnection { 
 [...]
-               if netIndex == vm.VM.NetworkConnectionSection.PrimaryNetworkConnectionIndex {
+               if vmNet.NetworkConnectionIndex == vm.VM.NetworkConnectionSection.PrimaryNetworkConnectionIndex { 
```

### Terraform Version
Terraform v0.12.18

### Affected Resource(s)
Please list the resources as a list, for example:
- vcd_vapp_vm

### Terraform Configuration Files
```hcl
  network {
    type               = "org"
    name               = var.network
    ip_allocation_mode = "POOL"
  }
  network {
    type               = "org"
    name               = var.network
    ip_allocation_mode = var.private_ip == null ? "POOL" : "MANUAL"
    ip                 = var.private_ip
    is_primary         = true
  }

```

**Comment by Didainius** [comment]
Thanks, we'll look at patching it.
Just curious - how did you end up with such config (not having NIC0). Was it imported?

**Comment by jpbuecken** [comment]
> Just curious - how did you end up with such config (not having NIC0). Was it imported?

Exactly. It has been imported from vSphere to VCD. Now it is imported to terraform for further management.

**Comment by jpbuecken** [comment]
Any news on this? This bug prevent us from using a official release. We need to compile a own version with our fix applied.
The VMs without NIC0 had been generated by another VMware product before, so not sure why it is messed up, but we cannot change it.

**Comment by Didainius** [comment]
I can't yet promise 100% but will try to squeeze it in for next version

**Comment by jpbuecken** [comment]
Hi,
thank you for the effort. May compile master in a few days to test.
