### ISSUE TITLE
VM doesn't support vApp routed networks

### ISSUE THREAD

**Issue by vbauzysvmware** [terraform-providers/terraform-provider-vcd#471]
Current implementation of VM has old way of handling vApp networks.

* It has deprecated behavior `vapp_network_name` and `network_name` which toggles using precreated vApp network(only isolated type) or creating org vdc attached vApp network.

* It has new `network` construction with `network.name` and `network.type` and behaviour on identifying vApp network or attaching Org Vdc network as vApp network. 

Currently both of them supports on vApp network(isolated). We need enhance to support vApp network which is connected to Org Vdc network(routed).

FYI - there are 4 types of vapp network:
1.) vcd_vapp_network | connected to Org net | has static routing
2.) vcd_vapp_network | not connected to Org net | isolated
3.) vcd_vapp_org_network | is_fenced = true | no static routing (almost same as (1))
4.) vcd_vapp_org_network | is_fenced = false | directly connected

**Comment by lvirbalas** [comment]
Illustration:

```
resource "vcd_vapp_network" "demo_vapp_net_w_org" {
  name      = "demo-vapp-net-w-org"
  vapp_name = vcd_vapp.demo_vapp.name

  # 2.7.0
  org_network_name = vcd_network_routed.demo_routed_net_multi_pool.name

  gateway            = "192.168.9.1"
  netmask            = "255.255.255.0"
  dns1               = "192.168.9.1"
  dns2               = "192.168.9.2"
  dns_suffix         = "mybiz.biz"
  guest_vlan_allowed = true

  static_ip_pool {
    start_address = "192.168.9.51"
    end_address   = "192.168.9.100"
  }

  dhcp_pool {
    start_address = "192.168.9.2"
    end_address   = "192.168.9.50"
  }
}

resource "vcd_vapp_vm" "demo_vm_wordpress" {
  # ...

  network {
    type = "vapp"
    name               = vcd_vapp_network.demo_vapp_net_w_org.name
    ip_allocation_mode = "DHCP"
  }
}
```

Leads to an error like this during apply:

```
vcd_vapp_network.demo_vapp_net_w_org: Still creating... [30s elapsed]
vcd_vapp_network.demo_vapp_net_w_org: Creation complete after 37s [id=dd4b0367-7614-4a74-bc20-9513f8ffdda5]
vcd_vapp_vm.demo_vm_wordpress: Creating...

Error: unable to process network configuration: unable to find vApp network demo-vapp-net-w-org: configured vApp network isn't found: demo-vapp-net-w-org

  on xendi.tf line 344, in resource "vcd_vapp_vm" "demo_vm_wordpress":
 344: resource "vcd_vapp_vm" "demo_vm_wordpress" {
```

**Comment by vbauzysvmware** [comment]
Will be release in 2.7
