### ISSUE TITLE
 Error: error retrieving Org and VDC: error retrieving Org Devices_2: error retrieving org | Timeout

### ISSUE THREAD

**Issue by MrTolerant** [terraform-providers/terraform-provider-vcd#474]
Hi all i trying to deploy VMs to vCloud Director. Evrething is good but sometimes i have a error on random VMs (1-3 vms)
```
module.make_vm.vcd_vapp_vm.vapp_vm["nginx-01"]: Creating...
 module.make_vm.vcd_vapp_vm.vapp_vm["nginx-01"]: Still creating... [10s elapsed]
...
 module.make_vm.vcd_vapp_vm.vapp_vm["engine-01"]: Still creating... [2m0s elapsed]
 module.make_vm.vcd_vapp_vm.vapp_vm["engine-01"]: Creation complete after 2m0s [id=urn:vcloud:vm:f25e2b0d-0e30-40da-9cb8-3c08bb22f1be]
 Error: error retrieving Org and VDC: error retrieving Org Devices_2: error retrieving org: Get https://vcd.cloud.ru/api/org/97eca273-df2e-424d-97c2-730936be4911: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
   on vcd/vcloud.tf line 34, in resource "vcd_vapp_vm" "vapp_vm":
   34: resource "vcd_vapp_vm" "vapp_vm" {
 ERROR: Job failed: exit code 1

```
```
terraform {
  required_version = ">= 0.12.23"

   backend "s3" {
     bucket   = "terraform"
     skip_credentials_validation = true
     key      = "terraform.tfstate"
     endpoint = "http://ceph.ORG.ru:7480"
     region = "us-east-1"
   }
}

provider "vcd" {
  user                 = var.user
  password             = var.password
  org                  = var.org
  vdc                  = var.vdc
  url                  = var.vcd_url
  max_retry_timeout    = 30
  allow_unverified_ssl = true
}

```
My base module:
```
data "template_file" "init" {
  template = file("init.sh")
}

resource "vcd_vapp" "vapp" {
  for_each = toset(var.vapp_names)
  name = each.value

   lifecycle {
     prevent_destroy = true
   }
}

locals {
  vm_list_flat = flatten([
    for vm_name, vm_params in var.vm_map : [
      for index in range(lookup(vm_params, "count", 1)) : {
        index              = index
        vapp_name          = vm_params.vapp_name
        vm_name            = vm_name
        catalog_name       = lookup(vm_params, "catalog_name", var.catalog_name)
        template_name      = lookup(vm_params, "template_name", var.template_name)
        memory             = vm_params.memory
        cpus               = vm_params.cpus
        cpu_cores          = vm_params.cpu_cores
        power_on           = lookup(vm_params, "power_on", var.power_on)
        network_name       = vm_params.network_name
        ip                 = lookup(vm_params, "ip_subnet", null) != null ? cidrhost(lookup(vm_params, "ip_subnet", null), index) : null
      }
    ]
  ])
}

resource "vcd_vapp_vm" "vapp_vm" {
  for_each = {
    for vm in local.vm_list_flat : format("%s-%02d", vm.vm_name, vm.index + 1) => vm
  }

  vapp_name     = each.value.vapp_name
  name          = lower(each.key)
  catalog_name  = each.value.catalog_name
  template_name = each.value.template_name
  memory        = each.value.memory
  cpus          = each.value.cpus
  cpu_cores     = each.value.cpu_cores
  power_on      = each.value.power_on

  customization {
    force       = true
  }

  initscript    = data.template_file.init.rendered

  network {
    type               = "org"
    name               = each.value.network_name
    ip                 = each.value.ip
    ip_allocation_mode = each.value.ip != null ? "MANUAL" : "POOL"
    is_primary         = true
  }

  depends_on = [vcd_vapp.vapp]

   lifecycle {
    prevent_destroy = true
   }
}

```
Can you help me?
Ned more info?

Terraform v0.12.23
 * provider.template: version = "~> 2.1"
 * provider.vcd: version = "~> 2.6"

Some trace:

```
 module.make_vm.vcd_vapp_vm.vapp_vm["nginx-02"]: Still creating... [6m10s elapsed]
 2020/03/11 13:32:30 [TRACE] dag/walk: vertex "provider.vcd (close)" is waiting for "module.make_vm.vcd_vapp_vm.vapp_vm[\"nginx-02\"]"
 2020/03/11 13:32:30 [TRACE] dag/walk: vertex "root" is waiting for "meta.count-boundary (EachMode fixup)"
 2020/03/11 13:32:31 [TRACE] dag/walk: vertex "meta.count-boundary (EachMode fixup)" is waiting for "module.make_vm.vcd_vapp_vm.vapp_vm[\"nginx-02\"]"
 2020/03/11 13:32:35 [TRACE] dag/walk: vertex "root" is waiting for "meta.count-boundary (EachMode fixup)"
 2020/03/11 13:32:35 [TRACE] dag/walk: vertex "provider.vcd (close)" is waiting for "module.make_vm.vcd_vapp_vm.vapp_vm[\"nginx-02\"]"
 2020/03/11 13:32:36 [TRACE] dag/walk: vertex "meta.count-boundary (EachMode fixup)" is waiting for "module.make_vm.vcd_vapp_vm.vapp_vm[\"nginx-02\"]"
 module.make_vm.vcd_vapp_vm.vapp_vm["nginx-02"]: Still creating... [6m20s elapsed]
 2020/03/11 13:32:40 [TRACE] dag/walk: vertex "root" is waiting for "meta.count-boundary (EachMode fixup)"
 2020/03/11 13:32:40 [TRACE] dag/walk: vertex "provider.vcd (close)" is waiting for "module.make_vm.vcd_vapp_vm.vapp_vm[\"nginx-02\"]"
 2020/03/11 13:32:41 [TRACE] dag/walk: vertex "meta.count-boundary (EachMode fixup)" is waiting for "module.make_vm.vcd_vapp_vm.vapp_vm[\"nginx-02\"]"
 2020/03/11 13:32:45 [TRACE] dag/walk: vertex "root" is waiting for "meta.count-boundary (EachMode fixup)"
 2020/03/11 13:32:45 [TRACE] dag/walk: vertex "provider.vcd (close)" is waiting for "module.make_vm.vcd_vapp_vm.vapp_vm[\"nginx-02\"]"
 2020/03/11 13:32:46 [TRACE] dag/walk: vertex "meta.count-boundary (EachMode fixup)" is waiting for "module.make_vm.vcd_vapp_vm.vapp_vm[\"nginx-02\"]"
 module.make_vm.vcd_vapp_vm.vapp_vm["nginx-02"]: Still creating... [6m30s elapsed]
 2020/03/11 13:32:50 [TRACE] dag/walk: vertex "root" is waiting for "meta.count-boundary (EachMode fixup)"
 2020/03/11 13:32:50 [TRACE] dag/walk: vertex "provider.vcd (close)" is waiting for "module.make_vm.vcd_vapp_vm.vapp_vm[\"nginx-02\"]"
 2020/03/11 13:32:51 [TRACE] dag/walk: vertex "meta.count-boundary (EachMode fixup)" is waiting for "module.make_vm.vcd_vapp_vm.vapp_vm[\"nginx-02\"]"
 2020/03/11 13:32:55 [TRACE] dag/walk: vertex "root" is waiting for "meta.count-boundary (EachMode fixup)"
 2020/03/11 13:32:55 [TRACE] dag/walk: vertex "provider.vcd (close)" is waiting for "module.make_vm.vcd_vapp_vm.vapp_vm[\"nginx-02\"]"
  
```
```
waiting for "module.make_vm.vcd_vapp_vm.vapp_vm[\"nginx-02\"]"
2020-03-11T13:40:35.860Z [DEBUG] plugin.terraform-provider-vcd_v2.6.0_x4: 2020/03/11 13:40:35 [DEBUG] Unlocking "org:MyCompany_2|vdc:MyCompany_2_VDC01|vapp:nginx"
2020-03-11T13:40:35.860Z [DEBUG] plugin.terraform-provider-vcd_v2.6.0_x4: 2020/03/11 13:40:35 [DEBUG] Unlocked "org:MyCompany_2|vdc:MyCompany_2_VDC01|vapp:nginx"
2020/03/11 13:40:35 [DEBUG] module.make_vm.vcd_vapp_vm.vapp_vm["nginx-02"]: apply errored, but we're indicating that via the Error pointer rather than returning it: error retrieving Org and VDC: error retrieving Org MyCompany_2: error retrieving org: Get https://vcd.OrdCloud.ru/api/org/97eca273-df2e-424d-97c2-730936be4911: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
2020/03/11 13:40:35 [TRACE] module.make_vm: eval: *terraform.EvalMaybeTainted
2020/03/11 13:40:35 [TRACE] EvalMaybeTainted: module.make_vm.vcd_vapp_vm.vapp_vm["nginx-02"] encountered an error during creation, so it is now marked as tainted
2020/03/11 13:40:35 [TRACE] module.make_vm: eval: *terraform.EvalWriteState
2020/03/11 13:40:35 [TRACE] EvalWriteState: recording 1 dependencies for module.make_vm.vcd_vapp_vm.vapp_vm["nginx-02"]
2020/03/11 13:40:35 [TRACE] EvalWriteState: writing current state object for module.make_vm.vcd_vapp_vm.vapp_vm["nginx-02"]
2020/03/11 13:40:35 [TRACE] module.make_vm: eval: *terraform.EvalApplyProvisioners
2020/03/11 13:40:35 [TRACE] EvalApplyProvisioners: vcd_vapp_vm.vapp_vm["nginx-02"] is tainted, so skipping provisioning
2020/03/11 13:40:35 [TRACE] module.make_vm: eval: *terraform.EvalMaybeTainted
2020/03/11 13:40:35 [TRACE] EvalMaybeTainted: module.make_vm.vcd_vapp_vm.vapp_vm["nginx-02"] was already tainted, so nothing to do
2020/03/11 13:40:35 [TRACE] module.make_vm: eval: *terraform.EvalWriteState
2020/03/11 13:40:35 [TRACE] EvalWriteState: recording 1 dependencies for module.make_vm.vcd_vapp_vm.vapp_vm["nginx-02"]
2020/03/11 13:40:35 [TRACE] EvalWriteState: writing current state object for module.make_vm.vcd_vapp_vm.vapp_vm["nginx-02"]
2020/03/11 13:40:35 [TRACE] module.make_vm: eval: *terraform.EvalIf
2020/03/11 13:40:35 [TRACE] module.make_vm: eval: *terraform.EvalIf
2020/03/11 13:40:35 [TRACE] module.make_vm: eval: *terraform.EvalWriteDiff
2020/03/11 13:40:35 [TRACE] module.make_vm: eval: *terraform.EvalApplyPost
2020/03/11 13:40:35 [ERROR] module.make_vm: eval: *terraform.EvalApplyPost, err: error retrieving Org and VDC: error retrieving Org MyCompany_2: error retrieving org: Get https://vcd.OrdCloud.ru/api/org/97eca273-df2e-424d-97c2-730936be4911: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
2020/03/11 13:40:35 [ERROR] module.make_vm: eval: *terraform.EvalSequence, err: error retrieving Org and VDC: error retrieving Org MyCompany_2: error retrieving org: Get https://vcd.OrdCloud.ru/api/org/97eca273-df2e-424d-97c2-730936be4911: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
2020/03/11 13:40:35 [TRACE] [walkApply] Exiting eval tree: module.make_vm.vcd_vapp_vm.vapp_vm["nginx-02"]
2020/03/11 13:40:35 [TRACE] vertex "module.make_vm.vcd_vapp_vm.vapp_vm[\"nginx-02\"]": visit complete
2020/03/11 13:40:35 [TRACE] dag/walk: upstream of "meta.count-boundary (EachMode fixup)" errored, so skipping
2020/03/11 13:40:35 [TRACE] dag/walk: upstream of "provider.vcd (close)" errored, so skipping
2020/03/11 13:40:35 [TRACE] dag/walk: upstream of "root" errored, so skipping
2020/03/11 13:40:35 [DEBUG] Uploading remote state to S3: {
  Body: buffer(0xc000018630),
  Bucket: "terraform",
  ContentLength: 10345,
  ContentType: "application/json",
  Key: "terraform.tfstate"
}
```

**Comment by MrTolerant** [comment]
@Avbauzysvmware HI :) can you help me?)

**Comment by vbauzysvmware** [comment]
Hi @MrTolerant,

According error seems issue with your evn network stability or other network configuration issues.

To deny other possible issues, you could enable additional logging(By setting this https://www.terraform.io/docs/providers/vcd/index.html#logging) and share results with us.

**Comment by MrTolerant** [comment]
> Hi @MrTolerant,
> 
> According error seems issue with your evn network stability or other network configuration issues.
> 
> To deny other possible issues, you could enable additional logging(By setting this https://www.terraform.io/docs/providers/vcd/index.html#logging) and share results with us.
`` 2020/03/12 13:14:39 [DEBUG] [aws-sdk-go] 
 Error: failed powering on with customization: error waiting for task completion after power on with customization nginx-01: task did not complete successfully:  [500:INTERNAL_SERVER_ERROR] - [ fef9a0d7-18a9-4caa-9b80-7224ef372724 ] Unable to perform this action. Contact your cloud administrator.
   on .terraform/modules/make_vms/vcloud.tf line 32, in resource "vcd_vapp_vm" "vapp_vm":
   32: resource "vcd_vapp_vm" "vapp_vm" {
 Error: failed powering on with customization: error waiting for task completion after power on with customization nginx-02: task did not complete successfully:  [500:INTERNAL_SERVER_ERROR] - [ c04edfcc-c1e2-47b6-8e1e-87b886f68b1a ] Unable to perform this action. Contact your cloud administrator.
   on .terraform/modules/make_vms/vcloud.tf line 32, in resource "vcd_vapp_vm" "vapp_vm":
   32: resource "vcd_vapp_vm" "vapp_vm" {
 Error: failed powering on with customization: error waiting for task completion after power on with customization test-01: task did not complete successfully:  [500:INTERNAL_SERVER_ERROR] - [ 6961f29e-535b-4b13-9411-b741e20da22b ] Unable to perform this action. Contact your cloud administrator.
   on .terraform/modules/make_vms/vcloud.tf line 32, in resource "vcd_vapp_vm" "vapp_vm":
   32: resource "vcd_vapp_vm" "vapp_vm" {
 Error: failed powering on with customization: error waiting for task completion after power on with customization nlp-engine-01: task did not complete successfully:  [500:INTERNAL_SERVER_ERROR] - [ c062aa47-d00b-4dfa-8dc6-c23989c3ecab ] Unable to perform this action. Contact your cloud administrator.
   on .terraform/modules/make_vms/vcloud.tf line 32, in resource "vcd_vapp_vm" "vapp_vm":
   32: resource "vcd_vapp_vm" "vapp_vm" {``

**Comment by vbauzysvmware** [comment]
> > Hi @MrTolerant,
> > According error seems issue with your evn network stability or other network configuration issues.
> > To deny other possible issues, you could enable additional logging(By setting this https://www.terraform.io/docs/providers/vcd/index.html#logging) and share results with us.
> > ` 2020/03/12 13:14:39 [DEBUG] [aws-sdk-go]   Error: failed powering on with customization: error waiting for task completion after power on with customization nginx-01: task did not complete successfully:  [500:INTERNAL_SERVER_ERROR] - [ fef9a0d7-18a9-4caa-9b80-7224ef372724 ] Unable to perform this action. Contact your cloud administrator.    on .terraform/modules/make_vms/vcloud.tf line 32, in resource "vcd_vapp_vm" "vapp_vm":    32: resource "vcd_vapp_vm" "vapp_vm" {  Error: failed powering on with customization: error waiting for task completion after power on with customization nginx-02: task did not complete successfully:  [500:INTERNAL_SERVER_ERROR] - [ c04edfcc-c1e2-47b6-8e1e-87b886f68b1a ] Unable to perform this action. Contact your cloud administrator.    on .terraform/modules/make_vms/vcloud.tf line 32, in resource "vcd_vapp_vm" "vapp_vm":    32: resource "vcd_vapp_vm" "vapp_vm" {  Error: failed powering on with customization: error waiting for task completion after power on with customization test-01: task did not complete successfully:  [500:INTERNAL_SERVER_ERROR] - [ 6961f29e-535b-4b13-9411-b741e20da22b ] Unable to perform this action. Contact your cloud administrator.    on .terraform/modules/make_vms/vcloud.tf line 32, in resource "vcd_vapp_vm" "vapp_vm":    32: resource "vcd_vapp_vm" "vapp_vm" {  Error: failed powering on with customization: error waiting for task completion after power on with customization nlp-engine-01: task did not complete successfully:  [500:INTERNAL_SERVER_ERROR] - [ c062aa47-d00b-4dfa-8dc6-c23989c3ecab ] Unable to perform this action. Contact your cloud administrator.    on .terraform/modules/make_vms/vcloud.tf line 32, in resource "vcd_vapp_vm" "vapp_vm":    32: resource "vcd_vapp_vm" "vapp_vm" {`

@MrTolerant provided snippet isn't full, ending is missing.

**Comment by MrTolerant** [comment]
last error i solve by comment:
```
  # customization {
  #   force       = true
  # }
```

**Comment by MrTolerant** [comment]
And it seems that I won the first error by adding `power_on = true` to vapp
```
resource "vcd_vapp" "vapp" {
  for_each         = toset(var.vapp_names)
  name             = each.value
  power_on         = true
  description      = each.value
  
  # lifecycle {
  #   prevent_destroy = true
  # }
}
```

**Comment by MrTolerant** [comment]
is that config ok?
```

resource "vcd_vapp" "vapp" {
  for_each         = toset(var.vapp_names)
  name             = each.value
  power_on         = true
  description      = each.value
  
  # lifecycle {
  #   prevent_destroy = true
  # }
}

locals {
  vm_list_flat = flatten([
    for vm_name, vm_params in var.vm_map : [
      for index in range(lookup(vm_params, "count", 1)) : {
        index              = index
        vapp_name          = vm_params.vapp_name
        vm_name            = vm_name
        catalog_name       = lookup(vm_params, "catalog_name", var.catalog_name)
        template_name      = lookup(vm_params, "template_name", var.template_name)
        memory             = vm_params.memory
        cpus               = vm_params.cpus
        cpu_cores          = vm_params.cpu_cores
        power_on           = lookup(vm_params, "power_on", var.power_on)
        network_name       = vm_params.network_name
        ip                 = lookup(vm_params, "ip_subnet", null) != null ? cidrhost(lookup(vm_params, "ip_subnet", null), index) : null
      }
    ]
  ])
}

resource "vcd_vapp_vm" "vapp_vm" {
  for_each = {
    for vm in local.vm_list_flat : format("%s-%02d", vm.vm_name, vm.index + 1) => vm
  }

  vapp_name        = each.value.vapp_name
  name             = each.key
  catalog_name     = each.value.catalog_name
  template_name    = each.value.template_name
  memory           = each.value.memory
  cpus             = each.value.cpus
  cpu_cores        = each.value.cpu_cores
  power_on         = tobool(each.value.power_on)
  accept_all_eulas = true

  # customization {
  #   force       = true
  # }

  # initscript    = templatefile("init.sh", { ip = each.value.ip != null ? each.value.ip : "127.0.0.1" })

  network {
    type               = "org"
    name               = each.value.network_name
    ip                 = each.value.ip
    ip_allocation_mode = each.value.ip != null ? "MANUAL" : "POOL"
    is_primary         = true
  }

  depends_on = [vcd_vapp.vapp]

  # lifecycle {
  #   prevent_destroy = true
  # }
}

```

**Comment by vbauzysvmware** [comment]
> last error i solve by comment:
> 
> ```
>   # customization {
>   #   force       = true
>   # }
> ```

Customization various fixes and changes coming with next release, which is soon.

**Comment by MrTolerant** [comment]
> > last error i solve by comment:
> > ```
> >   # customization {
> >   #   force       = true
> >   # }
> > ```
> 
> Customization various fixes and changes coming with next release, which is soon.

Please tell me when to wait until the next release?
Thank you very much for your work!

**Comment by Didainius** [comment]
> > > last error i solve by comment:
> > > ```
> > >   # customization {
> > >   #   force       = true
> > >   # }
> > > ```
> > 
> > 
> > Customization various fixes and changes coming with next release, which is soon.
> 
> Please tell me when to wait until the next release?
> Thank you very much for your work!

@MrTolerant , 
Next release should happen soon (hopefully in days), but the `customization.force=true` error is very strange. I haven't seen such. Which vCD version do you have? Usually 500 links to some error on vCD side, not terraform-provider-vcd.

As far as getting the IP - this usually very much depends on guest operating system. For testing we usually use [Photon OS](http://dl.bintray.com/vmware/photon/3.0/Rev2/ova/photon-hw11-3.0-9355405.ova) and it sets the IP address on interface on first boot "automagically". For other OS'es - I've head people need to exactly do "force customization" for it to work.

I'd propose to try and deploy one VM via GUI with IP allocation=POOL and check if it works or not. We need to understand if your guest os is capable of setting the IP address or not to identify whether there is any potential bug inside the provider.

**Comment by lvirbalas** [comment]
> Please tell me when to wait until the next release?

Next release (2.7.0) is in the final certification phase as we speak. Unless unexpected issues are hit, it should be ready next week.

>  Thank you very much for your work!

Thank you for the feedback. Keep it coming! :)

**Comment by vbauzysvmware** [comment]
> > > > last error i solve by comment:
> > > > ```
> > > >   # customization {
> > > >   #   force       = true
> > > >   # }
> > > > ```
> > > 
> > > 
> > > Customization various fixes and changes coming with next release, which is soon.
> > 
> > 
> > Please tell me when to wait until the next release?
> > Thank you very much for your work!
> 
> @MrTolerant ,
> Next release should happen soon (hopefully in days), but the `customization.force=true` error is very strange. I haven't seen such. Which vCD version do you have? Usually 500 links to some error on vCD side, not terraform-provider-vcd.
> 
> As far as getting the IP - this usually very much depends on guest operating system. For testing we usually use [Photon OS](http://dl.bintray.com/vmware/photon/3.0/Rev2/ova/photon-hw11-3.0-9355405.ova) and it sets the IP address on interface on first boot "automagically". For other OS'es - I've head people need to exactly do "force customization" for it to work.
> 
> I'd propose to try and deploy one VM via GUI with IP allocation=POOL and check if it works or not. We need to understand if your guest os is capable of setting the IP address or not to identify whether there is any potential bug inside the provider.

Don't forget that you have to install VMware Tools in the guest operating system.

**Comment by vbauzysvmware** [comment]
Hi @MrTolerant, please try, newest version 2.7 released

**Comment by MrTolerant** [comment]
> Hi @MrTolerant, please try, newest version 2.7 released

Wow thank you!

**Comment by MrTolerant** [comment]
Guys help me here please [https://github.com/hashicorp/terraform/issues/24379](https://github.com/hashicorp/terraform/issues/24379)

**Comment by Didainius** [comment]
@MrTolerant , would you potentially be able to share the whole configuration with modules in a zipped file on some server  leaving out any private data you may have)?

Thanks

**Comment by vbauzysvmware** [comment]
I am closing this. Please reopen if new information will be provided.
