### ISSUE TITLE
Migrate templates to usage of vcd_vapp_org_network

### ISSUE THREAD

**Issue by NilsBusche** [terraform-providers/terraform-provider-vcd#480]
### Affected Resource(s)
vcd_vapp_org_network
vcd_vapp
vcd_vapp_vm

### Current configuration

Currently we are using the automatic attachment method for org networks within the `vcd_vapp_vm` resource:

```hcl
resource "vcd_vapp_vm" "instance" {
[...]
  network {
    type               = "org"
    name               = var.network
    ip_allocation_mode = "POOL"
    is_primary         = true
  }
[...]
```

### Future configuration

Since this method is deprecated with the last release we want to migrate to the new method using an extra resource:

```hcl
resource "vcd_vapp_org_network" "vappnetattach" {
  vapp_name        = var.hostname
  org_network_name = var.network
}

resource "vcd_vapp_vm" "instance" {
[...]
  network {
    type               = "org"
    name               = vcd_vapp_org_network.vappnetattach.org_network_name
    ip_allocation_mode = "POOL"
    is_primary         = true
  }
[...]
```

### Question

Because for `vcd_vapp_org_network` there is no import option, `terraform apply` would create this resource and (re)attach the network to the vApp. I'm not sure if this could be done without a downtime and if there are side effects.

Is there a recommended migration way?

**Comment by vbauzysvmware** [comment]
Both resources supports imports. `org-name.vdc-name.vapp-name.network-name` or `org-name.vdc-name.vapp-name.org-network-name`. I will update documentation!
