### ISSUE TITLE
Error 401 after a (very) long template upload

### ISSUE THREAD

**Issue by ejgarcia** [terraform-providers/terraform-provider-vcd#482]
Hi,

I applied a configuration file that just uploads a template to a vCD catalog. The upload process itself worked correctly, but after finishing, I got this error message:

vcd_catalog_item.db: Still creating... [32m21s elapsed]
vcd_catalog_item.WIN-2016-SE-MULTI_20191129.ova: Upload progress 99.25%
vcd_catalog_item.db: Still creating... [32m31s elapsed]
vcd_catalog_item.WIN-2016-SE-MULTI_20191129.ova: Upload progress 99.78%
vcd_catalog_item.db: Still creating... [32m41s elapsed]
vcd_catalog_item.WIN-2016-SE-MULTI_20191129.ova: Upload progress 100.00%

Error: vCD Error importing new catalog item: &errors.errorString{s:"error retreiving task: error retrieving task: [ParseErr]: error parsing error body for non-200 request: EOF (&{Status:401 Unauthorized **StatusCode:401** Proto:HTTP/1.1 ProtoMajor:1 ProtoMinor:1 Header:map[Content-Length:[0] Date:[Mon, 23 Mar 2020 23:21:38 GMT] X-Vmware-Vcloud-Ceip-Id:[6ef30e48-ab0b-43be-92e3-44121467b8e2] X-Vmware-Vcloud-Request-Id:[b9fcf17c-4d41-4b79-9e16-379b912cc7a1]] Body:0xc000150200 ContentLength:0 TransferEncoding:[] Close:false Uncompressed:false Trailer:map[] Request:0xc000b92000 TLS:0xc0000be9a0})"}

  on templates.tf line 18, in resource "vcd_catalog_item" "db":
  18: resource "vcd_catalog_item" "db" {

Since upload took longer than 30 minutes, it is my impression that the 401 code could be related to the 30 minutes of validity of the session token.

### Terraform Version
Terraform v0.12.20
provider.vcd v2.7.0

### Affected Resource
- vcd_catalog_item

### Terraform Configuration Files
```hcl
provider "vcd" {
  user = "admin"
  password = "password"
  org = "my-org"
  url = "https://vcd/api"
  max_retry_timeout = 5
  allow_unverified_ssl = true
}

resource "vcd_catalog" "tfcatalog" {
  org = "my-org"
  name             = "my-catalog"
  description      = "Temporary catalog"
  delete_recursive = "true"
  delete_force     = "true"
}

resource "vcd_catalog_item" "db" {
  org     = vcd_catalog.tfcatalog.org
  catalog = vcd_catalog.tfcatalog.name

  name                 = "WIN-2016-SE-MULTI_20191129.ova"
  description          = "Template"
  ova_path             = "./WIN-2016-SE-MULTI_20191129.ova"
  upload_piece_size    = 5
  show_upload_progress = "true"

}
```

### Expected Behavior
After the upload, the configuration apply should have finished successfully

### Actual Behavior
An error was shown, with a trace informing of a 401 code

### Steps to Reproduce
1. `terraform apply`

**Comment by vbauzysvmware** [comment]
Hi @ejgarcia to better understand issue we need more logs from go-vcloud-director which should be enabled. How to enable is mentioned in documentation: https://www.terraform.io/docs/providers/vcd/index.html - parameters logging, logging_file.

**Comment by ejgarcia** [comment]
I executed it again, with logging enabled. Here are the logs:

[go-vcloud-director.log](https://gist.github.com/ejgarcia/860d9f65afa189b790ef9af27c49d344#file-go-vcloud-director-log)

**Comment by vbauzysvmware** [comment]
> I executed it again, with logging enabled. Here are the logs:
> 
> [go-vcloud-director.log](https://gist.github.com/ejgarcia/860d9f65afa189b790ef9af27c49d344#file-go-vcloud-director-log)

thank you, but this time without error? Could you try to reproduce?

**Comment by ejgarcia** [comment]
You can see the error, the 401, at the end of the logs. It is a very large file, please make sure that you do not see it truncated.
The root issue seems to be that the same token is used after more than 30 minutes of upload, so inactivity has made it expire.

**Comment by vbauzysvmware** [comment]
Oh yes, I have make it raw to see it all. Thank you for logs, it can be the case which you mentioned. I will investigate. Yet this unexpected as it makes a lot request with `upload_piece_size    = 5` chunks.

**Comment by vbauzysvmware** [comment]
@ejgarcia Have you somewhere configured Bearer token(session) validation time?

**Comment by ejgarcia** [comment]
@vbauzysvmware not that I know of, but I can check any configuration parameter in vCD.

Typically, I use Postman, and I can reuse the same session token for a long time, as long as requests are spaced in less than 30 minutes (I have just checked, and token was working ok after 20 -exact- minutes of inactivity)

I get your point of this being a multi-part upload... could it be the case that this is considered a single transaction in terms of vCD?

**Comment by vbauzysvmware** [comment]
We haven't faced such issue with existing authentication modes. Let's see if we can reproduce in our environments. 

Are you saying that you can 
* make a request
* wait 20 minutes
* make request
* wait 15 minutes
* make request and it don't fail?

**Comment by vbauzysvmware** [comment]
Also could provide these details?:)
![image](https://user-images.githubusercontent.com/41415459/77423589-2cc9af00-6dd8-11ea-9b50-b2893373d913.png)

**Comment by vbauzysvmware** [comment]
Also in SAML case session time is configured there too.

**Comment by ejgarcia** [comment]
Hi!

I just made the proposed test:

> Are you saying that you can
> 
> * make a request
> * wait 20 minutes
> * make request
> * wait 15 minutes
> * make request and it don't fail?

I used that exact timing, and the session is working as expected: the token that I acquired for the first request is still valid for the last request, after 35 minutes, due to the fact that there was an intermediate call after 20 minutes.

These are the settings in this vCD installation:

![vCD-settings](https://user-images.githubusercontent.com/250010/77431804-82548a80-6ddd-11ea-9c8c-128385dbd504.png)

I am using a local user for this, so SAML or LDAP settings should not apply (they are not configured for this vCD, in any case)

**Comment by vbauzysvmware** [comment]
> Hi!
> 
> I just made the proposed test:
> 
> > Are you saying that you can
> > 
> > * make a request
> > * wait 20 minutes
> > * make request
> > * wait 15 minutes
> > * make request and it don't fail?
> 
> I used that exact timing, and the session is working as expected: the token that I acquired for the first request is still valid for the last request, after 35 minutes, due to the fact that there was an intermediate call after 20 minutes.
> 
> These are the settings in this vCD installation:
> 
> ![vCD-settings](https://user-images.githubusercontent.com/250010/77431804-82548a80-6ddd-11ea-9c8c-128385dbd504.png)
> 
> I am using a local user for this, so SAML or LDAP settings should not apply (they are not configured for this vCD, in any case)

thank you for elaborated information. I will try to reproduce and search for possible fix.

**Comment by vbauzysvmware** [comment]
Until we figure out if can improve such case, I confirmed that if you extend() `Idle session time` to higher value - it will solve this issue.

**Comment by vbauzysvmware** [comment]
PR with change which extends session automatically merged.
