### ISSUE TITLE
Organization VDC creation failing for vCD 10.1 with: error creating VDC: no entity type found vdc34.0

### ISSUE THREAD

**Issue by sibbasriv** [terraform-providers/terraform-provider-vcd#493]
Organization VDC creation failing for vCD 10.1 with: error creating VDC: no entity type found vdc34.0

The provider plugin seems to be referring to the wrong go-vcloud-director go module.

**Comment by dataclouder** [comment]
Thanks for reporting this issue.
We are aware of the problem, and we have fixed it.
If you can build your own plugin using the master branch, you should be able to overcome the issue.
If not, you can wait for the updated plugin 2.8.0, which should be released in a few days.

**Comment by dataclouder** [comment]
v2.8.0 was released. This issue is resolved
