### ISSUE TITLE
Customize vCD VM with cloud-init

### ISSUE THREAD

**Issue by dwettstein** [terraform-providers/terraform-provider-vcd#508]
Hi all

Is it possible to customize a vCD VM with [cloud-init](https://cloudinit.readthedocs.io/) metadata and userdata using vCD Terraform Provider?
- If yes, how is it done? Please document it accordingly on [vCD Provider docs](https://www.terraform.io/docs/providers/vcd/r/vapp_vm.html).
- If no, I request to implement support for cloud-init customization.

### Terraform Version
- Terraform v0.12.24
- vCD Provider v2.8.0

### Affected Resource(s)
- vcd_vapp_vm
- VM Template: `photon-hw11-3.0-9355405.ova` without any changes

### Terraform Configuration Files
Using vSphere Provider, I can do the following to customize the Photon OS OVA using cloud-init and it works like a charm.

```hcl
extra_config = {
    "guestinfo.metadata" = "base64gzip(file(\"${path.module}/cloud-init/metadata.yaml\"))"
    "guestinfo.metadata.encoding" = "gzip+base64"
    "guestinfo.userdata" = "base64gzip(file(\"${path.module}/cloud-init/userdata.yaml\"))"
    "guestinfo.userdata.encoding" = "gzip+base64"
}
```

How can I achieve the same with vCD Provider? I tried using `guest_properties`, `customization` and `metadata` but had no success.

```hcl
guest_properties = {
    "guestinfo.metadata" = "base64gzip(file(\"${path.module}/cloud-init/metadata.yaml\"))"
    "guestinfo.metadata.encoding" = "gzip+base64"
    "guestinfo.userdata" = "base64gzip(file(\"${path.module}/cloud-init/userdata.yaml\"))"
    "guestinfo.userdata.encoding" = "gzip+base64"
}
```

### Expected Behavior
The Photon OS should have been customized through cloud-init.

### Actual Behavior
No customization happend.

### Steps to Reproduce
1. Add metadata and userdata to TF config
2. `terraform apply`
3. Check customization on vCD VM

### Important Factoids
I'm using the exact same OVA in vSphere and vCloud.

**Comment by funky81** [comment]
hi @dwettstein,
Yesterday I’m having same problem. You can use this following example in your vcd_vapp_vm

> guest_properties = {
    "user-data"        = "(Your Base64 string)"
    "hostname"         = "master-${count.index}"
  }

And also 
1. Use catalog (prefer OVA) that support cloud-init
2. please make sure you dont use customization otherwise guest_properties wont work.

**Comment by Didainius** [comment]
@dwettstein,
Interested - what type of image are you using? If your image supports DataSourceOVF (https://cloudinit.readthedocs.io/en/latest/topics/datasources/ovf.html) then as per DataSourceOVF the following fields should work:
`password`, `seedfrom`,`local-hostname`, `public-keys`, `instance-id`
Source code: https://github.com/canonical/cloud-init/blob/master/cloudinit/sources/DataSourceOVF.py#L421-L440

As @funky81 stated above you can also supply `user-data` in base64. (https://cloudinit.readthedocs.io/en/latest/topics/format.html)

I have personally tried Ubuntu 20.04 with some of the fields above. It does set the password. I also tried to leave network configuration for guest customization. It does run it, but fails as `open-vm-tools` in Ubuntu are trying to look for `ifconfig` command to determine NIC and fails configuring NICs so your mileage may vary based on the image used.

**Comment by dwettstein** [comment]
Hi @funky81 and @Didainius 
Thanks a lot for your answers! I got it to work with your help. :)

The cloud-init user-data has to be sent as follows:

```hcl
guest_properties = {
  "user-data" = base64encode(file(\"${path.module}/cloud-init/userdata.yaml\"))
}
```

Additionally, there cannot be any `customization` part. Even using the following, cloud-init won't run:

```hcl
customization = {
  enabled = false
}
```

I will close this issue now, thanks!
