### ISSUE TITLE
Terraform resets BGP settings on EDGE

### ISSUE THREAD

**Issue by dalfos** [terraform-providers/terraform-provider-vcd#515]
Hi there,

Terraform resets BGP settings on EDGE after apply

BGP settings before apply
![image](https://user-images.githubusercontent.com/3647840/83745115-bcf06400-a665-11ea-81ac-a435441a5e48.png)

BGP settings after apply
![image](https://user-images.githubusercontent.com/3647840/83745260-f2954d00-a665-11ea-8303-8cd05a6d8ba6.png)

### Terraform Version
Terraform v0.12.26
+ provider.vcd v2.8.0

### Affected Resource(s)
BGP settings on EDGE

### Terraform Configuration Files
https://gist.github.com/dalfos/4deeeb5889bd2e737f25b883fb7c433b

### Debug Output
https://gist.github.com/dalfos/2939e89750a92589c1d69f2efe557ded

### Panic Output
vcd_network_routed.net: Creating...
vcd_network_routed.net_private: Creating...
vcd_network_routed.net: Still creating... [10s elapsed]
vcd_network_routed.net_private: Still creating... [10s elapsed]
vcd_network_routed.net: Creation complete after 15s [id=urn:vcloud:network:60057730-344d-4fad-bed6-c60fb89becfe]
vcd_network_routed.net_private: Still creating... [20s elapsed]
vcd_network_routed.net_private: Still creating... [30s elapsed]
vcd_network_routed.net_private: Creation complete after 31s [id=urn:vcloud:network:795ad917-1e12-4fa1-a672-08e0ef615258]
vcd_snat.outbound: Creating...
vcd_vapp.vms: Creating...
vcd_firewall_rules.Internet: Creating...
vcd_vapp.vms: Creation complete after 7s [id=urn:vcloud:vapp:5896f901-3da2-4e51-8fa4-3d6fc5a2ef46]
vcd_vapp_vm.test-1: Creating...

Error: rpc error: code = Unavailable desc = transport is closing
Error: rpc error: code = Unavailable desc = transport is closing
Error: rpc error: code = Unavailable desc = transport is closing

### Expected Behavior
EDGE BGP settings untached

### Actual Behavior
EDGE BGP settings doesn't exist

### Steps to Reproduce
1. Apply some BGP settings
2. `terraform apply`

**Comment by dataclouder** [comment]
Hi.
Thanks for submitting this issue.

We have tried to reproduce, using the same setup indicated in your report, but unfortunately, we were unable to see the behavior you are experiencing.

Is there any more information you can provide to help pinning down the problem?
We have seen from your settings that you are using vCD 10.0 with distributed networks. Is there anything else that you could disclose about your edge gateway configuration?

**Comment by dalfos** [comment]
Hi @dataclouder 
We use vCD 9.7.0.5 and NSX-V 6.4.5
I haven't more information to help pinning down the problem.
If you still need some specific information, I’m ready to provide.

**Comment by lvirbalas** [comment]
@dalfos Does the issue persist if you don't use the `vcd_firewall_rules` and `vcd_snat` resources? 

Also, important: please use the new `vcd_nsxv_firewall_rule` and `vcd_nsxv_snat` resources instead of the old ones with advanced edge gateways (NSX-V).

Could you try and see whether the issue persists after these changes?

p.s. Also, there shouldn't be errors like these in the output:
> Error: rpc error: code = Unavailable desc = transport is closing
> Error: rpc error: code = Unavailable desc = transport is closing
> Error: rpc error: code = Unavailable desc = transport is closing

**Comment by dalfos** [comment]
@lvirbalas thank you for repply. I will test.

**Comment by dalfos** [comment]
With `vcd_firewall_rules` and `vcd_snat` resources all ok.
Thank you.

p.s. These errors in the output not a problem for me. I think they were caused by a lack of resources in the tenant:
> Error: rpc error: code = Unavailable desc = transport is closing
> Error: rpc error: code = Unavailable desc = transport is closing
> Error: rpc error: code = Unavailable desc = transport is closing

**Comment by lvirbalas** [comment]
> With vcd_firewall_rules and vcd_snat resources all ok.
> Thank you.

Did you really wanted to say "with"? If yes, then I'm confused what change you have made to make it work :) Please rephrase.

**Comment by dalfos** [comment]
> Did you really want to say "with"? If yes, then I'm confused what change you have made to make it work :) Please rephrase.

instead of `vcd_firewall_rules` and `vcd_snat`
used `vcd_nsxv_firewall_rule` and `vcd_nsxv_snat`
