### ISSUE TITLE
unable to change disk size when deploy VM

### ISSUE THREAD

**Issue by reski-rukmantiyo** [terraform-providers/terraform-provider-vcd#516]
### Terraform Version
- Terraform v0.12.24
- Provider.vcd v2.8.0
- vCloud Director 9.7.0.5

### Affected Resource(s)
- vcd_vapp_vm

### Terraform Configuration Files
I'm using Terraform vCloud Director example to override disk template when deploying VM, the source code taken from [this url](https://www.terraform.io/docs/providers/vcd/r/vapp_vm.html)

```
resource "vcd_vapp_vm" "internalDiskOverride" {
  vapp_name     = vcd_vapp.web.name
  name          = "internalDiskOverride"
  catalog_name  = "Boxes"
  template_name = "lampstack-1.10.1-ubuntu-10.04"
  memory        = 2048
  cpus          = 2
  cpu_cores     = 1

  override_template_disk {
    bus_type         = "paravirtual"
    size_in_mb       = "22384"
    bus_number       = 0
    unit_number      = 0
    iops             = 0
    storage_profile  = "*"
  }
}
```

### Debug Output
Refer to these URLs for log
- [tf.log](https://gist.githubusercontent.com/reski-rukmantiyo/854ffc50cf73b9a9a175e5d1428454aa/raw/9cde94aaa6f16bb993a007c073b8831a67e8523c/tf.log)
- [go-vcloud-director.log](https://gist.githubusercontent.com/reski-rukmantiyo/854ffc50cf73b9a9a175e5d1428454aa/raw/9cde94aaa6f16bb993a007c073b8831a67e8523c/go-vcloud-director.log)
```shell
export TF_LOG_PATH=tf.log            
export TF_LOG=TRACE                  
export GOVCD_LOG_FILE=go-vcloud-director.log
export GOVCD_LOG=true     
```

### Expected Behavior
We can deploy customized VM with customized storage based on that parameter that we input previously. Using the same OVA templates and _vcd-cli_ python apps, I able to deploy VM with customized storage. And also, I can run this with previous _vCloud Director 9.1_

### Actual Behavior
```
Error: error managing internal disks : error updating VM disks: error updating VM disks: API Error: 400: [ ec0803f4-2163-49a6-af12-b2cbe211c793 ] The hard drives of the virtual machine "internalDiskOverride" may not be modified, once created.

  on vm.tf line 71, in resource "vcd_vapp_vm" "internalDiskOverride":
  71: resource "vcd_vapp_vm" "internalDiskOverride" {
```

### Steps to Reproduce
just run `terraform apply`

### Important Factoids
It used to works at vCloud Director 9.1, but since upgrade to vCloud Director 9.7.0.5, problem arise.

**Comment by vbauzysvmware** [comment]
Hi @reski-rukmantiyo. It's vCD complain, not terraform.
Please check that VDC isn't fast provisioned or disk size isn't smaller than existing in template.

**Comment by reski-rukmantiyo** [comment]
Hi @vbauzysvmware , the reason why I ask here, is that in previous vCD it's working.
And also I able to create new VM by using vcd-cli (python apps).

**Comment by vbauzysvmware** [comment]
@reski-rukmantiyo I can't reproduce this as I don't have your env settings and template you use. When vCD complains with error "API Error: 400: [ ec0803f4-2163-49a6-af12-b2cbe211c793 ] The hard drives of the virtual machine "internalDiskOverride" may not be modified, once created." it's usually VDC is fast provisioned. This error from vCD, not terraform. I can't comment much on vcd-cli as don't know details on what you do with it.

**Comment by reski-rukmantiyo** [comment]
Noted for this. fyi, i take this little apps vcd-cli from [vmware.github.io](http://vmware.github.io/vcd-cli/). Quite simple apps.
Just running :
```
vcd vapp create -c "Private Catalog" -t  "ubuntu-18.04-modified-v1" -m 1024 -u 2 -k 20480 \
-v VM_TEST -a -nnetwork-312dqwdqw4r12341qwe VM_TEST
```
aside from I have to change my tf code to adapt with 9.7.0.5
thanks, you can close the issue.

**Comment by lvirbalas** [comment]
@reski-rukmantiyo Did you find what is different in your new VCD compared to the previous one? Could you provide details/screenshot of your VDC settings? I'm curious to understand what may not be allowing for this disk size adjustment.

**Comment by reski-rukmantiyo** [comment]
Hi @lvirbalas ,

Following is my vdc settings 
- [VDC settings 1](https://1drv.ms/u/s!AtdAagydqYKUnak_apn_wNOLyqcYnQ?e=ZcSwLc)
- [VDC settings 2](https://1drv.ms/u/s!AtdAagydqYKUnak-ZlAVirxbddX9tg?e=2guWyQ)

**Comment by vbauzysvmware** [comment]
@reski-rukmantiyo if you untick `fast provisioning` in second screen it will allow to resize disk. 
If you try resize fast provisioned disk in UI, you will see the same error.

**Comment by reski-rukmantiyo** [comment]
Thanks @vbauzysvmware and @lvirbalas for the info.
Yes, maybe this is the difference that makes I unable to resize the disk.

But just wondering and it's quite interesting, is there any fundamental difference with vcd-cli from vmware.github.io. Because I'm confident enough to say, that vcd-cli support disk resize although my config is Fast Provision. If the fault is in the underlying vCloud Director, how come 2 apps come with different result. But this is only my curiosity. You dont have to follow up this.

Thanks

**Comment by vbauzysvmware** [comment]
To get answer for 100% I would need to analyze vcd-cli, but my guess is that vcd-cli using old API calls which allowed that.
