### ISSUE TITLE
Guest customization - cannot reset root password

### ISSUE THREAD

**Issue by ewypych** [terraform-providers/terraform-provider-vcd#52]
### Terraform Version
v0.10.2

### Provider vCD Version
version = "~> 1.0"

### Affected Resource(s)
Please list the resources as a list, for example:
- vcd_vapp

### Terraform Configuration Files
```hcl
resource "vcd_vapp" "server" {
  name              = "TERRA-TEST"
  catalog_name      = "Linux"
  template_name     = "TEMP-CentOS-7.3"
  memory            = 1024
  cpus              = 1
  network_name      = "${var.vcd_number}_NETWORK_01"
  storage_profile   = "SILVER"
  ip                = "${cidrhost(var.internal_net, 110)}"
}
```

### Expected Behavior
vApp should be deployed and VM should be customized. The template has checked "Enable guest customization" and also "Allow local administrator password", "Auto generate password" and "Require administrator to change the password on first login", so the "Guest OS Customization" tab in the new VM should have the same configuration. Root password should be generated and listed on the tab. 

![image](https://user-images.githubusercontent.com/25039172/29762131-1b510a2e-8bcd-11e7-9c2e-6fd5dc1eb085.png)

### Actual Behavior
The new deployed VM has unchecked mentioned checkboxes (excluding "Enable guest customization") and the root password is not changed.

![image](https://user-images.githubusercontent.com/25039172/29762367-7c322ae8-8bce-11e7-97a1-ee5bf15e7284.png)

### Steps to Reproduction
1. Run terraform apply
2. Check "Guest OS Customization" tab in the newly deployed VM.
3. Check whether "Allow local administrator password", "Auto generate password" and "Require administrator to change the password on first login" check boxes are checked.

### Important Factoids
Running on vCloud Director 8.10 - Linux OS.

**Comment by carmineesposito73** [comment]
any news on that?

**Comment by lvirbalas** [comment]
This needs some investigation @vbauzysvmware 

Few remotely related updates in the meantime:

1. Ability to create VM through the vApp resource will be deprecated - only the proper way of creating vApp + n VM resources will be left.
2. Recently (still in master for 2.5.0 release) the following have been added:
2.b. `guest_properties` for both vApp and VM resources.
2.c.  `force` guest customization flag for VM resource.

**Comment by vfuyong** [comment]
@vbauzysvmware @lvirbalas I can confirm that with 2.5 the issue still exists. In 2.6 release notes, there is no fix yet. 

There are API calls to enable password and set password in the guest customization tab. This should be a feature request. It is best to be implemented in the customization block of vcd_vapp_vm. 

customization {
}

**Comment by Didainius** [comment]
@vfuyong ,
I would appreciate if you can test out the code in pull request https://github.com/terraform-providers/terraform-provider-vcd/pull/462
