### ISSUE TITLE
vcd_network_routed "transport is closing"

### ISSUE THREAD

**Issue by bejoycalias** [terraform-providers/terraform-provider-vcd#523]
Crash while creating a basic vcd_network_routed resource.

### Terraform Version
Terraform v0.12.28
+ provider.vcd v2.8.0

vCloud Director version: 9.7.0.16081827

### Affected Resource(s)
vcd_network_routed

### Terraform Configuration Files
```hcl
provider "vcd" {
  user                 = var.vcd_user
  password             = var.vcd_pass
  org                  = var.vcd_org
  vdc                  = var.vcd_vdc
  url                  = var.vcd_url
  allow_unverified_ssl = var.vcd_allow_unverified_ssl
  logging              = true
}
resource "vcd_network_routed" "ocp44-1593160797750" {
  name         = "ocp44-1593160797750"
  edge_gateway = "edge-dal10-5c2b2b62"
  gateway      = "192.168.50.1"
  netmask      = "255.255.255.0"
  shared      = "false"
}
```

### Debug Output
https://publicbucketforsomething.s3.ap-south-1.amazonaws.com/tf.zip

### Panic Output
https://publicbucketforsomething.s3.ap-south-1.amazonaws.com/crash.zip

### Expected Behavior
Create a routed network

### Actual Behavior
Panic

### Steps to Reproduce
terraform apply

### Important Factoids
This is a shared vCloud instance running on IBM Cloud, user has only Org admin permission to specific org

**Comment by dataclouder** [comment]
Hi
Thanks for reporting an issue.
From the logs, it seems that the connection between the client and vCD was broken during the network creation.
You should clean up and start again: remove the network, delete the file terraform.tfstate, and re-run the command.

**Comment by bejoycalias** [comment]
Thank you @dataclouder, I have cleaned up everything and now it's working ! (Not sure, but I have ran it multiple times with tracing, without tracing etc, every time it was failing. Only thing I did not do was to cleanup the state file. Anyways, Thank you)
