### ISSUE TITLE
Creating LB pools, virtual servers etc doesn't automatically enable the LB service in Edge

### ISSUE THREAD

**Issue by bejoycalias** [terraform-providers/terraform-provider-vcd#524]
If I have a NSX Advanced version, when I create the LB pool, virtual servers, doesn't it supposed to automatically enable the LB service in NSX? There is a note in VCD provider documentation "To make load balancing work one must ensure that load balancing is enabled", which I believe is to make sure the NSX version is one with LB support (NSX Advanced+). Or, are we saying that this HAS TO BE a manual step in any case?

### Terraform Version
Terraform v0.12.28
+ provider.vcd v2.8.0

### Affected Resource(s)
vcd_lb_virtual_server, vcd_lb_server_pool

### Expected Behavior
Automatically enable the LB service when I create load balancer virtual server resources

### Actual Behavior
Load balancer virtual servers are created, but the LB service within NSX remains disabled and one has to manually enable it.

### Steps to Reproduce
Create a vcd_lb_virtual_server and check the LB service status in NSX

**Comment by Didainius** [comment]
Hello @bejoycalias ,
You can enable it using parent `vcd_edge_gateway` resource - https://www.terraform.io/docs/providers/vcd/r/edgegateway.html#lb_enabled
If you already have edge gateway created - you can get use of `import` feature to start managing it.

We do not implicitly enable it, because this would be "magic" action. Besides - in Terraform when operating in code we do not see how many resources (say `vcd_lb_virtual_server`) one has defined and we wouldn't know if one should disable load balancing on resource deletion. Enabling it on creation and leaving it enabled during delete doesn't make sense as well.

Hope this helps. I am closing it, but feel free to add comments/reopen if it doesn't work for you.

**Comment by bejoycalias** [comment]
Thanks @Didainius for that input. 

Just to give little more background, this VCD instance is an As-a-service offering from Cloud Service Provider (IBM), where end user gets access to an already provisioned organization, already provisioned VDC[s] under that Org, and permission to manage (up to certain extend) an already deployed Edge within each VDC (This user's max permission is Org Admin). So, what I am trying to do is, 
1) Fetch the details of existing edge deployed in that VDC (which I am unable to do through terraform, currently using vCD API manually) - Is there a way to get this details like edge name, networks etc if I just have the VDC & Org details in hand. I tried a VDC import, but it did not have the Edge details.
2) Configure the LB services, like pools, virtual servers etc through terraform (this doesn't enable the LB service itself). Currently using vCD API/UI to enable the LB service, even though other config is done thru terraform.

As you suggested, I tried importing the existing edge details, but unable to enable just the LB service by adding "lb_enabled = true" to the resource. It fails with below error, looks like terraform expects more than just the Org Admin permissions (even though I can do these configuration manually through the console as Org Admin). 

I used this to import the Edge GW details, which worked fine and I can see the details in tfstate file.
```
resource "vcd_edgegateway" "tf-edgegateway" {
  name              = var.edge_gateway
  configuration     = "COMPUTE"
  external_networks = ["COMPUTE"]
}
```
Then for just enabling the LB service, I tried this (I tried setting the config and external networks values as shown in the imported tfstate file, but that too fails with same error)
```
resource "vcd_edgegateway" "tf-edgegateway" {
  name              = var.edge_gateway
  lb_enabled = true
  configuration     = "COMPUTE"
  external_networks = ["COMPUTE"]
}
```


What is the recommended way to perform above 2 operations when user has only Org Admin permission?

`Error: [edgegateway read] could not process network interface data: unable to create subnet structure for storing in statefile: could not check if IP address was set in configuration: could not read current state configuration: could not look up external network dal10-w02-tenant-external by name: functionality requires system administrator privileges`

**Comment by Didainius** [comment]
>     1. Fetch the details of existing edge deployed in that VDC (which I am unable to do through terraform, currently using vCD API manually) - Is there a way to get this details like edge name, networks etc if I just have the VDC & Org details in hand. I tried a VDC import, but it did not have the Edge details.

Similar to import there is a data source - https://www.terraform.io/docs/providers/vcd/d/edgegateway.html meant for "reading" data only. However it looks that you are hitting a problem here.
I will have to test this scenario and see if it could be improved to work without being an admin
