### ISSUE TITLE
vapp_vm and vapp name mismatch

### ISSUE THREAD

**Issue by slavina-rumenova** [terraform-providers/terraform-provider-vcd#53]
Hi there,

### Description
After an upgrade to Terraform 0.10+ whenever I provision a VM with he configuration above I get a VAPP and a VAPP_VM created with different names. Seems that the VAPP takes the name, specified in the config, and the VM takes a random one.

### Expected Behavior
The names of the vapp and vapp_vm should be the same.

### Actual Behavior
VAPP takes the name, specified in the config, and the VM takes a random one.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan -var vcd_pass=#{password[1]} -var vcd_user=#{user[0]} -parallelism=0 -out=myplan.plan`
2.`terraform apply -parallelism=0 myplan.plan`
### Terraform Version
Terraform v0.10.2

### Affected Resource(s)
- vcd_vapp
- vcd_vapp_vm

### Terraform Configuration Files
```hcl
resource "vcd_vapp" "sample" {
  name          = "sample"
  catalog_name  = "${var.catalog}"
  template_name = "template"
  memory        = 8192
  cpus          = 2
  network_name  = "${var.vapp_network}"
  ip            = "${var.vapp_ip}"
  initscript    = "echo 'Alabama'"
}

### Important Factoids
vCloud Direction version that we use is 8.10.1.4655197

**Comment by slavina-rumenova** [comment]
Seems to work with Terraform 0.10.2

**Comment by bobbydeveaux** [comment]
hi @slavina-rumenova - can I close this?

**Comment by slavina-rumenova** [comment]
sure, it can be closed
