### ISSUE TITLE
Feature Request - Edge Gateway properties  

### ISSUE THREAD

**Issue by srinarayanant** [terraform-providers/terraform-provider-vcd#56]
I have a question on the supported list of APIs, please move it to appropriate location , posting it as issue:

Is it by design that admin apis are are not part of the provider?
The Edge Gateway properties are currently not supported by the API ;
Say for instance assigning a DNAT rule to a routed org network requires an external IP[10.0.0.80] to be sub allocated to an edge gateway  , had to do it manually prior to creating the rules.

###
Link to the script:

https://github.com/srinarayanant/terraform_vcd_examples/blob/master/02_jump_server/vcd.tf

**Comment by ewypych** [comment]
@srinarayanant I think there is a small problem with the privileges. Organization Administrator cannot change suballocation on the Edge Gateway. On the other hand, System Administrator cannot do some operations via API in the Organizations. So imho it would be very hard to manipulate suballocation AND then create a NAT rules. Terraform should use two different users - System Admin for Edge Gateway properties and Org Admin for the infrastructure deployment. Of course since 8.2 you can create different roles and assign them different privileges, but it cannot be unified for many users.

I hope I understood you well.

**Comment by srinarayanant** [comment]
Hello @ewypych  ,
Thanks you ! You got me right , I thought sys admin had all rights of org admin , my lab environment is 8.20 and I did the suballocate via the sys admin at the VCD ui  and then terraform executed the rest of creating nework , launching centos ,  firewall config , DNAT and SNAT via org admin
Regards,
Sri

**Comment by bobbydeveaux** [comment]
Shall we close this, or keep the feature request open for those with sufficient access?

**Comment by gpetrousov** [comment]
Hi guys, I'm facing a similar issue where I want to use terraform to open an external SSH connection using NAT on the Edge Gateway. When I try to apply the config, I get a segmentation error and Terraform reports a crash. Could this be related to the rights for the account I'm using (Account Administrator)?
Thanks

**Comment by gpetrousov** [comment]
@lvirbalas - Thanks for your fast response. I am working on something similar with you. However, the difference for me is that the edge gateway already exists and there is already existing infrastructure not created by me. What I want to do is to add some more VMs and expose their SSH ports. In short, here's my tf config https://gist.github.com/gpetrousov/e5a35b74191fb7ae2f5f61b6ec201c14
While I am able to spin up vApps and VMs inside, Terraform crashes with SIGSEGV every time I apply a DNAT rule. I tried upgrading my role which now says "Virtual Infrastructure Administrator, Network Administrator", but Terraform still crashes. Here's the crash report
https://gist.github.com/gpetrousov/437c9002d7045b25faaaf27edf78b0c6

**Comment by gpetrousov** [comment]
@lvirbalas 
I tried using the full CIDR as you suggested, that did not help.
Moreover, I compiled and tried using the provider from the "vmware-takes-ownership" branch and got a API mismatch when executing terraform plan -out=plan.out

Getting privilege escalation is difficult (corp. environment).

Thanks for your help

**Comment by lvirbalas** [comment]
@gpetrousov could you provide the error log for the API mismatch? We'll take a look.

BTW, which vCD version are you on?

**Comment by gpetrousov** [comment]
Hi @lvirbalas 
I'm not sure about the version, not an expert in this platform. I curled <org name>.vmware.com/api/versions and got a large XML back in which there are a lot of version tags to look through.

Here's the error I got
$ terraform plan -out=plan.out 
Error: Error running plan: 1 error(s) occurred: 
* provider.vcd: something went wrong during authentication: error authorizing: API Error: 406:
The request has invalid accept header. Supported API versions are: [1.5, 11.0, 12.0, 13.0, 14.0
, 16.0, 17.0, 5.1, 5.10, 5.11, 5.12, 5.5, 5.6, 5.7, 5.8, 5.9, 6.0, 7.0, 9.0]

Please not that I am abandoning the development on this platform as it's proving to be inflexible.

**Comment by lvirbalas** [comment]
@gpetrousov you can find vCD version by going to its GUI and clicking Help -> About on the right upper corner. We need to know vCD version, as this error is directly related to it.

From the error it looks like you are connecting to a newer vCD, for which we have added support in the vmware-takes-ownership branch. Currently, major development effort is being put in that branch and soon it will land into master, which will make it easier to download and use all the new features.

**Comment by lvirbalas** [comment]
Got it. Good luck in your next endeavour/platform, @gpetrousov
