### ISSUE TITLE
Move code of govcloudair to this repo

### ISSUE THREAD

**Issue by floriankammermann** [terraform-providers/terraform-provider-vcd#58]
It would be nice if the code of https://github.com/UKCloud/govcloudair could be moved in this repo. Otherwise we always have to create two pull requests (and wait for the first to be accepted, to be able to create the second one), if we need a change in govcloudair, which enables an additional functionality.

**Comment by bobbydeveaux** [comment]
I think it's important to keep the code separate. There are other tools that make use of the govcloudair library other than terraform :)

**Comment by floriankammermann** [comment]
Thanks for the response. Are there other tools on github you know, which are using govcloudair?
