### ISSUE TITLE
VM provisioning fails with vCloud Director 9.0: Error changing vmname

### ISSUE THREAD

**Issue by pasikarkkainen** [terraform-providers/terraform-provider-vcd#60]
I'm using Terraform v0.10.7 and vcd provider 1.0.0. After updating vCloud Director from 8.20 to 9.0 it seems VM/vApp provisioning with Terraform doesn't work anymore. I get this error when running "terraform apply":

vcd_vapp.jumpbox: Still creating... (3m0s elapsed)
vcd_vapp.jumpbox: Still creating... (3m10s elapsed)
vcd_vapp.jumpbox: Still creating... (3m20s elapsed)
Error applying plan:

1 error(s) occurred:

* vcd_vapp.jumpbox: 1 error(s) occurred:

* vcd_vapp.jumpbox: Error changing vmname: &errors.errorString{s:"Error with vm name change: &errors.errorString{s:\"error refreshing vapp before running customization: error decoding task response: strconv.ParseInt: parsing \\\"\\\": invalid syntax\"}"}

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

Exactly the same Terraform configuration did work OK against older version of vCloud Director.

main.tf contents for the vapp in question:

resource "vcd_vapp" "jumpbox" {
    name          = "${var.jumpbox_hostname}"
    catalog_name  = "${var.vcd_catalog}"
    template_name = "${var.vapp_centos7_template}"
    memory        = 1024
    cpus          = 1
    network_name  = "${vcd_network.mgt_net.name}"
    ip            = "${var.jumpbox_int_ip}"
    initscript    = "initscript goes here"

    depends_on    = [ "vcd_dnat.jumpbox-ssh", "vcd_firewall_rules.mgt-fw", "vcd_snat.mgt-outbound" ]

    connection {
        host = "${var.jumpbox_ext_ip}"
        user = "${var.ssh_user}"
        private_key = "${file("/home/foo/.ssh/xxxxx")}"
        timeout = "7m"
    }

    provisioner "file" {
        source = "config.sh"
        destination = "/tmp/config.sh"
    }

    provisioner "remote-exec" {
        inline = [
          "chmod +x /tmp/config.sh",
          "/tmp/config.sh ${var.jumpbox_hostname}",
          "reboot"
        ]
    }
}

**Comment by bobbydeveaux** [comment]
I imagine the API's will have changed considerable for 9.0... 

"vCD 9.0 relieves the requirement to have a Virtual Appliance (vApp) to build a single virtual machine, with this release of vCloud Director users can create virtual machines without having to necessarily create a vApp first. vApps can also be created however they are not required to operate individual virtual machines. vCD creates a vApp container automatically for virtual machines."

If anyone is willing/able to submit a pull request for this to work with vCloud director 9.0 then awesome.. :)

**Comment by Nklya** [comment]
Hello.
I faced the same problem with vCD 9.0.
I can help with debugging and fixing. I know programming a little and can recompile module and make tests.
If someone could point me what part of the code I should change, that would be great.

**Comment by Nklya** [comment]
I've built provider from current master and it resolved my problem.

**Comment by msopula** [comment]
Building the provider fixed the issue for me too. When there will be new binaries in public terraform plugin repository?

**Comment by jackalsh** [comment]
Did not worked for me. I built provider from master branch, but still get an error:
Error: Error applying plan:

```
1 error(s) occurred:

* module.us01-dev-api-proxy.vcd_vapp.instance: 1 error(s) occurred:

* vcd_vapp.instance: Error changing vmname: &errors.errorString{s:"Error with vm name change: &errors.errorString{s:\"error refreshing vapp before running customization: error decoding task response: strconv.ParseInt: parsing \\\"\\\": invalid syntax\"}"}
```

Can someone share working module?

**Comment by Nklya** [comment]
You can build your own provider from my fork with Go 1.9. It should work I think))
https://github.com/Nklya/terraform-provider-vcd

**Comment by urajio** [comment]
This is not "enhancement", this is a fatal error that does not allow me to use the Terraform to manage the infrastructure.

**Comment by Didainius** [comment]
This should not be the case anymore. Feel free to reopen with new sample data if the issue persists.
