### ISSUE TITLE
wrong documentation of firewall rules

### ISSUE THREAD

**Issue by floriankammermann** [terraform-providers/terraform-provider-vcd#65]
In the firewall rules is documented, that the string deny can be used as default action and policy https://www.terraform.io/docs/providers/vcd/r/firewall_rules.html. But actually this is not the case. According to the documentation of vmware the string drop has to be used https://pubs.vmware.com/vca/index.jsp?topic=%2Fcom.vmware.vcloud.api.reference.doc_90%2Fdoc%2Ftypes%2FFirewallServiceType.html.

### Terraform Version
Terraform v0.10.7

### Affected Resource(s)
resource "vcd_firewall_rules" "fw"

### Terraform Configuration Files
```hcl
resource "vcd_firewall_rules" "test-deny" {
  edge_gateway   = "testgateway"
  default_action = "deny"

  rule {
    description      = "deny all connections"
    policy           = "deny"
    protocol         = "any"
    destination_port = "any"
    destination_ip   = "192.168.2.1/23"
    source_port      = "any"
    source_ip        = "192.168.12.1/24"
  }
}
```

### Debug Output
```xml
<?xml version="1.0" encoding="UTF-8"?>
<Error xmlns="http://www.vmware.com/vcloud/v1.5" majorErrorCode="400" message="Value 'deny' not found."
minorErrorCode="BAD_REQUEST" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.vmware.com/vcloud/v1.5
https://whateverhoster/api/v1.5/schema/master.xsd"></Error>
```
### Expected Behavior
deny should have been accepted, according to the documentation of the vcd terraform provider.

### Actual Behavior
vcd doesn't know the default action deny

### References
* https://www.terraform.io/docs/providers/vcd/r/firewall_rules.html
* https://pubs.vmware.com/vca/index.jsp?topic=%2Fcom.vmware.vcloud.api.reference.doc_90%2Fdoc%2Ftypes%2FFirewallServiceType.html

**Comment by mycloudrevolution** [comment]
`default_action = "drop"` is right.

> Default action of the firewall. One of: drop (Default. Drop packets that match the rule.), allow (Allow packets that match the rule to pass through the firewall)

**Comment by Didainius** [comment]
Docs were long time improved since then and also there is a new resource `vcd_nsxv_firewall_rule` which handles firewall rules by using NSX-V API and providing more features.
