### ISSUE TITLE
vcd_firewall_rules doesn't support update

### ISSUE THREAD

**Issue by tl-aiyor** [terraform-providers/terraform-provider-vcd#66]
Error when modifying "vcd_firewall_rules" configuration.

If you createa "vcd_firewall_rules" config and then subsequently change the config., i.e., modifying the value of "source_ip", Terraform would complain that "vcd_firewall_rules" module doesn't support update.

However, in the "vcd_firewall_rules" documentation, https://www.terraform.io/docs/providers/vcd/r/firewall_rules.html, it states that this module supports reate, **modify**, and delete firewall settings and rules.

### Terraform Version

Terraform v0.10.8

### Affected Resource(s)

resource "vcd_firewall_rules" "esg_fw"

#### Original Configuration

```hcl

resource "vcd_firewall_rules" "esg_fw" {
  edge_gateway = "test-nat-gw-01"
  default_action = "allow"

  rule {
    description = "test-fw-01"
	policy = "allow"
	protocol = "any"
	destination_port = "any"
	destination_ip = "any"
	source_port = "any"
	source_ip = "192.168.200.0/24"
  }
}

```

Once the above is applied, and you the try to modify it to below, e.g., change the subnet of source_ip,

#### Modified Configuration
 
```hcl

resource "vcd_firewall_rules" "esg_fw" {
  edge_gateway = "test-nat-gw-01"
  default_action = "allow"

  rule {
    description = "test-fw-01"
	policy = "allow"
	protocol = "any"
	destination_port = "any"
	destination_ip = "any"
	source_port = "any"
	source_ip = "192.168.240.0/21"
  }
}

```

### Debug Output

```

Error: Error applying plan:

1 error(s) occurred:

* vcd_firewall_rules.esg_fw: 1 error(s) occurred:

* vcd_firewall_rules.esg_fw: doesn't support update

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

```

### Expected Behavior

We should expect that the source_ip subnet be changed and updated with the new value.

### Actual Behavior

Terraform module, "vcd_firewall_rules", complains with an error saying that it doesn't support update

### Steps to Reproduce

1. `terraform apply` using the original configuration listed above
2. Modify the configuration file with a new modified/updated subnet value
3. `terraform apply`

**Comment by spengilley** [comment]
Just butted up against this. Will this see light of day at any point?

**Comment by lvirbalas** [comment]
@spengilley thanks for putting this to attention. Actually, would you be open to raising a PR for fixing this? Feels like a relatively self-contained fix.

**Comment by Didainius** [comment]
`vcd_firewall_rules` uses an older type of API which can cause problems.  New `vcd_nsxv_firewall_rule` uses NSX-V API which allows more configuration and has proper update support.
