### ISSUE TITLE
Scaling down VMs in vApp restarts vApp

### ISSUE THREAD

**Issue by MrMorice** [terraform-providers/terraform-provider-vcd#69]
Hello Terraform Community! We have have a suggestion for optimising scale down scenarios! Unfortunately I'm not that fluent in Go to implement it myself. Thanks for your help!

### Terraform Version
Terraform v0.10.4
terraform-provider-vcd_v1.0.0_x4

### Affected Resource(s)
- vcd_vapp_vm

### Expected Behavior
When scaling down (destroying one or more VMs) the other VMs in the vApp should keep running.

### Actual Behavior
When scaling down (destroying one or more VMs) other VMs get shut down and after the deletion restarted. This leads to a disruption of the service.

### Steps to Reproduce
1. Create a vApp with two VM count of 2
2. Reduce the count to 1 for scaling down
3. The vApp gets shut down before deleting the VMs

**Comment by pkleanthous** [comment]
Hi @MrMorice can you add a code snippet of how are you trying to achieve the scale down?

**Comment by MrMorice** [comment]
Hi @pkleanthous thanks for your response. We basically just change the count of the machines via an input variable. Here is a short example:

resource "vcd_vapp_vm" "example" {
  vapp_name       = "${var.vapp}"
  [...]
  count = "${var.examplecount}"
}

Increasing the "examplecount" input variable works fine and the vApp keeps running while we scale up. Decreasing the input variable however will result in a shutdown of all the VMs and then a restart after the machines are destroyed.

The reason for the behaviour is this line in the resource_vcd_vapp_vm.go file that undeployes the vApp before destroying one VM. This is probably legacy functionality from the time where the provider only supported one VM per vApp. But it should not be needed anymore.
https://github.com/terraform-providers/terraform-provider-vcd/blob/master/vcd/resource_vcd_vapp_vm.go#L332

Thanks for your help!

Kind regards,
MrMorice

**Comment by pkleanthous** [comment]
I can confirm the reported behaviour and when you remove a VM resource from a TF file

```hcl
resource "vcd_vapp_vm" "demo-vm-1" {
  vapp_name     = "${vcd_vapp.test-demo.name}"
  name          = "demo-vm-1"
  catalog_name  = "Catalogue"
  template_name = "magic_template"
  network_name  = "${vcd_network.net.name}"
}

resource "vcd_vapp_vm" "demo-vm-2" {
  vapp_name     = "${vcd_vapp.test-demo.name}"
  name          = "demo-vm-2"
  catalog_name  = "Catalogue"
  template_name = "magic_template"
  network_name  = "${vcd_network.net.name}"
}
```

If I remove `demo-vm-2` resource `demo-vm-1` will be restarted

**Comment by dn1s** [comment]
@bobbydeveaux please assign this issue to me. I'll look into it this week.

**Comment by dn1s** [comment]
I did dig into this today and found out it's just a copy + paste error:
```
diff --git a/vcd/resource_vcd_vapp_vm.go b/vcd/resource_vcd_vapp_vm.go
index 89245d7..bfe4e35 100644
--- a/vcd/resource_vcd_vapp_vm.go
+++ b/vcd/resource_vcd_vapp_vm.go
@@ -321,17 +321,17 @@ func resourceVcdVAppVmDelete(d *schema.ResourceData, meta interface{}) error {
 		return fmt.Errorf("Error getting VM4 : %#v", err)
 	}
 
-	status, err := vapp.GetStatus()
+	status, err := vm.GetStatus()
 	if err != nil {
-		return fmt.Errorf("Error getting vApp status: %#v", err)
+		return fmt.Errorf("Error getting VM status: %#v", err)
 	}
 
-	log.Printf("[TRACE] Vapp Status:: %s", status)
+	log.Printf("[TRACE] VM Status: %s", status)
 	if status != "POWERED_OFF" {
 		log.Printf("[TRACE] Undeploying vApp: %s", vapp.VApp.Name)
-		task, err := vapp.Undeploy()
+		task, err := vm.Undeploy()
 		if err != nil {
-			return fmt.Errorf("Error Undeploying vApp: %#v", err)
+			return fmt.Errorf("Error Undeploying VM: %#v", err)
 		}
 		err = task.WaitTaskCompletion()
 		if err != nil {
@@ -349,27 +349,5 @@ func resourceVcdVAppVmDelete(d *schema.ResourceData, meta interface{}) error {
 		return nil
 	})
 
-	if status != "POWERED_OFF" {
-		log.Printf("[TRACE] Redeploying vApp: %s", vapp.VApp.Name)
-		task, err := vapp.Deploy()
-		if err != nil {
-			return fmt.Errorf("Error Deploying vApp: %#v", err)
-		}
-		err = task.WaitTaskCompletion()
-		if err != nil {
-			return fmt.Errorf("Error completing tasks: %#v", err)
-		}
-
-		log.Printf("[TRACE] Powering on vApp: %s", vapp.VApp.Name)
-		task, err = vapp.PowerOn()
-		if err != nil {
-			return fmt.Errorf("Error Powering on vApp: %#v", err)
-		}
-		err = task.WaitTaskCompletion()
-		if err != nil {
-			return fmt.Errorf("Error completing tasks: %#v", err)
-		}
-	}
-
 	return err
 }
```

**Comment by dn1s** [comment]
I'll add this to https://github.com/terraform-providers/terraform-provider-vcd/pull/74 even though it's not used in there right now.

**Comment by Didainius** [comment]
This should be resolved. Feel free to reopen if needed
