### ISSUE TITLE
Can't create a dnat rule with computed IP address

### ISSUE THREAD

**Issue by pkleanthous** [terraform-providers/terraform-provider-vcd#70]
Hi there,

When I'm trying to create a dnat rule with a  `computed` ip address the resource fails.
If I re-run Terraform, the resource succeeds.

### Terraform Version
Terraform v0.10.8

### Affected Resource(s)
- vcd_dnat

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
resource "vcd_dnat" "demo-server-ssh" {
  edge_gateway    = "Internet_ABC"
  external_ip     = "1.2.3.4"
  port            = 22
  internal_ip     = "${vcd_vapp_vm.demo-vm-1.ip}"
  translated_port = 22
  depends_on      = ["vcd_vapp_vm.demo-vm-1"]
}
```

### Debug Output
```
* vcd_dnat.demo-server-ssh: Error completing tasks: &errors.errorString{s:"Error setting DNAT rules: &errors.errorString{s:\"error reconfiguring Edge Gateway: API Error: 400: [ 28086172-7092-44bb-9137-802416f16cf1 ] validation error on field 'gatewayServiceConfigurationSpec.natSpec.ruleList[1].translatedIp': String value should not be empty\"}"}
```

### Expected Behavior
It should create the relevant resource

### Actual Behavior
Terraform apply fails

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

**Comment by Didainius** [comment]
This should work now with using newer `network` block in `vcd_vapp_vm` resources if using `POOL` ip allocation mode. DHCP could also work, but #316 details what are the issues with DHCP (in short vCD cannot guarantee that guest works and reports the IP it got)

**Comment by Didainius** [comment]
@pkleanthous, if you are still interested in getting DHCP IP, you could try and check https://github.com/terraform-providers/terraform-provider-vcd/pull/436 PR and see if it works for you
