### ISSUE TITLE
Add DHCP Pools to Network forces destroy and then create replacement

### ISSUE THREAD

**Issue by mycloudrevolution** [terraform-providers/terraform-provider-vcd#81]
Hi there,

I found a problem or need to request an enhancement for the ressource _vcd_network_. 

### Terraform Version
Terraform v0.11.1
provider.vcd v1.0.0

### Affected Resource(s)
- resource "vcd_network"

### Terraform Configuration Files
```hcl
# VMware vCloud Director Network Variables (Blank)
variable "vcd_edge" {
    description = "vCD Tenant Edge Gateway"
}

# VMware vCloud Director Network Resource Definition
resource "vcd_network" "tf-net" {
  name         = "my-tf-net"
  edge_gateway = "${var.vcd_edge}"
  gateway      = "172.20.0.1"

  static_ip_pool {
    start_address = "172.20.0.100"
    end_address   = "172.20.0.200"
  }

  dhcp_pool {
    start_address = "172.20.0.10"
    end_address   = "172.20.0.20"
  }
}
```

### Expected Behavior
DHCP Pool should be added via in-place update

### Actual Behavior
destroy and then create replacement

### Steps to Reproduce
1. `terraform apply` without DHCP Pool
1. `terraform apply` with additional DHCP Pool

**Comment by Didainius** [comment]
Closing in favor of #421
