### ISSUE TITLE
Error when creating VM on vCD 9.1

### ISSUE THREAD

**Issue by timvdl900** [terraform-providers/terraform-provider-vcd#87]
The error I receive seems identical to the error in issue #60 

### Terraform Version
Tried version 0.10.8 (because the plugin page says 0.10.x is required), 0.11.7 and 0.11.6

### Plugin
Used the vCD plugin Terraform fetches automatically (1.0.0), but also compiled it myself from the latest Git code.

### Affected Resource(s)
- vcd_vapp_vm

### Terraform Configuration Files
```hcl
# Configure the VMware vCloud Director Provider
provider "vcd" {
  user                 = "user"
  password             = "pass"
  org                  = "org"
  url                  = "https://vcd01.domain.com/api"
  vdc                  = "orgvdc"
  max_retry_timeout    = "300"
  allow_unverified_ssl = "true"
}

# Create a network
resource "vcd_network" "net1" {
  name         = "testnet01"
  edge_gateway = "esg01"
  gateway      = "10.123.123.1"

  dhcp_pool {
    start_address = "10.123.123.2"
    end_address   = "10.123.123.20"
  }

  static_ip_pool {
    start_address = "10.123.123.30"
    end_address   = "10.123.123.40"
  }
}

# Create a vApp
resource "vcd_vapp" "vapp1" {
  name          = "terrademo-vapp1"
  description   = "Demo-vApp"
  power_on      = "false"
}

# Create a VM in the vApp
resource "vcd_vapp_vm" "VM1" {
  vapp_name     = "${vcd_vapp.vapp1.name}"
  name          = "terrademo-vm1"
  catalog_name  = "Public Templates"
  template_name = "CentOS 7 x64"
  network_name  = "${vcd_network.net1.name}"
  memory        = 2048
  cpus          = 1
  power_on      = "false"
}
```

### Error received
* vcd_vapp_vm.terrademo-vm1: Error getting VM1 : &errors.errorString{s:"error refreshing vapp: error decoding task response: strconv.ParseInt: parsing \"\": invalid syntax"}

### Expected Behavior
Provisioning should complete successfully.  I've tested the code above against another vCD instance, but version 8.2. Here it works without a problem.

### Actual Behavior
In vCD the vApp seems to be created and I can power it on, so no issues there. It seems to go wrong at the post-deployment stage/checks.

### Steps to Reproduce
1. Create a TF file with the code mentioned above
2. Run 'terraform init' to make sure it's initialized and the vCD plugin is there
3. Run 'terraform apply -parallelism=1'

### Important Factoids
I've checked the vCD debug log, and it seems that Terraform and this plugin currently uses vCD API 5.5. This API is still supported in vCD9.1 (they deprecated everything <5.5 in 9.1).

**Comment by ybaumy** [comment]
same problem here but that might be because im already on 0.11.x terraform version.

Just asking.. is there a plan to develop this further and update it when new terraform version come out?

else it makes no sense to use this provider at all.

**Comment by lvirbalas** [comment]
@ybaumy the provider is actively developed in vmware-takes-ownership branch currently. Please give it a try. It has support up to vCD 9.5 and there are various useful additions as well.

**Comment by dvastazion** [comment]
Thanks @swerveshot @lvirbalas compile the branch work fine for me.

git clone -b vmware-takes-ownership --single-branch https://github.com/terraform-providers/terraform-provider-vcd.git

**Comment by lvirbalas** [comment]
@dvastazion great to hear it! I'll close this issue then. Don't hesitate to reopen if needed.

**Comment by merlin145160** [comment]
I've got exactly the same error with master branch with 9.1
So I've tried to compile
git clone -b vmware-takes-ownership --single-branch https://github.com/terraform-providers/terraform-provider-vcd.git 
but it failed to compile whereas it's ok for master branch.
Any idea ?

**Comment by dataclouder** [comment]
@merlin145160  What's the compile error?

**Comment by merlin145160** [comment]
bastionUbu1604:~/GOPATH/src/github.com/terraform-providers$ git clone -b vmware-takes-ownership --single-branch https://github.com/terraform-providers/terraform-provider-vcd.git
Cloning into 'terraform-provider-vcd'...
<<<>>>

bastionUbu1604:~/GOPATH/src/github.com/terraform-providers$ cd $GOPATH/src/github.com/terraform-providers/terraform-provider-vcd
bastionUbu1604:~/GOPATH/src/github.com/terraform-providers$ go version
go version go1.8.3 linux/amd64
bastionUbu1604:~/GOPATH/src/github.com/terraform-providers$ echo $GOROOT
/usr/local/go

bastionUbu1604:~/GOPATH/src/github.com/terraform-providers/terraform-provider-vcd$ make build
==> Checking that code complies with gofmt requirements...
go install
# github.com/terraform-providers/terraform-provider-vcd/vendor/github.com/vmware/go-vcloud-director/govcd
vendor/github.com/vmware/go-vcloud-director/govcd/monitor.go:206: elapsed.Round undefined (type time.Duration has no field or method Round)
GNUmakefile:9: recipe for target 'build' failed
make: *** [build] Error 2

Do you know when 
https://github.com/terraform-providers/terraform-provider-vcd/pull/143
will be accept ?

Thanks

**Comment by merlin145160** [comment]
Please find my output:

$ git clone -b vmware-takes-ownership --single-branch https://github.com/terraform-providers/terraform-provider-vcd.git
Cloning into 'terraform-provider-vcd'...
<<<>>>

$ cd $GOPATH/src/github.com/terraform-providers/terraform-provider-vcd
$ go version
go version go1.8.3 linux/amd64
$ echo $GOROOT
/usr/local/go

$ make build
==> Checking that code complies with gofmt requirements...
go install
\# github.com/terraform-providers/terraform-provider-vcd/vendor/github.com/vmware/go-vcloud-director/govcd
vendor/github.com/vmware/go-vcloud-director/govcd/monitor.go:206: elapsed.Round undefined (type time.Duration has no field or method Round)
GNUmakefile:9: recipe for target 'build' failed
make: *** [build] Error 2

Do you know when https://github.com/terraform-providers/terraform-provider-vcd/pull/143 will be accept ?

Thanks

**Comment by dataclouder** [comment]
Branch `vmware-takes-ownership` requires go 1.10

Could you try with a newer Go version? It should also work with 1.11, but it has not been tested extensively yet.

**Comment by merlin145160** [comment]
@dataclouder After upgrading to go 1.10, compile is now ok.
terraform init && terraform plan --out plan are ok too
Tomorrow, I will work with my receipt as I've a new vCloud 9.1 ready to prod.
I will report back if I face new issue.
Thanks

**Comment by lvirbalas** [comment]
> Branch vmware-takes-ownership requires go 1.10 (Sorry, I forgot to update the README file about the change)

@dataclouder please update while PR to master is open.

**Comment by Asgoret** [comment]
@dataclouder issue is still here. See https://github.com/terraform-providers/terraform-provider-vcd/issues/68

**Comment by dn1s** [comment]
@Asgoret I don't get your error. I'm using 9.5 but with one addition to your tf file.
```
# Create a VM in the vApp
resource "vcd_vapp_vm" "VM1" {
  vapp_name     = "${vcd_vapp.vapp1.name}"
  name          = "terrademo-vm1"
  catalog_name  = "Public Templates"
  template_name = "CentOS 7 x64"
  network_name  = "${vcd_network.net1.name}"
  ip = "allocated"
  memory        = 2048
  cpus          = 1
  power_on      = "false"
}
```
