### ISSUE TITLE
'initscript' is being set after the VM is powered on, when the vApp is created

### ISSUE THREAD

**Issue by lrichero** [terraform-providers/terraform-provider-vcd#88]
Hi,

'initscript' is being set after the VM is powered on, when the vApp is created.

### Steps to Reproduce

1) Create a vApp template with an 'initscript' "touch /tmp/file1.txt" were setted to a Linux VM in the vApp.

2) From terraform, create a new vApp using this template and set 'initscript' to "touch /tmp/file2.txt"

### Expected Behavior
The /tmp/file2.txt should be created

### Actual Behavior
The /tmp/file1.txt is created

### Terraform Version
`terraform -v`
Terraform v0.11.7

### Terraform-provider-vcd Version
Last vesion, from branch "master" commited on Dec 6, 2017

### Posible solution
I tried changing the order when that was done in the file 'vcd/resource_vcd_vapp.go' at the function  'resourceVcdVAppCreate('...

And it worked as expected.

Original fragment code:

			if d.Get("power_on").(bool) == true {
				err = retryCall(vcdClient.MaxRetryTimeout, func() *resource.RetryError {
					task, err := vapp.PowerOn()
					if err != nil {
						return resource.RetryableError(fmt.Errorf("Error powerOn machine: %#v", err))
					}
					return resource.RetryableError(task.WaitTaskCompletion())
				})

				if err != nil {
					return fmt.Errorf("Error completing powerOn tasks: %#v", err)
				}
			}

			initscript := d.Get("initscript").(string)

			err = retryCall(vcdClient.MaxRetryTimeout, func() *resource.RetryError {
				log.Printf("running customisation script")
				task, err := vapp.RunCustomizationScript(d.Get("name").(string), initscript)
				if err != nil {
					return resource.RetryableError(fmt.Errorf("Error with setting init script: %#v", err))
				}
				return resource.RetryableError(task.WaitTaskCompletion())
			})

New fragment code:

                        initscript := d.Get("initscript").(string)

                        err = retryCall(vcdClient.MaxRetryTimeout, func() *resource.RetryError {
                                log.Printf("running customisation script")
                                task, err := vapp.RunCustomizationScript(d.Get("name").(string), initscript)
                                if err != nil {
                                        return resource.RetryableError(fmt.Errorf("Error with setting init script: %#v", err))
                                }
                                return resource.RetryableError(task.WaitTaskCompletion())
                        })

                        if d.Get("power_on").(bool) == true {
                                err = retryCall(vcdClient.MaxRetryTimeout, func() *resource.RetryError {
                                        task, err := vapp.PowerOn()
                                        if err != nil {
                                                return resource.RetryableError(fmt.Errorf("Error powerOn machine: %#v", err))
                                        }
                                        return resource.RetryableError(task.WaitTaskCompletion())
                                })

                                if err != nil {
                                        return fmt.Errorf("Error completing powerOn tasks: %#v", err)
                                }
                        }

**Comment by lrichero** [comment]
I updated de section of fragments of code, because in git format is not correct visualized.

**Comment by lvirbalas** [comment]
Fix (PR #119) merged into vmware-takes-ownership branch.
