### ISSUE TITLE
Implement Catalog resource

### ISSUE THREAD

**Issue by lvirbalas** [terraform-providers/terraform-provider-vcd#94]
Feature request for a new Catalog Item resource

### Context

The new go-vcloud-director SDK has support for creating Catalogs. Let's implement a new resource in Terraform to be able to create them.

Afterwards we can use Issue #93 for uploading catalog items (OVAs) into it.

### Affected Resource(s)

Addition of the Catalog will be useful for the following resources:
- vcd_catalog_item
- vcd_vapp_vm

### Terraform Configuration Files

Suggested configuration:

```hcl
resource "vcd_catalog" "OperatingSystems" {
org = "Solpan" # Optional, if defined at provider level

name = "OperatingSystems"
description = "Fresh OS templates"

delete_force      = "true" #when deleting force=True along with recursive=True to remove a catalog and any objects it contains, regardless of their state
delete_recursive  = "true" # when deleting recursive=True to remove a Catalog and any objects it contains that are in a state that normally allows removal
}
```

### Expected Behavior

Terraform vCD provider should create the defined catalog, which can then be used for uploading items into it. On a practical side, Catalog Item resource will have to depend (wait) until catalog is created. Example:

```hcl
resource "vcd_catalog_item" "PhotonTemplate" {
org = "Solpan" # Optional, if defined at provider level

catalog = "OperatingSystems" # To which catalog to upload the item

name = "Photon-2.0-HW11"
description = "Photon 2.0 OVA with hardware v11"
ova_path = "/opt/ovas/photon-custom-hw11-2.0-304b817.ova"

depends_on = ["vcd_catalog.OperatingSystems"]
}
``` 

### References

https://github.com/terraform-providers/terraform-provider-vcd/issues/93

**Comment by lvirbalas** [comment]
@vbauzysvmware please make the following additions to this functionality:

- Change `upload_piece_size` unit of measurement from bytes to MB, so it's easier to type in configuration.
- Make `upload_piece_size` resource parameter optional and set the default value as 1 (MB).

**Comment by lvirbalas** [comment]
@vbauzysvmware another ask:

- Right now `vcd_catalog_item.Photon: upload progress xx.xx%` messages are being sent to os.Stdin. This leads to the fact that they are invisible in some terminals (one example is GoLand's "Run" window). Please see if it's possible to send them to os.Stdout and still have them work.

**Comment by vbauzysvmware** [comment]
Fixes are done.
