### ISSUE TITLE
Implement vApp Network resource

### ISSUE THREAD

**Issue by lvirbalas** [terraform-providers/terraform-provider-vcd#97]
Feature request to support vApp level network

### Description

Currently only Org VDC Network resource (vcd_network) is available. Let's add a vApp level Network resource.

### Affected Resource(s)

New resource required:
- vcd_vapp_network

The above network will take as reference the vApp resource:
- vcd_vapp

The created vApp network can then be used in the VM resource:
- vcd_vapp_vm

### Terraform Configuration Files

Suggested schema for the new resource:

```hcl
# vApp network
resource "vcd_vapp_network" "VAppNetwork" {
  name         = "VAppNetwork"
  vapp_name = "VAppWithNet" # Which vApp should get this network

  gateway = "192.168.10.1"
  netmask = "255.255.255.0"
  dns1       = "8.8.8.8"
  dns2       = "1.1.1.1"
  dns_suffix = "biz.com"
  guest_vlan_allowed = true

  static_ip_pool {
    start_address = "192.168.10.2"
    end_address   = "192.168.10.100"
  }

  dhcp_pool {
    start_address = "192.168.2.2"
    end_address   = "192.168.2.50"
  }

}
```

Then we need to make network parameter of the VM to accept either `vcd_network` or `vcd_vapp_network`:

```hcl
resource "vcd_vapp_vm" "TerraformVM" {
  vapp_name     = "VAppWithNet"
  name          = "TerraformVM"
  catalog_name  = "OperatingSystems"
  template_name = "Photon-2.0-HW11"
  memory        = 384
  cpus          = 1
 
  network_name = "VCDNetwork"
  # or
  # Additional to the current vcd_network value
  vapp_network_name = "VAppNetwork"

  accept_all_eulas = "true"
}
```

### Expected Behavior

A vApp network is created inside the referenced vApp, which can then be attached to its VMs.

### Creating vApp Network Manually

Here's a manual way of reproducing this behaviour to aid in development:
- Go to vCD GUI
- Create an empty vApp
- Click on it and select "Networking"
- Press the "+" symbol and select "vApp network"
- Specify all the network details and create it
- Add two VMs inside this vApp and select the above created network for both of them, deploy
- Login to one of the VMs and try SSHing into the other VM, it should work as both VMs are on the same vApp network

**Comment by vbauzysvmware** [comment]
Code for moment in dev branch: terraform-providers:vmware-stash-while-master-pr-open later will be merged to master.
