### ISSUE TITLE
vCD Create vApp and VM resources fails to complete

### ISSUE THREAD

**Issue by 8bitnz** [terraform-providers/terraform-provider-vcd#99]
Attempting to create vApp or VM's via a Terraform plan fails to complete successfully. The resources are usually created (unless there are dependencies), but the apply fails to complete (and appears to time out). Resources show 'Still Creating', though the vCloud Director tasks are complete.

### Terraform Version
Terraform v0.11.8
+ provider.vcd v1.0.0

### Affected Resource(s)
provider.vcd

### Terraform Configuration Files
https://gist.github.com/8bitnz/5aefb71c572d3bf8f4da75490ad2a490

### Panic Output
* vcd_vapp.ajs-tf-vapp: Error changing vmname: &errors.errorString{s:"Error with vm name change: &errors.errorString{s:\"error refreshing vapp before running customization: error decoding task response: strconv.ParseInt: parsing \\\"\\\": invalid syntax\"}"}

### Expected Behavior
Create a network, vApp and VM

### Actual Behavior
Created the network, created the vApp and VM. Network creation task last status was, still creating, even after the vCloud Director task completed. Terraform plan does not identify any resources as created. 

### Steps to Reproduce
1. `terraform apply`

### Important Factoids
vCloud Director version 9.1.0.1 

### References
Based on examples here - https://mycloudrevolution.com/2018/01/02/vmware-vcloud-director-provider-for-terraform

**Comment by rohitgabriel** [comment]
Same issue:
main.tf:
terraform {
  required_version = "> 0.11.7"
}

data "template_file" "init" {
  template = "${file("${path.cwd}/setup.sh")}"
}

provider "vcd" {
  user = ""
  password = ""
  org = ""
  url = "https://host.com/api"
  vdc = ""
  max_retry_timeout = "120"
  allow_unverified_ssl = "true"
}

resource "vcd_vapp" "web2" {
  name          = "web2"
  network_name = ""
}

resource "vcd_vapp_vm" "web-vm" {
  vapp_name     = "${vcd_vapp.web2.name}"
  name          = "web-vm"
  catalog_name  = "Appliances and media"
  template_name = "Ubuntu-1604-linux"
  memory        = 3096
  cpus          = 1
  network_name = "TWG-ICP"
  initscript    = "${data.template_file.init.rendered}"
  power_on = "true"
}

output "vm_ip" {
    value = "${vcd_vapp_vm.web-vm.ip}"
}

----------
terraform apply
Error: Error applying plan:

1 error(s) occurred:

* vcd_vapp_vm.web-vm: 1 error(s) occurred:

* vcd_vapp_vm.web-vm: Error getting VM1 : &errors.errorString{s:"error refreshing vapp: error decoding task response: strconv.ParseInt: parsing \"\": invalid syntax"}

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

--------
The vapp and VM are created but terraform errors out. It does not turn on the VM. Does not save the infrastructure state.

**Comment by rohitgabriel** [comment]
Update: This issue does not occur when the vcd provider plugin is built from source and placed in plugins directory.

**Comment by bobbydeveaux** [comment]
Thanks @rohitgabriel  - possibly looks as though the latest release (Aug 2017) doesn't have the fix for this.. @radeksimko  - are we okay to do a release? there's a number of commits to master since the last release.

**Comment by pasikarkkainen** [comment]
Yes please, a new release would be good to have. Also my PR about fixing vm guest customization (https://github.com/terraform-providers/terraform-provider-vcd/pull/92) is not merged yet, and it's an important bugfix to have.

**Comment by 8bitnz** [comment]
I suspect this one is also related - VCD provider crash creating vapp_vm #103.
I'll try building the provider and confirm @rohitgabriel findings.

**Comment by 8bitnz** [comment]
I can confirm when using a provider that is built from source the plan completes without issue.

**Comment by bobbydeveaux** [comment]
@katbyte @radeksimko  - any chance we can get a release please? :)

**Comment by Didainius** [comment]
@8bitnz, I believe this shouldn't be an issue anymore. Could you check if it is still relevant and file a new issue with up to date details.
